== Section II.

[.blurb]
=== Reciting several difficult exercises he went through, both inwardly and outwardly, between his convincement and the setting up of a public meeting at Lurgan

Whilst I was at sea, self reasoned strongly to save the duty on my goods,
for I had an opportunity to do it,
the troop my brother belonged to quartering at Carrickfergus and Belfast,
who would have helped me night or day.
But I durst not do it, my conscience being awakened to plead for truth,
justice and equity; yet there was a great contest between conscience and self,
and in this conflict many Scriptures were opened in my understanding,
that duties and customs ought to be paid; and though self struggled hard for mastery,
jet at last was overthrown, and the judgment of truth prevailed.

I landed at Carrickfergus, where a trooper readily lent me his horse,
and I rode that evening home to Antrim, where my wife lived.
When I came to the door, my brother came forth to salute me with his usual compliments;
but the Lord`'s power seized upon me at that instant, he was struck amazed,
went in and sat down silent.
I was much broken in the power of the Lord before them,
and my brother made no opposition, but received the truth and joined with it.

I returned to Carrickfergus to bring my goods ashore,
but the officers required an oath to the truth of my bills of parcels,
and not suffering them to come ashore without it, would have seized upon my goods.
I told them, I could not swear, for it was contrary to Christ`'s command,
which seemed a strange thing to them, not having met with the like before;
but the Lord`'s truth and testimony was precious to me, and after some time,
with much difficulty, I got an order to bring my goods to the custom-house.
My deportment to the officers and others herein was a wonder to them,
and caused much discourse and various rumours to be spread of the Quakers,
and of me in particular.

After I came home with my goods, the Lord`'s hand was heavy upon me day and night,
so that I travailed under a great conflict between flesh and spirit,
and was much cast down with sorrow and trouble of mind;
but none there understood the cause of my sorrow and trouble,
or gave a word of comfort to ease me.
I would have gone far for the company of an experienced Friend.
My sleep departed from me, and many times in the night in great trouble of mind,
crying and weeping, I wished for day, and when day came my sorrows remaining,
I wished again for night.
In this restless state I had none who had trod this path to converse with;
so that the rumour of my condition spread abroad among the professors;
many would come to gaze on me, jangle and contend against truth, and some would say,
I was bewitched; others, I was going mad.
So talk and rumour concerning me spread a great way among people.

About this time one Miles Bousfield came from England to Ireland,
at whose house George Fox had been.
He had been in some degree convinced of the truth, and came away upon it;
he was a great talker of religion, but an enemy and a stranger to the cross of Christ.
Hearing of me, and of the exercise I was in, he came to see me.
I was not at home when he came, but he talked to my wife,
and spoke well of the Quakers and their principles,
seeming to be glad that he had found such a companion in this nation as I was,
and the comfort we should have of one another.

When I came home, my wife told me of his having been there,
and the discourse he had with her, of which I was glad to hear,
and soon took my horse and rode twelve miles to see him, and stayed with him all night.
He talked abundance of religion, and of the inward work of God in man by his spirit,
and spoke well of George Fox and James Nayler, and of their doctrine, which I liked well;
but said, he knew those things before he saw or heard them;
and spoke much of his knowledge of God and Christ.
I sat in silence with attention to hear him; for I was cast down,
poor and low in my spirit,
yet glad that I had met with such a knowing man in the things of God,
and his work in man by his spirit, to advise me in my great troubles of a wounded spirit.
He advised me to be cheerful and merry, and not to look at those inward troubles,
that bowed me down; which was the enemy`'s work to lead me into despair, and destroy me,
by swallowing me up in much trouble; and as it was plainly manifest,
that God had a love for me, to make me a chosen vessel of mercy,
he would love me to the end; and nothing in me could hinder his love,
or frustrate his will.

This doctrine healed me without the cross of Christ, or self-denial;
which answered my will and carnal desires;
for I loved the truth which I was convinced of, and would have had it,
together with my carnalities, fleshly liberties, worldly pleasures and profits;
so when the Lord`'s power would rise to bow me down under his cross,
I would reason against it with those arguments aforementioned,
and thereby would get from under judgment.
But this ease and slight healing lasted only about a week;
for the Lord would not leave me so, praised be his name forever,
whose merciful hand preserved me,
and his power took fresh hold of my heart and inward parts,
which bowed me under his judgments, and opened the eye of my understanding,
plainly showing me there was that alive in me that must be crucified,
which opposed the will of God.

Then I saw where Bousfield was, and all of his spirit,
and the wounds of my restless spirit were opened wider than before,
and Major Bousfield`'s slight cure was all marred,
and the false rest he set me in taken away.
I had none now to trust to but the Lord, for counsel and information,
whose care was greatly manifested for my preservation, redemption and information,
through many temptations and deep afflictions that did attend me many ways,
with many opposers and contenders.
I was weak, but the Lord`'s strength was perfect in weakness,
and his spirit and power increased in me through obedience to the cross of Christ,
wherein I was daily exercised, and thereby grew into acquaintance with the Lord`'s work,
to make me a vessel for his purpose.

In the spring following, I removed with my family from Antrim,
to live in the county of Armagh; took a house and grazing for my cattle,
and kept a shop of some merchant goods,
where I became the talk and gazing-stock of the people.
Professors watched me narrowly to get occasion against me,
and the principles of truth I professed,
but the Lord strengthened me in my watch over my words and deeds,
and so cut off occasion from them that sought occasion against the truth and me.

In those days to use the plain and proper speech, as thee and thou to a single person,
and keeping on the hat, were strange things to people,
and few could suffer them to be used; but would reflect in abusive words,
and sometimes use blows, or throw stones.
Keeping to one price in selling goods, and to the first asking without abatement,
was a great stumbling-block to most sorts of people,
and made them stand at a distance from buying for some time,
until they saw further into the justice thereof All
things were rough and rugged in the world,
and the cross of Christ was foolishness and a stumbling-block to them.

My exercises and trials both within and without were many, and of divers sorts,
beyond what I can express.
The Lord`'s judgments clave close to me; I was made to love them,
and willing to wait upon the Lord in the ways thereof.
Sometimes when the Lord`'s hand would be easy with me,
I would be afraid lest he should withdraw his hand;
then my desires were to the Lord not to slacken his hand, but to search me thoroughly;
for his judgments were become sweet to my taste,
which he many times mixed with springs of mercy, to my joy and comfort.
Business in the affairs of the world became a trouble to me,
though there were presentations and opportunities to get riches, either by trading,
taking land by lease, mortgage or purchase, which I was able to do.

My brother being convinced of the truth, my wife,
he and I met together twice a week at my house;
in a while after four more were convinced,
and then we seven met together to wait upon God, and to worship him in spirit and truth.
The Lord`'s mercy and goodness were often extended to us to our comfort and confirmation,
in the appearance of his blessed truth received in our hearts.
