== Section XIV.

In 1694, William Edmundson goes to the Yearly Meeting at London,
having divers comfortable meetings in several shires in England,
and in several counties in Ireland after his return thither.
Also his conference with Dean Reader, concerning tithes, etc.

In the year 1694, it was with me to go to London, to the Yearly Meeting;
so I went first to Dublin to our National Half-year`'s Meeting,
where were Friends from every province, and many things were under our consideration,
for promoting the kingdom of Christ Jesus and his righteous government;
as also for the preservation of Friends from the spots, cumber,
and surfeiting cares of the world and things of it.
The Lord`'s glorious power was with us,
owning our service and concern for his honour and the glory of his great name,
who gave the faithful a spirit and understanding that none could gainsay;
greatly blessing his work in our hands,
and us in the handling of it faithfully with diligence,
preferring it before ourselves or earthly concerns.

When the service of that meeting was over, I took shipping for London,
accompanied by about twelve Friends who went with me to the Yearly Meeting;
also many Friends went on ship-board with us, and there took leave.
The wind favoured to carry us by the French privateers that were then in the channel,
and things were ordered for our safety,
so that we took notice of the providential hand of God therein.
We landed at Nesson; some of us went to Liverpool,
and were with Friends about Bickerstaff, at their Monthly Meeting for business;
from thence we went to Warrington, and near to it met with the rest of our company,
and went together towards London, the Yearly Meeting being at hand.

Near Ridgley we had a meeting at an inn where we lay, and there were many people at it.
We came to London the day before the Yearly Meeting began,
where many elders and faithful brethren were glad of our coming.
I stayed in London about two weeks,
and duly attended public meetings for the worship of God,
and men`'s meetings for truth`'s affairs.
When the service of that meeting was over, I travelled northward,
accompanied by John Pim, and had many large and comfortable meetings in divers places;
Friends`' hearts were glad and well refreshed in that visit;
for the Lord`'s power and wonted goodness accompanied us.
Some of the places where we had meetings, were in Bedfordshire, Hertford, Leicester,
Dunnington, Nottingham, Mansfield, Chesterfield, Stockport and Manchester;
there John Pim left me, and went towards Chester, intending for Ireland.

Being moved of the Lord to turn towards York, I sent to Roger Haydock,
who came to me at Manchester, and went with me to York.
As we went we had a meeting at Leeds, which was full and largo,
where the Lord`'s heavenly presence was with us,
and Friends`' hearts were comforted therein.
From thence we went to York, and it was men Friends`' Quarterly Meeting,
and women Friends`' Yearly Meeting.
There were several hundreds of Friends from divers parts, the Lord was with us,
and many faithful Friends were glad of our company.

There Thomas Trafford met me, and when the service of that meeting was over,
we went to a meeting near Halifax;
from thence Roger Haydock went homewards to Lancashire,
but Thomas Trafford travelled with me.
We had many large powerful meetings at Bradforth, Roidan, Hardcastlegarth, Massam,
Richmond, Swadell, Wentzerdale near Skipton, and Edgeend meeting;
so to Manchester and into Cheshire, and had several meetings of good service;
then went into Lancashire to Hardshaw to their Monthly Meeting,
which was large and powerful, there I met with Leonard Fell;
we were glad to see one another, and truehearted Friends were glad of that visit.
Thomas Trafford and I went back to Cheshire, and so through Wales to Holyhead,
and stayed there about a week for a passage; then took shipping for Ireland,
landed at the hill of Hoath and came to Dublin.
I stayed the first-day meeting there, and then came to my son-in-law, William Fayle`'s,
and from thence to Mountmellick, where Friends received me gladly.

I attended meetings for the worship of God, as they fell in course,
and was with Friends in managing church affairs, both in Monthly, Six Weeks,
Quarterly and Half-yearly Meetings; and as the service of truth increased,
the increases of God were multiplied in our hearts,
and gave us ability to perform it to his glory, and our great comfort and satisfaction.
From our Half-year Meeting at Dublin, in the ninth month, 1694,
I went to visit Friends in several counties, and had meetings at Wicklow,
John Wickham`'s, Israel Webster`'s, Shellaly, Castledermot, Province Meeting,
and at Waterford, Clonmel, Kilcommon and Cashell;
there several of our Friends met me and accompanied me homewards.

The first day of the second month, 1695, I took my journey towards the north,
to visit Friends, and had a comfortable meeting near Castle Jordan,
many Friends of our Monthly Meeting being with me there.
When the meeting was ended we parted in the tender love of God.
I went on my journey towards the north, accompanied by my son-in-law,
William Fayle and John Barcroft;
the next day we came to Old-castle and stayed a meeting there;
several Friends came to it from other places,
it being their men`'s and women`'s meeting day, for ordering church affairs.
The next day we had a meeting fifteen miles from thence, near Ballyhayes,
where were many Friends, and we were well refreshed,
the Lord`'s presence and goodness being with us.

The next day we travelled about thirty miles into the county of Armagh,
and the day following, being the first-day of the week,
we were at the meeting at Ballyhagan, at which were many Friends:
we were greatly comforted together, and glad to see one another.

From thence we went beyond Charlemount to visit Friends,
and had a comfortable meeting with them;
then came back to Ballyhagan to their fifth-day meeting,
and stayed there until the Province Meeting,
it being their Quarterly Meeting both for the worship of God,
and ordering of church affairs, which held part of three days, and was very large;
so that some Friends said they never saw the like there before.
Friends were well refreshed, for the glory of the Lord shined among us,
his power was over all, and his Seed in dominion.
I was helpful there to Friends,
in the ordering and managing of truth`'s affairs in the church,
and they were willing and glad to be advised, for that the Lord Jesus,
who called me into the ministry,
gave me a measure of understanding in the ground of church government,
discipline and Gospel order.
The meeting ended, and Friends and brethren parted in great love, union,
and comfort of the Lord`'s holy Spirit.

The priest of that parish, one Dean Reader,
had cited several Friends to the bishop`'s court for small tithes,
but had a desire to speak with two or three Friends; and hearing of me,
had a mind to speak with me in particular: so the morning after our meeting was over,
it being the second day of the week, three other Friends, with me, went to his house,
where he was ready to receive us.
We discoursed of things very moderately and at large, for some hours,
about tithes and ministers`' maintenance;
his great and chief plea was the law of the land and the government that gave it them;
and when he had used all his arguments to strengthen his plea,
and I believe saw they were all fully answered, he let his argument fall.
I told him that I had one thing more to offer to him, which if he would do,
I believed it would end the difference; and that was, to do as he would be done unto,
which is the royal law of Christ.
So we left him moderate and loving, parting friendly.

That day we came to John Robson`'s, and from thence to a meeting at Lurgan,
where were many honest-hearted Friends,
and the Lord`'s power and presence were with us to our great comfort and satisfaction.
Next day we were at Lisnegarvy meeting, where were many honest tender Friends,
and we were refreshed in the Lord, and glad to see one another.

From thence we came to Ballinderry, and stayed their first-day meeting,
which was full and comfortable: then to Grange, and rested one day with James Greenwood,
I being unwell.
We went to a meeting near Toberhead, and several Friends from Grange accompanied us.
On the day following we were at a meeting at Dunclaudy,
then returned back again to Grange,
and stayed the first-day meeting there for the worship of God,
and also the men`'s and women`'s meetings for the keeping of good order in the church,
and had good service for the Lord and his truth on several accounts.
Honest-hearted Friends were glad of my company and service;
so we parted well satisfied and comforted with the Lord`'s goodness.

From thence we went to Lurgan to their fourth-day meeting,
which was large and full with Friends and other people,
there being a marriage accomplished in the meeting that day.
I spoke of several things relating to the ordinance of marriage,
as the Lord by his power and spirit opened my understanding and gave me ability:
it was a heavenly powerful meeting.
From thence we went to a meeting the next day at Hillsborough,
accompanied by many Friends, and had a comfortable meeting;
the mysteries of the kingdom of God were opened in the demonstration
of the spirit and power of the Lord Jesus Christ,
his testimony reached the hearts of the hearers,
and God`'s witness sealed the truth of what was declared.

We rode that night five miles to Tobias Courtney`'s, and the next day to Lurgan,
where William Brownlow and William Williamson came to meet me,
and to take their leave of me, both being ancient Friends.
We stayed the first-day meeting, which was very large and full;
many Friends of other meetings came thither,
and the Lord answered their labour and good desires,
in blessing our meeting with the openings and overflowings of his word of life;
it was an opportunity of consolation and sweetness.
After which we took leave one of another in the love
of God and comfort of his holy Spirit.

Next morning we took our journey towards Dublin,
to our third month National Half-year`'s Meeting, in 1695,
in company with Friends from the north, who went up to it.
There was a great appearance of Friends from several parts of the nation,
and the Lord`'s power was with us, in the managing of truth`'s affairs,
both in doctrine and discipline; the meeting held most of three days,
and Friends parted in the peace of God.

From thence I went in the company of many Friends, both of Leinster and Munster,
to our Province Meeting at Castledermot,
where things relating to a holy discipline were managed in the wisdom of God,
and the Lord was with us as formerly in such opportunities and services,
which he sanctifies to his people,
and furnisheth his servants with spiritual gifts to perform, as occasion requires,
and according to the service of the day.
When the meeting was over, I took leave of Friends, and returned to my own dwelling,
being ready to answer the Lord`'s service as it presented,
according to my ability and gift received.

Soon after my return home, I visited Friends at Dublin, Edenderry and Mountrath,
having meetings with them at each place.
Our next Provincial Meeting being at the Moat, I went thither,
where were Friends from several parts, and many other people;
we had a good serviceable meeting, the Lord`'s ancient goodness being with us;
after which I went home.
