== Section XVII.

In 1697, he goes over to the Yearly Meetings at London, Wales, Bristol and Colchester;
visits several meetings through England and Wales for about seven months;
after his return he solemnizes his marriage with Mary Strangman, at Mountmellick.

Soon after this I went to the Moat and was at their meeting on first-day,
and stayed until third-day, there being a marriage and many people at it,
both Friends and others, where I had good service for truth;
and on the first-day following was at our Monthly Meeting in Mountmellick,
where I acquainted Friends in the men`'s meeting of my intention
of going for England shortly in truth`'s service,
and desired their certificate according to the order established among us,
which accordingly was given.

Our Province Meeting for Leinster, was also at Mountmellick,
the 14th day of the first month, 1697,
and lasted two days in the worship of God and church affairs,
being a powerful and consolating meeting; many Friends were there from several quarters,
and we took leave one of another in the sweet tender love of God.
On the 16th day of the said month, I took leave of my family,
who were sorrowful to part with me, and came to Dublin the 18th day of the same,
where I stayed three meetings, the last of which was a mighty powerful meeting,
and things declared and opened in the power of God, not to be forgotten.

After the said meeting, being the 23rd day of the first month,
I went on board the yacht Mary, bound for Holyhead in Wales;
many Friends went to the water-side with me,
where we took leave one of another in the tender love of God;
but three Friends were willing to bear me company in the Lord`'s service, viz.:
Roger Roberts, George Rooke, and John Barcroft.
That night we lay at anchor in Dublin harbour,
the next morning set sail and landed at Holyhead about noon the day following,
being the 25th of the month aforesaid.

The next day we took our journey, and that night lodged at Bangor;
we hired a guide over the mountains,
and came to Clanroust about the middle of the next day,
being the seventh-day of the week, and 27th of the month, where we met with Joseph Ellis,
a shop-keeper, and a Friend`'s son, who much desired we would have a meeting there,
it being a place where no meeting of Friends was settled.
Finding freedom and willingness, we got a meeting at the inn where we lodged;
and although the parish-priest endeavoured all he could to hinder it,
yet many people came into and about the house within hearing,
and the doctrine of the kingdom of Christ was preached
in the demonstration of the spirit and power of God;
the Lord`'s power and authority went over them, and kept them quiet;
and some were reached with the testimony of truth.

After the meeting was over, it being the first-day of the week, David Jones, a Friend,
came to meet us; we went home with him, about eleven miles, and rested the next day.
We had a meeting there on the day following, and were refreshed in the Lord,
and one in another; then we went to a meeting near Dolgelly, at the house of Lewis Owen,
and from thence to Dolobran, to Charles Lloyd`'s, and had two meetings there.
From thence to Llanydlos in the company of several Friends of those parts,
to the Yearly Meeting for Wales,
which held two days for the worship of God and church affairs.
I had good service for the Lord and the good of his people;
the Lord`'s mighty power broke forth among us,
which brought many under his heavenly testimony,
and many bore witness to the truth of what was offered in
the word of life relating to church government among Friends.

When the service of the meeting was over, George Rooke went into South Wales,
to Haverfordwest, and I, with Roger Roberts and John Barcroft,
came to Roger Hugh`'s house, and the next day had a meeting there.
I was very unwell, having got cold, which much disabled me; yet I travelled to Leinster,
where on the first-day of the week we had a large meeting in Friends`' meetinghouse.
Things relating to the kingdom of Christ were opened
in the demonstration of the spirit and power of God;
many being reached, and confessed to the truth of what was spoken.
After the meeting was over, I was very unwell with pain and weakness,
which seized closely on me, and caused me to lie down; and a doctor in that town,
who had been at the meeting, and in whom the witness of God was reached,
which witnessed to the truth of what was spoken, hearing of my sickness,
offered freely to serve me day or night, according to the utmost of his skill,
to recover my health and strength, and was very careful of me,
in applying things that were beneficial.

I stayed there two weeks at Timothy Townson`'s house, Roger Roberts also stayed with me,
and was very helpful, John Barcroft being gone to Warwickshire.
In that two weeks`' time of weakness I had three
meetings with Friends in the house where I lodged,
not being able to go to the meetinghouse,
and I laid before them their shortness in managing
the Lord`'s business in men`'s and women`'s meetings,
by reason whereof the authority of their meeting was much lessened,
and the service of truth not answered.

John Barcroft being returned to us, and I much recovered from pain, though weak,
was willing to go on my journey; so with my two companions and Timothy Townson,
I rode to Ross the 26th day of the second month, 1697.
The next day travelled to Gloucester, and at the request of Friends there,
stayed a meeting, which was appointed the next day,
and was large.. I was strengthened to answer the service in the meeting,
and the Lord`'s power was graciously manifested, which healed me:
after the meeting was over, I sent for several Friends to my lodging,
and discoursed them about things that were amiss among them,
relating to truth`'s affairs.

The next day we rode to Nailsworth ten miles, where was a meeting and a marriage;
I had good service for the Lord.
The day after we rode to Bristol to the Yearly Meeting for eight counties,
which held four days, many elders and brethren being there,
and the heavenly glorious power of the Lord accompanied the service.
I had several opportunities to speak to ministers, elders and others,
in their several stations and services in the church of Christ;
and the Lord`'s eminent glorious power went over all, whereby many hearts were made glad,
and thankful to the Lord for that visit and service.
So in the sweetness of the love of God, and glorious shining of his power,
I took my leave of Friends, and, with my three companions from Ireland, went to Melksham;
William Penn and several others set us on our way some miles.
We had a meeting at Melksham on first-day, to which many came from several places,
and the heavenly doctrine of truth was preached to them,
in the demonstration of the spirit and power of Christ.
The next day we went to Chippenham,
and had two meetings and good service for the Lord and his truth.
From thence to Cain, and had a meeting, to which came several Separates,
and the Lord`'s power in his testimony went over all.

After the meeting was over we rode to Marlborough,
and the next morning Friends coming together, sat down to wait on the Lord,
and were comforted one in another,
then parted in the love of God and sense of his goodness.
We rode that day to Newbury, and from thence to Ore, where we had a meeting next day;
the Lord`'s glorious power was with us, and,
many heavenly things were opened in the doctrine of the kingdom of Christ.

From thence we went to Reading, and on the day following had two meetings,
being the first-day of the week; several of the Separates came to it,
and the testimony of truth in the authority of the Lord`'s blessed power, went over all.
The next day we came to High-Wickham, and had a meeting there on the day following;
after which we went to Thomas Ellwood`'s house,
and on the next day had a comfortable meeting in their meetinghouse at Jordans,
and were refreshed in the Lord.

We lodged that night at Richard Baker`'s,
who accompanied us next day to the Yearly Meeting at London,
being the 20th day of the third month, 1697,
where I and my three companions tarried about ten days in the service of truth,
and were at many heavenly meetings, both for the worship of God,
and men`'s meetings for managing truth`'s affairs, relating to church government.
I had great service on several accounts in that city, and the Lord`'s power went over all.

When the service was over I parted with the elders
and brethren in the tender love of God,
and took my journey towards Colchester,
accompanied by George Rooke and Samuel Waldenfield,
several Friends of London going with us on our first day`'s journey.
Roger Roberts and John Barcroft left us at London, and went towards Ireland.
We had serviceable powerful meetings in our journey to Colchester,
and were there at the Yearly Meeting, which lasted part of three days;
and there was a great collection of Friends from several parts.
I had good service for the Lord and his blessed truth in divers respects,
and in the heavenly authority of the Lord`'s power, his testimony went over all,
both in doctrine and discipline, to the comfort and satisfaction of Friends.

I travelled towards Norwich,
accompanied by George Rooke and Samuel Waldenfield aforesaid,
and had several precious serviceable meetings by the way.
We were at Norwich on first-day at two meetings,
and second-day being their Monthly men`'s and women`'s Meeting for truth`'s business,
I had much service,
and good opportunity to speak to several necessary things relating to church government.
The next day we came to another meeting eight miles from thence,
accompanied by several Friends from Norwich,
and had another meeting the next day but one, about twenty-seven miles distant;
after which Samuel Waldenfield left us, and went to Edmundsbury to a meeting there.

I went to a place called St. Ives, accompanied by George Rooke,
where we had a great meeting and good service for the Lord to the comfort of Friends.
After the meeting was over, we took our leave of Friends,
parting in the tender love of God, and that night came to Ramsey; the next day to Ireby,
about forty miles; and the next morning were at the meeting in Nottingham,
where was a marriage, and a rumour being spread beforehand,
there gathered a great concourse of people,
and some of them were restless by reason of the throng.
After the meeting we rode to Mansfield and stayed a meeting there.

On the day following John Gratton and several Friends came thither;
he went with us to Thomas Brockshaw`'s,
and the next morning he and George Rooke went to a meeting eight miles off,
after which George Rooke came to me again,
and on first-day we had a heavenly powerful meeting at Tupton.
Then we went to John Gratton`'s house, and the next day we rode to Stockport in Cheshire,
where we had a meeting that evening,
and on the day following Benjamin Bangs came with
us to William Barns`'s house at Sankey in Lancashire,
and we went the same day to Liverpool, being the last day of the fourth month, 1697.

We abode some days at Robert Haydock`'s, and had a meeting,
to which Friends came out of the country.
From thence we travelled to Chester, and had a meeting on first-day,
many Friends of the country coming to it.
Here I parted with George Rooke,
having a concern on my mind to visit some meetings in several counties,
and that night I went to John Merrick`'s in Cheshire,
where Friends who lived several miles distant came to see me.
I was at a meeting at Middlewich the next day,
and on the day following had one at Franley;
the Lord`'s power enabled me to perform his service in his heavenly testimony,
which was acceptable to Friends on several accounts, who were glad and well refreshed.

The next day I went to Penketh in Lancashire, and was at a meeting there on a first-day,
which was large and full, many Friends came to it from Cheshire, and other places.
I was also at their Monthly men`'s and women`'s Meetings for truth`'s affairs,
where the Lord`'s power did mightily appear, and I had good service in divers respects.
Travelling towards Yorkshire, I came to John Acridge`'s, and had a meeting near Cain,
which was full and large, and another four miles from thence.
So went to Ireton, and had a meeting there on first-day, which was very large;
the Lord`'s power was greatly manifested therein,
and the mysteries of God`'s kingdom wonderfully opened to
the comfort and satisfaction of that great congregation.

I went to Steeton, and had a meeting; from thence to Bradford,
and had a meeting two miles off; so to Burton,
and had a meeting at Michael Miller`'s house on a first-day;
from thence to Pomfret and Selby; and the next day to their Monthly Meeting at Tuck with;
and from thence to York, and had two meetings on a first-day;
the Lord`'s heavenly power accompanied us to our great comfort and satisfaction.
From York I went towards Burlington, having sent word before,
to have a meeting there the next day; and from thence to Scarborough, and had a meeting;
Friends were tender and well refreshed.

I went to Whitby and had a meeting; and from thence to Gisborough, where Joseph Inman,
a Friend from Ireland, who had come over to visit his relations,
met me and accompanied me until I returned again to Ireland.
At Gisborough I had a meeting on a first-day,
to which came many Friends from several places,
and the Lord`'s power mightily appeared among us; many precious things were opened,
and close Gospel order recommended,
which was very needful there and in many other places,
wherefore it lay upon me to stir up Friends to their duty in Gospel discipline.
I went into Bishopric to Stockton, and a living powerful meeting we had there;
to Darlington, and so to Raby, and had a meeting there;
and from thence over Stainmoor to Sedgberg,
and had a meeting at Friends`' meetinghouse on a first-day,
which was large and very full, many Friends coming far thereto,
and we were well refreshed and comforted in the Lord.
We parted in the love of God, and sweet peace and unity one with another.

I went to Kendal, and had a meeting; from thence to Cumberland,
and was at a meeting at Pardsey-crag;
and at the county Monthly men`'s meeting for church affairs;
and from thence to the Border Meeting on a first-day; and the next day,
being the 30th of the sixth month, we took our journey into Scotland,
and got that night to Dumfries, being twenty-four miles;
and the next day to Moneygoff about forty miles; and so to Port Patrick,
where I sent back my horse with John Rutledge and Henry Iveson,
two Friends who came from Cumberland to accompany us to this place.

Next day we took boat, and on the day following landed at Dunnaghadee in Ireland,
being the 3rd day of the seventh month, 1697.
I hired a horse, and rode to Lisnegarvy twenty miles;
and from thence to Richard Boyes`'s, and had a meeting there on a first-day;
also to Lurgan, and from thence to Ballyhagan, and was at the Province Meeting,
which held part of two days, for the worship of God and affairs of the church.
I went to Dublin in company with several Friends, who had a service to attend there:
the parliament then sitting, I tarried a week,
and attended meetings as they came in course.
Then took my journey homewards, several Friends accompanying me,
and the next day came to my house near Rossenallis,
being the 22nd day of the seventh month, 1697, where I found my family well,
through the Lord`'s preservation, who drew me from them in his service,
and enabled me to perform it for the good of many, to his praise and honour,
who is worthy forever.

Soon after, our Monthly Meeting at Mountmellick occurred,
where I and Mary Strangman presented our intentions
of marriage to the men`'s and women`'s meetings,
and in the week following again to the Province Meeting at Castledermot,
where the Lord was with us.
When the service of that meeting was over, which held part of three days,
I came to Mountmellick.

I went to Mountrath, and stayed two meetings; but the parliament being to sit in Dublin,
and the bishops and priests having prepared two bills to pass into acts,
about their tithes and maintenance, which were likely to fall heavy on Friends,
if granted, I rode to Dublin, accompanied by Gershom Boat and James Hutchinson,
and joined with Friends in using our endeavours with the members of parliament,
to stop the priests`' proceeding;
and in order thereto we drew up in writing our objections,
and ordered them to be printed in readiness to give in to the parliament,
when the priests`' bills came into the house.
We likewise went to one of the lords justices, the lord of Galway,
and acquainted him how those bills, if they passed into acts,
would destroy the fruits of our labours; and gave him a paper,
that he might see what the priests and their servants
had taken from us without those laws;
whereby he might judge what they would do if those bills passed into laws.
We did the like to the chancellor and several of the parliament men,
who seemed to be courteous and concerned for us.
Having put things in as good order as well could be, to answer our opposers,
the parliament also adjourning for one week, I left Dublin and came to Mountmellick,
accompanied by two Friends.

Soon after was our Half-year`'s Meeting in Dublin, and I went thither, where,
with other sincere brethren, we were under an exercise for the promotion of truth,
and removing those things which hinder the prosperity thereof;
and a minute was sent from that meeting to the several provinces,
advising Friends to watch against such hurtful things.
After the meeting was over, I went home to my house and was very unwell for some time,
partly by cold,
and partly by occasion of the exercise I had been under for truth`'s sake;
but the Lord`'s power carried me over and healed me.

Friends having had my intentions of marriage with Mary Strangman
under their consideration for some time,
in men`'s and women`'s meetings, and inquiry being made, and all things clear,
public notice was given of the time and place, and upon the 1st day of the tenth month,
and fourth of the week, 1697,
before a public assembly in our usual meetinghouse at Mountmellick,
we took each other in marriage.
In which weighty affair the Lord`'s heavenly presence accompanied us,
to our great comfort and confirmation; and many in that meeting being sensible thereof,
were refreshed in their spirits; several testimonies were borne to the Lord`'s goodness,
which attended us in that ordinance; everlasting praise to his worthy name forever.
Amen.

I continued some few weeks at my own house,
keeping to our meetings as they fell in course,
until our Province Quarterly Meeting at Castledermot, where I was under some exercise,
but the Lord`'s power and heavenly testimony prevailed, and the service of truth went on,
so that we had a comfortable heavenly meeting, and Friends were refreshed in the Lord.
When the service of that meeting was over,
which held part of three days in the worship of God and public service in truth`'s affairs,
I went home and duly attended the service of our meetings as appointed,
and the Lord blessed his work and his concerned servants therein,
although a worldly selfish spirit in some struggled hard,
yet the Lord crowned his testimony with dominion,
his heavenly power and presence appeared with us and for us,
against that spirit which so predominated in some.
