== Section XVIII.

He visits Friends in the north of Ireland.
His wise counsel in a difficult strait at the Province Meeting.
In 1669, visits Ulster, and some part of Connaught.
At Rapho and Sligo the priests made some opposition.
He settles a meeting at H. Hamilton`'s, and joins with Friends in their provincial visit.

At our following National Meeting at Dublin, in the third month, 1698,
several testimonies were borne in public, against that worldly earthly spirit,
by approved brethren both of England and this nation,
in the demonstration of the spirit and power of God, which was glorious among us there,
as at other meetings upon truth`'s service.
Returning home after the service was over, I kept to meetings about us,
and was at our next Province Meeting at Castledermot, where the Lord`'s sweet,
comfortable presence was with us,
and matters relating to church order and discipline
were closely proceeded on with unity and love,
to the great satisfaction of faithful concerned Friends.
When the service of this meeting was over, which lasted part of three days,
I returned home in the company of Friends,
and kept to meetings about us and to the service of them as usual.

In the sixth month, 1698, I travelled into the north,
and was at the Province Meeting at Lurgan,
which held part of three days in truth`'s service,
and the Lord`'s power was mightily manifested among us to our great comfort;
then I with some Friends travelled together,
and visited most of the meetings in that part of Ulster,
then came up the country to Dublin, and had three meetings there.
Accompanied by several Friends from Dublin, I had two meetings in the county of Wicklow,
and one in the county of Wexford, so came to Leinster Province Meeting at Castledermot,
which held part of three days, and was attended by a large number of Friends.
The heavenly glorious presence of the Lord was among us,
and things relating to church government closely discoursed of,
for the honour of God and good of his people;
the world and things of it in particular were under our consideration,
as they had been often before, viz. the riches, height, finery and delight thereof,
which too much prevailed to the damage of many, and hindrance of truth`'s prosperity;
as also to the grief and wounding of the hearts of true, sincere, self-denying Friends,
who loved the truth more than all.

After much discourse how to stop the stream thereof,
that it might not prevail over our Society, it appeared difficult to accomplish,
and the way intricate, how to deal with such,
to bring them into the bounds of Christian moderation,
to use the creatures in their proper places and services,
for which they were created and given of God to men; and to avoid covetousness.
The way not opening with clearness to proceed, I desired Friends to adjourn the meeting,
which was done; and the Friends of the said meeting met together again,
with many ancient concerned women.
I desired we might be still, and wait on the Lord, that he might open our hearts,
and show how us to proceed in this weighty matter.
Accordingly Friends were all still and quiet,
and the Lord filled our hearts with his holy Spirit and ancient goodness;
so that the meeting was covered with the glory of the Lord, that shined among us;
then a way opened in his divine light, how to proceed in the present affair,
and things were offered to the meeting in that matter
which answered the witness of God in all their hearts,
so that there was an agreement to observe the same;
and many testimonies borne to truth`'s limits and against the covetous worldly spirit.
Friends parted in much gladness, and with great satisfaction.

When the service of the meeting was over, I went home the next day with my wife,
keeping to our meetings as usual, until the ninth month, and then rode to Edenderry,
and was at Friends`' meeting there, and from thence to Dublin,
in company with many Friends going to our Half-year`'s Meeting,
which held three days in the worship of God and church affairs.
Friends were there from several parts of the nation,
and things were carried on in quietness,
though an opposite spirit to truth`'s testimony appeared, yet the Lord`'s power,
which was with us, was over it, and Friends kept in the wisdom of God.

Cold winter weather being come, and I not able to endure hardship,
to travel in truth`'s service as formerly, being ancient,
I kept to meetings as they fell in course.
Our Province Meeting for Leinster being at the Moat, I went thither,
and we had a comfortable meeting,
several Friends in the ministry from England were there,
and had a time to clear themselves in their service,
whereby Friends and others were edified.
Some time after, finding my body able to ride short journeys,
and having clearness in my spirit, I went to Birr, to visit Friends,
and had a good fresh meeting there.

The week following I went to the Moat, accompanied by John Pim and Gershom Boat,
and was at their meeting on first-day, which was full,
and the Lord`'s good presence with us.
Things relating to truth`'s testimony were largely opened in the demonstration
of the spirit and power of Christ--Friends were well refreshed in the Lord,
and one in another: so I took leave of Friends there, and came home.

Not being able to endure hardship in travel, I stayed about home,
keeping to our usual meetings as they fell in course, until the third month.
Then I rode to Dublin to our National Half-year`'s Meeting, which held part of four days,
and a great appearance of Friends from several parts was there,
and the heavenly glorious presence and power of the Lord Jesus was with us,
both in meetings for divine worship,
and those for the service of truth in church affairs;
many things relating thereto were closely managed in the wisdom of God, in great unity,
peace and concord.

The week following I rode to Castledermot,
to our Quarterly Meeting for the province of Leinster, which held part of three days,
and the Lord`'s wonted goodness was plentifully with us to our great comfort and satisfaction,
and truth`'s affairs closely managed in much unity.
We parted in a sense of the Lord`'s goodness,
and I returned home and attended our meetings as usual, until the sixth month;
then finding my health and strength increase, I went a journey towards the north,
and took New Garden and Dublin meetings in my way,
and the Lord`'s power mightily accompanied his testimony.
George Rooke went with me from Dublin to the north, and in two days we came to Lurgan.

Next day we came to the Quarterly Meeting near Ballinderry,
which continued part of three days, for the worship of God and church affairs.
When the service of the meeting was over, we went to Lurgan meeting,
and then to Ballyhagan, and so to the meeting beyond Charlemount and Toberhead,
near Salter`'s town, where many Friends met us and many other people came,
and a heavenly meeting it was.
Then we went to Grange, Colerain, and to Dunclaudy meeting;
in all which meetings with Friends,
the mighty power of the Lord did accompany us in his word and testimony,
to the comfort and confirmation of faithful Friends,
and placing of judgment on the unfaithful.
Having so far gone through Friends`' meetings,
we entered the mountains in the county of Londonderry,
and had a meeting at Dungiven on a first-day, to which came many people,
several of whom were persons of account;
and all seemed to be well satisfied with what was declared
in the authority of the Lord`'s spirit and power,
which reached his witness in their hearts.

Leaving Londonderry about two miles on the right hand, we came to Raphe,
in the county of Dunnegal, the bishop`'s place, where we lodged at an inn,
and endeavoured to get a meeting, but none durst let us have a house to meet in,
for fear of the bishop, though several would fain have had a meeting to hear us.
The next morning we appointed a meeting in the market-place, to begin at the ninth hour,
and went accordingly, where several came;
and while my fellow-labourer was declaring truth to the people,
two priests came with a constable, who laid hands on him,
saying he was the king`'s prisoner, and must go with him.
The priest brawled and raged; then I stood up by the market-cross,
and desired them to be civil and quiet, and hear what we had to say;
then if any magistrate had anything to question us of, we would go to him;
but the priest raged, and was so full of wrath that he trembled:
They would know what we were?
Whence we came?
and why we came there?
I asked if they were magistrates?
They said no.
Then I told them we were the king`'s subjects,
and inhabiters in the nation as well as they; and told the priest that trembled,
he was full of wrath, and not worthy of speaking to, unless he would discourse soberly;
but for the people`'s sake, and for their information,
who had heard various reports concerning us and our principles,
I would give them an account, both what we were, whence we came, why we came there,
and what faith and principles we held.
So I gave an account of these things until I was clear,
which the priests could not endure, but went away;
for the authority of truth was over them.
We kept the meeting until we were clear in our spirits, and then went to our lodging;
where, having a large room, and an entry adjoining,
I told our landlady we intended to have a meeting, and she gave consent.
We gave notice to have it at the fifth hour that evening, and a full, powerful,
heavenly meeting we had, many people of account being there,
and the testimony of the word of life went over them all.

The next day we had a meeting two miles from thence, to which several came,
and desired to have another meeting; but we could not stay then,
having before appointed a meeting at Litherkenny,
to begin at the first hour that afternoon, where some convinced people,
scattered in that country, met us, they having notice of our coming;
and we had a good open meeting in the under-sheriff`'s barn,
who kept the chief inn in that town.
We lodged there that night, and next morning it was with me to have another meeting,
which accordingly we had, and it was a comfortable confirming time.

We advised those few convinced people in that quarter,
to meet together at Hugh Hamilton`'s house, to wait on the Lord; which they assented to.
Being clear of our service in those parts, William Whiteside,
Jacob Marshal and Bartholomew Garnet, who had been with us at many meetings,
and helpful to us in that rough country, returned home; but I with my companions,
George Rooke, Abel Strettell, Richard Guy and Henry Ridgway,
took our journey towards Connaught,
and in a little more than two days`' travel came to Sligo,
upon a seventh-day of the week.
The high-sheriff of the county, and a justice of the peace, living in the town,
we acquainted them, as also the provost of the town,
that we intended to have a meeting there next day; they were very civil,
and granted us the market house to meet in.
There was a great concourse of people,
and the things of God`'s kingdom were largely declared
in the demonstration of the spirit and power of Christ.
The next day we had a meeting at Killoony, six miles from thence;
but the priest of the parish was angry and got a warrant
from a justice of the peace to break up our meeting,
and to set us in the stocks for an hour.
The constable came to execute it, but the Lord`'s power prevented him,
and therein we kept our meeting, though the priest was in the next room:
after the meeting he was moderate.

We went back to Sligo, having appointed another meeting there,
to be on the day following, a merchant in the town having a large empty house,
was so kind and friendly as to let us meet therein;
where we had an heavenly glorious meeting,
for Christ`'s testimony sunk into many of their spirits.
There were several eminent people at it, one justice of the peace,
and two justices`' wives; and some came to us after the meeting,
and expressed their satisfaction.
When the meeting was over, we rode to Killoony, and lodged,
the next day being very stormy we came to Carrickdrumroosk,
and at the inn where we lodged, there being a good convenient room for a meeting,
I asked the woman of the house if we might have a meeting there that evening?
She gave liberty, and notice was given for a meeting to begin at the fifth hour,
many came to it, and it was a powerful opening meeting,
the people seemed to be well satisfied, and worthy of the opportunity.

The next day we travelled hard to get to Langford in time to get a meeting there;
but we found the people`'s hearts shut up, therefore had none;
but we lodged there that night, and then came to the Moat to our Province Meeting,
the 23rd day of the seventh month, 1699.
Here we met with many Friends, brethren and elders,
engaged in the service of visiting Friends in the province;
and I being one appointed by the meeting to join in it, we concluded to meet in Dublin,
the 10th day of the following eighth month.
I returned home with Friends, having had my health and strength very well,
to perform my service for the Lord in the foregoing journey;
and the Lord`'s blessed power was with us, and went over all;
everlasting praise to his great and glorious name.
Amen.

According to agreement I went to Dublin, to join in the service of visiting Friends.
As I went, my horse threw me, and I was sorely bruised, but John Pim and my son-in-law,
William Fayle, being with me, helped me up, and stayed me with their hands,
until I recovered strength to sit on horseback.
I rode in great pain to Dublin,
yet joined with the Friends appointed for the service aforesaid,
where we made full inquiry of men and women Friends,
and such in general as frequented our religious meetings,
how they walked in the truth in their places and stations, according to Gospel order,
that their lights might shine before men in a good and righteous conversation,
to the glory of God, who had called and gathered us to be a people.
We had several meetings on this account in that city,
and spent three days in the service to good purpose,
the Lord`'s power and heavenly presence being with us, which crowned our labours,
and made them acceptable.

When clear, we went from thence in the peace and comfort of the Lord`'s good spirit,
and came to Wicklow twenty-four miles.
I rode in great pain from the hurt I got by the fall off my horse,
yet the Lord`'s goodness helped me through.
We had three meetings with Friends in that county, and made the same inquiry as at Dublin.
Then we went to the county of Wexford, and had two meetings with Friends;
and to the county of Catherlough,
and had two meetings with Friends upon the same occasion;
in all which meetings we had good satisfaction in
our labours of love for the honour of God,
and good of one another.
Our service being over in this visit, we returned home,
and the week following the Quarterly Province Meeting
for Leinster being appointed at Catherlough,
I rode thither, where was a very great appearance of Friends from several parts,
and a great concourse of other people.
The meeting held part of three days for the worship of God and church affairs;
it was a powerful heavenly meeting, the Lord`'s power being over all,
and his witness reached in many hearts, to their great satisfaction and comfort.

Here we made report to the men`'s meeting of our service in the visit before-mentioned,
which seemed to be satisfactory.
After this meeting I returned home, and kept to our usual meetings;
also visited Friends at Mountrath, and went to the burial of Elizabeth Smith,
near Edenderry, having good service at the graveyard in the testimony of truth,
many Friends and others being there.
I tarried the meeting of Friends at Edenderry, and then came to Ballynolert,
and stayed one meeting there;
so with Robert Hoope and John Barcroft to our meeting at Mountmellick,
and some time after went to the Moat, where we had several meetings,
and the Lord`'s power and goodness was with us, in which we were well refreshed together.
I returned home, and kept to our meetings as they came in course,
until the latter end of the second month, 1700.
