== Section XXIV.

[.chapter-synopsis]
* In 1703, he goes over to the Yearly Meeting at London and Bristol, visiting many counties in England
* Is at the Quarterly Meetings at Lincoln and York
* After his return visits Friends in the province of Munster

Soon after my journey to the north, our Provincial Quarterly Meeting was at Mountmellick,
which held part of three days,
and the Lord`'s heavenly presence was with us in his service, to our great comfort.
In the week following was our National Half-year`'s Meeting at Dublin, as usual,
where the Lord`'s power and presence accompanied us in a glorious manner;
a blessed comfortable and serviceable meeting it was,
and church affairs were managed in peace and concord.
After the meeting was over, which held most of four days, I returned home,
and continued keeping to meetings thereaway,
not being able to travel much in cold winter, by reason of old age.

The Quarterly Meeting for Leinster province being at Castledermot, I went thither;
it held part of three days, and was a comfortable meeting,
both in the worship of God and for discipline,
which was closely managed in sweet unity and concord.
I also went to our next meeting for Leinster province at Catherlough,
which held most of two days in worship and discipline to good satisfaction.
Some Friends having been appointed by the National Half-year`'s
Meeting at Dublin in the last ninth month,
to be at the Yearly Meeting in London in 1703, and I being one of that number,
we concluded to be at Dublin the 26th day of the first month,
in order to take shipping for England.
Having an intention of visiting several other meetings
of Friends in divers parts of England,
and our Monthly Meeting having unity with my concern,
gave me their certificate as a member thereof, as is usual in such cases.

On the 25th day of the first month, 1703, I set forward,
parting with my wife in tender love and resignation to the will of God; went to Dublin,
and there met with some of the Friends appointed to go with me for England.
We stayed two meetings in Dublin, and took shipping on the 1st day of the second month,
viz. George Rooke, John Watson, Thomas Pearce, John Hoope and myself;
many Friends accompanying us to the water-side,
where we had a sweet comfortable meeting in the overflowings of the love of God,
which sealed to us that his goodness would go with us.
We shipped in the packet boat bound to Nesson,
and came to anchor in Chester Water next day, and George Rooke and I went to Liverpool,
next day to Penketh, and stayed a meeting there, which was large,
it being on a first-day of the week.
Here the rest of our company came to us, and we went to Franley in Cheshire,
to a Monthly Meeting of Friends, and the next day to Morley Monthly Meeting,
having good service for the Lord in these meetings, and Friends were comforted.
At Newtown Friends desired to have a meeting with us before we left that county,
which we accordingly had to good satisfaction and comfort in the Lord,
and one in another.
Thomas Pearce and John Hoope rode to Nantwich, to appoint a meeting; to which we went,
and people came in, so that we wanted room, it being on a first-day of the week.

From thence we went to Wolverhampton, Sturbridge, Bewdley, Droitwich, and Worcester,
having a meeting at each place,
and stayed at Worcester until first-day and had two meetings more, which were large,
and Friends were comforted in the Lord, whose presence was with us in a plentiful manner.
The next day we went to Tewksbury, and so to Gloucester, and Nailsworth,
and were with Friends at their meeting, in each place.
Here we met with Joseph Pike come from Cork and intending to go to Bristol.
We went together and were at Friends`' meeting in Bristol,
and tarried in that city five days, being the time of their Yearly Meeting,
and a very great gathering of Friends from divers parts.
We were at several heavenly meetings, and had good service for the Lord and his people,
his power being mightily manifested with us in his work.

When the Yearly Meeting was over,
we took leave and parted in the melting power and tender love of God.
We left Bristol the 29th day of the second month, viz. George Rooke, Thomas Pearce,
John Hoope and I, and came to Tidbury, where we had a meeting; then to Sudbury,
and Cirencester, and had two meetings there, being on a first-day of the week;
then to Carlow, and had a comfortable meeting with Friends.
From thence to Abington, and had a meeting;
and on the next day were at Friends`' meeting at Reading,
where we stayed the first-day following, having two meetings,
which were of service and comfort to true-hearted Friends, and then came to Windsor,
and had a meeting with Friends.

On the 13th day of the third month, 1703, we came to London to the Yearly Meeting,
many Friends from most counties were there,
and we were at many serviceable meetings for the worship
of God and truth`'s affairs relating to Gospel order;
and the hand of the Lord was with us, to direct in matters of church discipline.
When the Yearly Meeting was over, I stayed in London, in truth`'s service,
until the 27th day of the third month,
then took leave of Friends in the tender love of God,
and went in company with Isaac Alexander and Thomas Pearce to Hertford;
several brethren of London accompanying us on our way;
the next day we had a full meeting at Hertford with Friends and others.

The day following we went to Ives, and on the first-day of the week,
had a large meeting at Friends`' meetinghouse,
where the doctrine of Christ`'s kingdom was powerfully preached,
Friends comforted and well refreshed.
The next day we went to Stamford in Lincolnshire, and were at Friends`' meeting there;
and on the day following to King`'s-clift in Northamptonshire,
and next day back to Stamford, and had another meeting; the day following to Deepin,
where we had a large powerful meeting; and from thence to Bourn,
and had a meeting which was large, many Friends came thither from other meetings,
it being on first-day.

Our next meeting was at Willoughby, at Samuel Everet`'s house, and then went to Lincoln,
to the Quarterly Meeting, which held part of two days.
When the service of that meeting was over, we went to Gainsborough,
and next day had a meeting there; then to a large meeting at Brigg,
it being first-day of the week; and so to Epworth in the Isle of Exham,
and had a meeting with Friends.

After this we went to Thorn, and to Selby, and had a meeting there;
the day following to York, to their county Quarterly Meeting,
where was a great appearance of Friends, and our service well accepted.
When this meeting was over, Isaac Alexander,
my fellow-labourer in the Gospel of Christ from London hither, went homewards,
and we parted in the love of Christ, in which we travelled together.
Thomas Pearce and I went to Weatherby, and that day had a meeting there with Friends;
then to Leeds; and next day to Halifax, accompanied by Aaron Atkinson, Joseph Baynes,
and some other Friends; and on the day following, being the first-day of the week,
we had a full meeting there.

The next day, Thomas Pearce and I took our journey towards Nesson,
to look for shipping for Ireland; and not finding conveniency there, went to Holyhead,
where we shipped our horses in the packet boat, and that evening set sail,
having a rough night at sea,
but through the Lord`'s mercy came well into Dublin harbour the next morning,
being first-day of the week: but did not get ashore with our horses until near night.
I was weary and sore with hard travel and labour, and rested at Dublin one day,
then went homeward, and on the 30th of the fourth month, 1703, came to my own house,
where through the Lord`'s mercies I found things well, blessed be his name!
This journey was above six hundred miles, besides crossing the sea.

Soon after I came home, our Quarterly Meeting was at Castledermot, to which I went,
and there was a great collection of Friends from divers parts; we had good service,
a concern being upon many for truth`'s prosperity and good order in the church of Christ.
This meeting held part of three days; when it was over r went home,
and kept to meetings as they fell in course.
Our next Province Meeting was at Athy, to which also I went in company of some Friends.

After this I took a journey to visit Friends in the province of Munster,
with George Rooke, my companion and fellow-labourer in the Gospel;
and having some meetings in our way we came to Cork, and were at their Province Meeting,
where were many Friends.
Abiding there some days, we had several good meetings,
in which Friends were well refreshed in the Lord; and we parted in the love of God.
We then took our journey to Charlevil, where we had a meeting;
and next day we rode to Limerick, and had several meetings there with Friends;
from thence we went to Birr, and so to my house.

Our Province Meeting for Leinster being that week at Mountmellick,
I was there with many Friends from other parts, and some from England.
About this time the Parliament sat at Dublin,
and the bishops and priests having drawn up the heads
of a bill for the more easy recovery of tithes,
etc., they laboured with both houses, lords and commons,
to get the bill passed into an act, which, if granted,
was likely to prove ruinous to Friends.
But through the Lord`'s mercy and care over us,
who gave us favour in the hearts of our superiors,
upon diligent application of Friends to the parliament,
and showing our reasons against passing the said bill, they,
in tenderness to us and others whom it might affect, laid it aside.

I was now unable to ride, by occasion of a fall, but some time after, being recovered,
I went to our Province Meeting at Castledermot,
where the Lord`'s good presence was with us,
and the affairs of the church were closely managed
in the wisdom and authority of the blessed truth,
to the great comfort of concerned Friends and brethren.
There were two Friends from England with us,
and the meeting held part of three days in the worship
of God and discipline of the church.
When it was over I returned to my own dwelling, and cold weather coming on,
together with old age, my decaying body would not permit me to travel long journeys:
so I kept to meetings near home as they fell in course.
