== Testimonies Concerning William Edmundson.

=== A Testimony of the Provincial Quarterly Meeting for Ulster, held in Lurgan the 5th of the Seventh month, 1713, concerning our ancient and worthy Friend, William Edmundson, deceased.

There seems to be a duty on us to cast in a mite into the treasury,
by way of testimony and commemoration of the many laborious and eminent
services of this our dear Friend William Edmundson among us,
for the honour of the great Lord of the harvest,
in which he was a faithful and valiant labourer,
and an instrument in the Lord`'s hand to the convincing and gathering many to the Lord,
both by doctrine and discipline, in which he was unwearied, undaunted,
and often eminently attended with power from on high, which gave life and authority,
impressing his testimony upon the minds of Friends;
and many have often been affected and comforted therewith.

His services and visits in our northern parts,
during the continuation of ability of body, were frequent and also edifying.
His chief concern and labour was,
that Friends might keep faithful to the testimony of truth
which they had received and walk in the same;
and a great care and concern was often upon him, exhorting Friends to beware,
and have a care of the great concerns of the world
making too much impression upon their minds,
which should be after the Lord.

He often reminded Friends of the apostle John`'s advice, "`Love not the world,
neither the things that are in the world;`" and also was very often concerned
to mention most of the sixth chapter of the first to Timothy,
for confirmation of the doctrine he had to deliver,
which was agreeable to the holy sayings and practices
of our blessed Saviour and his apostles,
and faithful followers, who have laid down their heads in peace with him.
As it is the incumbent duty of all mankind to glorify God,
being the end of their creation; so it is apparent,
that the accomplishment thereof consists in chiefly
minding things pertaining to the kingdom of Christ,
which was the chief end and aim of this our dear Friend through many countries,
as well in America as Europe.
We have reason to believe that he had great love to us in this province,
being the first part in this nation in which he laboured after his convincement,
and was instrumental in settling several meetings;
and the first meeting of Friends in this nation, some of us heard him say, was in Lurgan.

For a more particular account of his services we refer to his journal;
for which reason we think it not expedient to mention
the particulars of his worthy labours in this place,
but shall speak something further of his qualifications.
He was a man gifted for doctrine, and above many for discipline;
a reprover of evil-doers, and an encourager of those who did well, yet with great care,
so that none might be lifted up thereby.
He was gifted with a spirit of discerning,
and readily saw the danger some were in by falling from truth;
and being sound in the faith, valiant to contend for it,
and quick in apprehending those things that appeared
to the breach of unity and fellowship in the churches,
he timely laboured to prevent separation and controversies,
and so was an instrument of keeping the unity of the spirit in the bond of peace,
in points of faith and principle, as the same are testified to in the holy Scriptures.
He was a confirmer of the doubtful,
and a sympathizer with the mournful--endued with Christian as well as human courage,
like a prince in Israel, so that he feared not to encounter with those who seemed mighty,
especially when the testimony of truth was violated by them.
And notwithstanding his great courage as a man,
yet when it fell to his lot to suffer by imprisonment
or otherwise for his Christian testimony,
he was clothed with a lamb-like and meek spirit.
He was an eminent apostle and able minister of the Gospel of life and salvation,
having an extraordinary gift in opening and applying the
typical part of the law to the substance in the Gospel;
a faithful elder, whose lamp shined brightly,
and therefore was by us esteemed to be worthy of double honour;
and although those who loved undue liberty, might account him as a burdensome stone,
yet he passed through many exercises on their account,
which the Lord grant they may lay to heart before the day of their visitation be over.

Much more might be said on his behalf, on account of his faithfulness, watchfulness,
labours, diligence and care in the service of God and churches of Christ;
but shall conclude,
firmly believing that the Lord has taken him to himself in a good old age,
like a shock of corn in its season, whose memory is sweet to those who yet survive;
and we pray, that it may please the Almighty,
to raise up others to supply his place and service in the churches of Christ.

Signed by order, in behalf of the said meeting, by

Robert Hoope,

Alexander Seaton.

=== The Testimony of Friends of Leinster province, concerning William Edmundson.

We being under a deep sense of the wonderful lovingkindness
of God to mankind in every age and generation,
but especially in that he hath been pleased in this latter age of the world,
after a long, tedious and dark night of apostasy,
to cause the light of his Son Christ Jesus, so clearly and eminently to shine forth,
expelling the thick cloud of darkness that had long
been over the understandings of people,
and causing his everlasting Gospel to be preached again in the purity thereof;
and the true faith, once delivered to the saints, to be again professed and enjoyed;
as partakers of such mercies and privileges,
we are under deep obligations to walk humbly and reverently before the Lord,
and to return unto him praise, glory and honour, who with his dear Son,
our blessed Lord and Saviour Jesus Christ, is worthy thereof forever.

Among the many faithful labourers in the vineyard of the Lord,
our dear and ancient Friend, William Edmundson, deceased, deserves to be remembered,
especially by us of this province,
where for many years the place of his residence hath been;
concerning whose faithfulness and eminent services for God and his people,
and endeavours for the propagation of the blessed truth, a testimony lives in our hearts,
and much might be spoken,
but it is not our intention to attribute anything to the creature,
that belongs to the great Creator, God blessed forever.
Amen.

This our ancient Friend was by the Lord endued with a large and good understanding,
so that in his testimony he was many times wonderfully opened
into the divine mysteries of God`'s heavenly kingdom,
and would speak excellently of Zion, the beauty and glory thereof;
as also of the mysterious workings of Satan.
He was early convinced of God`'s blessed truth,
when deep trials and exercises attended on each hand; but coming into deep humility,
and relying upon the arm of the Lord alone for help and deliverance,
he was thereby preserved and kept pure and steadfast in his love to him,
through all those difficulties and hardships that attended;
so that in the hand of the Lord,
he was made instrumental to convince many of the way of life and salvation,
and bring them into obedience to the precepts of Christ Jesus.
So that by his, with the labours of other faithful servants,
whom the Lord commissioned and sent into this island, in the work of the ministry,
meetings were settled, and many joined with Friends, being weary of the dead,
lifeless profession and outward performances they had been under,
wherein they had found no spiritual comfort or refreshment to their souls.

After meetings were settled in many places,
and the Lord had been pleased to gift and qualify
several in this nation to preach the Gospel,
who were concerned for the promotion of truth and righteousness in the earth,
and that the great work of reformation, which the Lord had begun,
might be carried on and prosper, more than for any worldly concern whatever,
it pleased the Lord to send forth this our ancient Friend into the nation of England,
as also into the islands and English plantations in America, several times,
where he faithfully laboured and had eminent service,
many being convinced of the blessed truth by him, and others confirmed therein.
His concern and labour was fervent,
that all those to whom the Lord had been graciously
pleased to stretch forth a hand of love,
and convince of his blessed truth, might walk in faithful obedience thereunto,
adorning the same by a humble, blameless and self-denying conversation.

The great Lord of the harvest, who had called him to labour in his service,
to whom he gave up in obedience, and was devoted to serve,
gave him a clear sight of the necessity of a diligent care among Friends,
that such as professed the blessed truth,
and walked disorderly and loose in their conversations, should be seasonably dealt with,
and the evil and danger thereof plainly laid before them,
and they in the love of God admonished to amendment of life.
But if such advice and admonition were slighted and rejected,
and those things persisted in that brought scandal and reproach upon the blessed truth,
then for the clearing of truth and its faithful followers,
to testify against those obstinate offenders and their actions,
as such whom we had not unity with; as also,
that a due Christian care might be taken to relieve the necessities of the poor.
And that all Friends concerned in that holy ordinance of marriage, should seek to know,
and duly regard the mind and will of God therein,
more than worldly riches or earthly ends; often zealously exhorting Friends thereto,
as well as to proceed orderly with respect to parents and guardians,
and to observe justice and equity on all accounts.

When it pleased the Lord to concern his faithful servant, George Fox,
to set up men`'s and women`'s meetings, to take care of those things,
our dear friend William Edmundson rejoiced thereat, and gladly closed therewith:
so that Monthly and Provincial,
as also National Half-Yearly Meetings were appointed in this nation,
and have been kept up to this day,
which have been of good service for the ends before mentioned,
many having reaped great benefit and advantage thereby,
and have cause to bless the Lord for the same.

Our said Friend was a diligent attender of such meetings,
as well as those more particularly appointed for
performing Divine worship to Almighty God,
and was greatly concerned, that none might be admitted members thereof,
but such as were of clean and orderly conversations, walking as examples to the flock,
having a concern upon their minds for the promotion
of truth and righteousness in the earth.
He many times had good service in such meetings, by being clearly opened,
in the word of life,
to declare the qualifications necessary to fit members for such meetings and services.
Beginning at those whom the Lord put his spirit upon to assist Moses,
who were men fearing God and hating covetousness;
he would go through the law and prophets, the holy doctrines delivered by Christ,
when in the blessed and prepared body,
as also the discipline and order in the primitive church, before the apostasy entered,
and the glorious promises how it should be in the latter days in the church,
coming up out of the wilderness; which we are now in measure witnesses of.
O! the great dread and fear we ought to be under,
and concern to walk worthy of so great favours and mercies.

As the Lord was pleased to gift him for the ministry,
so that he could speak a word in season to the states and conditions of people,
he was also graciously pleased to pour forth the spirit
of prayer and supplication upon him in an eminent manner;
so that his appearance, when in the performance of that part of Divine worship,
was in such dread and awfulness upon his spirit,
that it had a great reach and impression upon the spirits of Friends,
causing many times great tenderness to come over the meeting--the
hearts of the sensible being greatly comforted and refreshed,
were inwardly filled with joy and divine praises to the Most High,
from whom all our mercies, both spiritual and temporal, do proceed.

He was greatly concerned for peace and unity in the church,
and that those things which tended to break the same might be kept out.
Much might be said concerning him and his faithfulness to God and concern for truth,
and the promotion thereof; as also for the good and benefit of God`'s people,
but shall refer to his own journal,
and other testimonies that may be given concerning him.
So shall conclude with fervent prayer to the Lord, that he will be pleased to raise up,
gift and qualify many more, for carrying on the glorious work of reformation,
that he hath begun, to the praise of his own great name, who is worthy forever.

Given forth at our Province men`'s meeting for Leinster, held at Catherlough,
the 18th of the Second month, 1713.

Signed by order, in behalf of the said meeting, by

John Pim,

Nicholas Gribbell.

=== The Testimony of Munster province Meeting, concerning William Edmundson.

Our dear Friend and elder brother in the Lord, William Edmundson, who is removed from us,
and hath finished his course in a good old age, and no doubt,
is entered into his mansion of rest and peace with the Lord forever,
out of the reach of the wicked, and the troubles which attend this outward life,
as well as the assaults of the enemy of all our happiness; whilst in it,
was one of the Lamb`'s warriors and true followers, and approved himself so,
as well as a good pattern and example to those he left behind him.

Concerning his convincement and receiving the blessed truth,
as also his coming forth in a public testimony, and his great sufferings by imprisonment,
with other hard and cruel usages,
we leave the particulars to his own journal and our brethren,
the elders of the province Meetings of Ulster and Leinster;
in which provinces he had been a dweller ever since his settling in Ireland,
being above fifty years;
knowing that the Friends of those parts are the most capable of being particular therein.
Notwithstanding which,
we think it no less our concern to give this short
testimony with our brethren concerning him,
viz.

That from the first knowledge of him in this province, which some yet remember,
and which was pretty early after truth was preached
by the people called Quakers in this nation,
he came into Munster with a public testimony, visiting Friends;
wherein also he appeared fervently zealous for truth and the promotion of it.
Having obtained mercy to be faithful, the Lord rewarded his faithfulness,
by increasing his gift in a large measure, whereby he received power,
and became fitted to be an able minister of the Gospel,
and an instrument in the hand of the Lord for turning many to righteousness.
Many and often were his visits in the Lord`'s work,
not only through this province and nation of Ireland, but also in England;
besides his great labours and hard travels beyond seas,
in several voyages to the American churches,
in which he had very great service for the Lord, not only in the work of the ministry,
but also by encountering truth`'s adversaries, priests and people in public assemblies,
and other times concerned against bad, loose and libertine people in divers places,
who made a profession of truth, but not dwelling under the cross and yoke of Christ,
were as the unsavoury salt to the people of the world,
and a grief and burden to faithful Friends.
In these services the Lord`'s power eminently attended him,
making him as a wall of brass, to the confuting of truth`'s adversaries,
as well as a help in time of need, for restoring and helping others.
Indeed, the Lord had qualified him in both respects,
and had endued him with a very large understanding
in the things appertaining to his kingdom.

He was sound in doctrine and in judgment; plain in preaching, and free from affectation.
In apparel and gesture, grave; in his deportment, manly;
of few words till a just occasion offered, and very exemplary in life and conversation.
Much might be truly said of this man of God, which we omit for brevity`'s sake,
and because we believe others will be more large; but in a word, may say,
he was freely given up and devoted to the service of the Lord,
and great was his care and concern for the whole flock of God in general,
that they might grow in his truth;
and in particular he was made a blessing in the hand of the Lord to this nation:
a man of a thousand for promoting virtue in the many branches thereof,
as well as a sharp instrument for threshing and cutting
down that which was evil and hurtful in the churches.

The last visit he made into this province, was in the year 1711,
being then in much weakness of body, yet fervent in spirit,
and his ministry as lively and acceptable as ever;
and so took his leave of Friends in Munster in more
than ordinary tenderness and brokenness of spirit;
after which, he visited us no more, but grew weaker and more feeble till his dissolution,
which was in the year 1712.

May the great Lord of the harvest raise up more such labourers in his vineyard,
is the desire of our souls.

Signed by order, in behalf of the said meeting, by

Thomas Wight.

Joseph Pike.

Waterford, the 2nd of the Ninth month, 1713.

=== The Testimony of Friends of Mountmellick Monthly Meeting; concerning our dear and ancient friend William Edmundson, whom the Lord hath been pleased to remove from us by death; and though it he our loss, we believe it is his great gain.

He was early called forth to labour in the Lord`'s vineyard,
and was made instrumental in the Lord`'s hand for the good of many,
and had a great share in bearing the burden in the heat of the day,
which he cheerfully underwent,
and was endued with valour and courage fitted for the work it pleased God to call him to.
In the times of the sufferings of Friends in this nation,
he had a deep share both in body and goods; and when he was at liberty,
he was very serviceable to Friends, in laying their sufferings before the rulers,
for he was enabled to stand before them, and had good success,
the Lord helping him in his service and labour of love,
and Friends`' liberty was obtained, which was gladness of heart to him,
and comfort to them.

He dearly loved truth and the prosperity thereof before anything in this world.
For this was his usual practice, when the Lord had laid any service before him to do,
he readily answered, preferring it before his own outward affairs;
and in the will of God,
he undertook long and perilous travels several times into America,
as may appear by his journal,
spending himself and his substance for the Gospel`'s sake and the good of souls.
And for the promotion of truth, he gladly joined with that eminent servant of the Lord,
George Fox, and others in this nation, about settling men`'s and women`'s meetings,
and when settled he laboured in them, and managed with all his understanding.
He was also concerned in settling other particular
meetings for performing worship to Almighty God;
and where Friends thought themselves too weak to keep meetings,
he often would go and visit them, and if there was anything that appeared dubious,
he was very helpful by way of advice, as the matter required.
He was ready and willing to serve the Lord, his truth and people,
both at home and abroad, with that ability and substance that God had given him.
For notwithstanding the charge he was at by his frequent travels,
yet he was very exemplary and open in collections for the poor,
and contributing towards building of meetinghouses,
and was very open and free in his own house, entertaining many Friends.

Although he was sharp in his testimony against the transgressing nature,
yet when he was sensible that any were dejected,
or cast down in a deep sense of their own unworthiness, he was very tender towards such,
and willing to reach forth a hand to help them,
both by comfortable advice and fervent prayers to Almighty God for their strength.
The care of the churches was much upon him;
he was also deeply sensible of the common calamity that was coming upon this nation,
which he prophetically spoke of in his testimony through most parts thereof,
several years before it came to pass, with a word of encouragement to Friends,
that if they were of that number that sighed and mourned for the
abominations that were committed by the inhabitants of the land,
the Lord would set a mark upon such, and would spare them.
For that the Lord had determined to dung the earth with the carcasses of men;
and many yet living are witnesses of the fulfilling thereof in some measure.
And as it drew nearer, O! how earnestly was he concerned,
calling to Friends for something that might be as an offering to God,
both for the nation and the preservation of his people;
and did join with Friends in pouring forth prayers with tears to God on this account,
which we believe the Lord graciously heard and answered in preserving their lives.

He was very helpful and strengthening to Friends in those times of great calamity;
he was also concerned in addressing the government and chiefest
men in authority on behalf of Friends and the English inhabitants,
and they commonly would hear him,
and often granted relief He was careful in advising Friends,
that they should not touch with any goods, where property was dubious, in those times;
and when the war was over, and Friends began to settle in the country, his care was,
that Friends might settle near together,
and also that they might keep within the bounds of truth and moderation,
in all their trading and dealing.
He laboured,
that Friends might be preserved out of the vain fashions and customs of the world,
and was for many years under a deep exercise,
that they might not take an undue liberty in exceeding Christ`'s precept of yea and nay,
instead of an oath.
And a weighty concern came upon his spirit,
that all that were concerned in the ordinance of marriage,
might seek the Lord in their undertakings, that worldly ends might not be the object.

He was valiant in his day for the truth, having a word in due season,
which was precious to many;
often concerned in exhorting Friends to do their day`'s work in their day.
He was a man whose heart was inditing good matter, and as a good householder,
brought forth things new and old;
often advising Friends when they offered anything in meetings,
whether in doctrine or discipline,
that they should wait to feel and offer in a living sense.
He had many large openings into the mysteries of Christ`'s kingdom,
often concluding meetings in prayer to the comfort of many.

He lived to old age, and continued livingly zealous for truth;
and though well known in many parts,
yet for the good order`'s sake established among Friends, even in old age,
he requested a certificate of the Monthly Meeting to which he belonged,
to signify Friends`' unity with him when he travelled abroad, to England or other places,
in the work of the Gospel, from time to time.
We might say much more as to his service for truth among Friends,
and of our loss of him on that account; and though he be taken away from us,
his memory lives and remains with us.

Signed by order, in behalf of the said meeting, by

Tobias Pledwell,

John Barcroft.

Mountmellick, the 1st of the First month, 1713.

=== The Testimony of George Rooke, concerning William Edmundson.

A testimony lives in my heart to give to the memory of my true and worthy friend,
William Edmundson.
He was a man with whom I have had some acquaintance above thirty years,
but we were more intimately and nearly acquainted about fifteen years last past,
it having been my lot to be often with him in the service of the Gospel,
both in England and Ireland; sometimes among Friends,
and sometimes in places where none were who bore the name of Quakers.
In all places where we travelled,
his service for God was great to the stopping of the mouths of gainsayers,
and convincing many of the way of truth,
directing and turning people`'s minds from darkness to light,
and from the power of Satan to God; so that many became the seals of his ministry,
which he delivered in great plainness; not in words which man`'s wisdom teacheth,
but in demonstration of the spirit and of power.
In his travels he was very careful not to make the Gospel chargeable;
and had a great zeal against the hireling teachers,
who sought for their gain from their quarter,
and looked after the fleece more than the flock: and for his testimony against such,
he often went through great sufferings both in body and goods,
as the book of sufferings and his following journal show.

Of his travels in America I shall not say much,
leaving it to them that were more acquainted with his service there,
and his own account thereof in the ensuing pages; though I have heard him say,
that he went through great exercises among them,
both in body and spirit--there arising many vain and unruly talkers among them,
who gave great trouble to the churches, and it fell to his lot often to deal with such.
He was a man fitted for such service beyond any other that ever I was acquainted with;
and great was his care to have such made manifest, and a stop put to them,
that they might proceed no further, wherever he met with them;
but especially that such might be kept out of men`'s meetings:
for he was careful that the authority of truth in
men`'s and women`'s meetings might be kept up,
where the Lord`'s business was managed,
that the members thereof might be faithful men and faithful women,
fearing God and hating covetousness,
that so true judgment and justice might be maintained in all these meetings,
without respect of persons; and judgment placed on all unruly and disorderly persons,
that God`'s house might be kept clean, which holiness becomes forever.

He was not one who sought after popularity, but was rather shy,
not intimate with any of whom he had not a trial and true knowledge,
nor willing to lay hands suddenly on any; but of those he had found faithful,
he was a great encourager in the Lord`'s service.
I have often heard him say, it was great satisfaction to him,
to see Friends come up in the service the Lord had fitted them for;
and great was his concern to stir up those the Lord
had gifted to answer their respective services,
by doing their day`'s work in their day,
while ability of body and understanding was continued.
He was an excellent pattern to us all,
in that he spared not himself while his abilities were continued to him,
but even to old age did perform service and travels beyond the ordinary course of nature,
in which he would often say, the Lord was his song and his strength,
who had carried him through many and various exercises and perils of divers sorts.
The greatest trials he met with, were from false brethren,
who opposed the good order of truth, which the Lord has established among us,
whose oppositions, both private and more public, he like a rock, immovably withstood,
and as a fixed star in the firmament of God`'s power did remain,
holding his integrity to the last.

He was one that truly sympathized with his suffering brethren and sisters,
not sparing himself to obtain their relief and enlargement,
when closely confined in prison for their testimony against the hireling teachers,
and the great oppression of tithes, by applying himself to the persons concerned,
and sometimes to the chief governors.
He was a man of an undaunted spirit, grave, meek,
free from affectation in speech and carriage, and therefore fit to stand before princes;
and in such services he was often very successful,
the Lord opening a way and prospering his endeavours.

The gain of all he was ready to consecrate to the Lord,
and not to any abilities of his own, whether natural or acquired,
having a large share of the former, though he had not much of the latter;
being a man of no great learning as to the outward, yet had the tongue of the learned,
so as to speak a word in season to the conditions and capacities of most;
for he was sound and profound in the mysteries of life and salvation.

This eminent elder and overseer in the house of God, was one of,
if not the first instrument in the hand of God, in this generation,
to publish his everlasting truth through this benighted island,
and direct the inhabitants thereof to the inshining light of Jesus Christ,
the glorious Sun of righteousness.
In the discharge of his service in the ministry, he persevered with such constancy,
faith and fidelity, that it pleased his great Lord to bestow on him,
as an additional favour,
a large understanding in the right ground of government and discipline in the church,
in which he earnestly laboured for universal love, unity and good order,
through all the churches of Christ, preferring the honour of God before all things else.
Many times things would open in him to admiration,
showing to rich men and the eager getters of this world,
the danger they were in of hurting themselves, by hindering their growth in the truth.
Nay, I cannot set forth the service he had among us; but this I am sure of,
the churches of this nation will have a great loss of him;
for indeed the care of the churches was daily upon him,
and too few there are to stand in the gap against iniquity,
or who will expose themselves as he did, in dealing plainly with every one,
not letting sin pass unreproved, nor faults untold,
sharply reproving obstinate offenders, but mildly admonishing the sensible and penitent.
A man of truth indeed, who sometimes did tell us,
he was glad when he looked back and considered how he had spent his time,
since the day it pleased the Lord to lay his hand upon him,
and call him into the ministry; and by a careful search,
could not find that he was behind with his day`'s work.

When he was taken sick he sent for me,
before my return from the Yearly Meeting at London;
and the next day after I came home I went to see him,
and found him very weak but very sensible,
and he freely imparted his mind to me in several things,
and particularly about the regulation of men`'s and women`'s meetings,
"`of which regulation,`" said he,
"`there is absolute need,`" and he believed some would come
to see the necessity thereof more than they yet had.

I stayed with him about four or five days,
in which time I observed nothing proceed out of his mouth,
save what showed his concern for truth and the good order of it;
and when I went to take leave of him, he said, "`We have had many good meetings together,
I believe we shall meet in heaven;`" and this he spoke very tenderly.
In a few days after he departed this life in a good old age and full of days,
being aged near eighty-five years, and a minister fifty-seven years; and I doubt not,
but he hath obtained a reward of durable riches, a crown of righteousness,
and his memorial is blessed, for he was a father in Israel in his day.

Though he was a man oppressed, afflicted and troubled in his life time,
yet now he is where the voice of the oppressor is no more heard,
but the wicked cease from troubling and the weary are at rest from their labours,
and their works do follow; receiving the reward of peace, and sentence of well done,
faithful and good servant, enter thou into the joy of thy Lord.
May we all so labour as to be counted worthy thereof, with this our aged Friend at last,
is the sincere desire and travel of.

Thy friend, who wisheth the welfare of all men, both here and hereafter.

George Rooke.
