== Section XV.

[.chapter-synopsis]
* In 1695, William Edmundson, with several others, presented to the Legislature the case of Friends
* He visits Munster province, and attends National and Provincial Meetings, in which were given seasonable admonitions against covetousness and, seeking great things of this world

About this time the parliament met at Dublin,
and we understanding that the priests were endeavouring
to get an act to recover tithes in temporal courts,
in such manner as would much prejudice us, I went to Dublin,
where I met with other Friends,
and joined with them in labouring for the ease of Friends,
with many of the members of parliament, both Lords and Commons, as also with judges,
to let them understand how prejudicial such a law
would be to the king`'s subjects in general,
and most of all to us.
They were generally kind and friendly;
and after I had been concerned some time in that service,
and also in meetings for the worship of God, I returned home.

From there I went to the Quarterly Meeting for Leinster at Castledermot,
where the Lord`'s power and presence appeared mightily with us,
both in our meetings for worship, and in men`'s meetings for truth`'s affairs,
relating to discipline in the church.
Having performed that service, I rode again to Dublin;
and after some time spent there in the service of truth,
I went to a meeting at Edenderry, where a marriage was solemnized,
and many Friends and others were present.
An heavenly meeting we had,
and divine things were opened to the understandings of the people.
That night I went with my son-in-law, William Fayle, to his house,
and next day was at Ballynolert meeting, and so returned home.
Shortly after I rode to Birr, in company of some Friends,
to be at the burial of the eldest son of Thomas Winsloe,
which being on the first-day of the week,
many people came to the meeting and also went with the corps to the graveyard.
I had good service for the Lord, and his testimony was over all;
blessed be his name forever,
who gives ability by his power and good spirit to perform every service he requires.

From there I returned home, and about a week after I went to the Moat,
accompanied by John Pim and Joshua Beale, to the burial of Samuel Strangman,
an honest ancient Friend.
We had a large meeting of Friends and others and
good service both at the meeting and burying-place;
the Lord`'s power and the testimony of his blessed truth were exalted,
and all seemed to be satisfied with what was declared.

Soon after was our Province Meeting at Mountmellick for the worship of God and truth`'s
affairs in which the Lord`'s blessed presence was with us to our comfort and satisfaction;
afterwards I went to the National Half-year`'s meeting at Dublin, in the ninth month,
1695, where were many Friends from several parts of the nation,
and the Lord`'s powerful presence was eminently with us,
to our great comfort and encouragement in his service.

Some time after the meeting was over, I returned home, from where,
after a short stay there, I went to Dublin again, in company with another Friend,
where the parliament was then sitting,
and had before them a bill for the recovery of tithes, with triple damages,
from such as did not pay them.
I joined with Friends in addressing the members of parliament,
and drawing up a paper to show what injuries and gross abuses we had received and suffered,
because for conscience sake we could not pay tithes; and how the said bill,
if passed into a law, tended to the ruining of our substance and families;
with other reasons against it.
A copy thereof was ordered first to be given to the lord deputy, Henry Capell,
then to be printed and given to the members of parliament, who readily heard us,
and seemed very courteous, promising to do what they could for us.
I left Dublin in the company of several Friends,
and came to our Quarterly Meeting at Castledermot,
where I met with some exercise by a bitter spirit; but by the Lord`'s power,
patience and wisdom, faithful Friends went over it.

From there I went to the widow Barcroft`'s,
and settled some concerns belonging to the widow and her children;
so returned home accompanied by one Friend.
Our next Province Meeting being at Mountmellick, I stayed until it was over,
and soon after took a journey into Munster, to visit Friends in that Province,
accompanied by Joshua Northall and some others; we went to Waterford, Clonmel,
Knock-Graffan and Youghal, having meetings in those places and good service for the Lord,
his truth and people.

From Youghal we went to Cork, in the company of several Friends of that city,
who came to meet us, stayed in Cork five days, and had several meetings,
and were at their Province Meeting for the worship of God and church affairs,
and had good service for the Lord on several accounts, being well refreshed in the Lord.
From there, accompanied by Friends, both of Cork and Limerick, we rode to Charlevil,
where we had a brave heavenly meeting;
the glorious mysteries of life and salvation were
opened by the spirit and power of Christ.

From there we went to Limerick, and stayed there to three meetings, and so to Birr,
where several Friends from our meeting met us, and we had a weighty meeting there.
I went home to my house in company of Friends, on the 25th day of the twelfth month, 1695.
In this visit we found a godly zealous concern upon several
Friends for promoting the close order of the blessed truth,
and practising thereof to the honour of God and the good of his people,
of which we were very glad, and our service and labour of love was well accepted,
in a brotherly condescension thereto,
under a sense that the Lord`'s power and goodness were with us,
which made way through all, and gave us satisfaction and comfort in our journey,
blessed be the Lord forever.

Our Quarterly Meeting for the province of Leinster being at hand,
to be held at Castledermot, I went there, accompanied by several Friends,
and we had good service, the Lord`'s presence being with us,
both in our meetings to worship him, and in meetings for church discipline,
in which Friends were closely concerned in the affairs of truth,
and to promote Gospel order in the churches.
This meeting held part of three days, and when the service of it was over,
I came home in the company of many Friends.
The next morning I rode to Maryborough to speak with the lord Chief Justice Pyne,
about some horses taken from some of our Friends.

Soon after this was our Monthly Meeting at Mountmellick, which I attended,
and when the service of it was over, I went to my son-in-law, William Fayle`'s,
and visited thereabout, and from there to a meeting at Edenderry,
then to Isaac Fuller`'s, and so to John Clibborn`'s,
visiting many Friends`' families up and down in that quarter,
giving advice and admonition as occasion required.
I also stayed the first-day meeting at the Moat;
and being pressed in spirit under a sense of some miscarriage,
I cleared my conscience thereof in the testimony of Jesus.
The next morning, being second-day of the week, I rode to my own house.

Soon after was our Province Meeting for Leinster at Castledermot,
which held most of three day`'s for the worship of God and ordering church affairs.
I was there with the elders and brethren,
and the Lord`'s power and presence mightily appeared among us,
to give us wisdom and understanding; also a close concern came upon us,
to search narrowly into matters relating to Friends, and in particular,
to keep out a covetous spirit after the riches and great things of this world,
from among our Society;
knowing that it surfeits and corrupts the mind and
darkens the understanding of people where it prevails.
And through the Lord`'s mercy and goodness,
there appeared a concurrence with the concern in most Friends.
When the service of that meeting was over,
we parted in much satisfaction and comfort of spirit,
I returned in the company of many Friends, and came to my own house;
our Monthly Meeting being the week following, which I also attended.
