== Section XXIII.

In 1702, he goes over to the Yearly Meeting at London.
After his return, he visits Ulster in company with G. R.;
then writes to the bishop of Kildare,
in behalf of Friends`' school-master at Mountmellick.

The time of our National Meeting at Dublin approaching, I went there in the third month,
1702, where was a great appearance of Friends from several parts of the nation.
Accounts were given of truth`'s prosperity,
and Friends`' care of the honour of God and credit of his blessed truth;
and it was concluded,
that some Friends of this nation should go to the Yearly Meeting at London.

I being one appointed by the meeting to go on this concern, with twelve other Friends,
we took shipping from Dublin the 15th day of the third month aforesaid,
being accompanied by many Friends to the water side,
and had a sweet comfortable meeting before parting,
the Lord`'s power and light shining in our hearts, tendering them in his presence,
to our great consolation and confirmation that he owned us in this service.
We had a comfortable easy passage, and enjoyed much of the Lord`'s goodness with us.
After being four nights at sea, we landed at Mossen in Wales, rode to Chester,
and the next day took our journey towards London, where we arrived in five days,
having had one meeting with Friends at Mims by the way, on the first-day of the week.

We were gladly received by many brethren, who greatly rejoiced to see us.
The next morning the Yearly Meeting began,
and there was a great number of Friends and brethren from most counties in the nation.
The meeting continued by adjournment five days,
and many things were discoursed relating to the affairs of truth and Gospel discipline,
particularly that about the affirmation.
The meeting came to this agreement,
that the dissatisfied Friends might have liberty to solicit
the parliament for an act that would be easy to them,
when opportunity offered.
After that meeting was over, having been at some very full meetings,
and preached the doctrine of the kingdom of Christ,
in the demonstration of the spirit and power of God,
to the comfort and satisfaction of many hearts in that city,
being clear we determined to leave London.
Many worthy brethren came to take their leave of us, and we parted in the sweet,
comfortable melting power of the Lord Jesus Christ,
which seals us in the covenant of light and life; then took horse,
several brethren of the city accompanying us some miles.

We came to Chester, and finding an embargo on shipping there, rode on to Holyhead,
having a meeting with Friends at Harding in Wales by the way.
While we were at Holyhead, Thomas Wilson, Joseph Pike and Samuel Randall,
whom we had left behind at London, came up to us,
and about the tenth hour of the evening next day
we set sail in the packet boat for Ireland,
and about the same hour in the evening following, came to anchor in the bay of Dublin.
We all returned together, and landed safe and well;
blessed be the name of the Lord for all his mercies.

I stayed in Dublin to the first-day`'s meeting, and on second-day went homeward.
Our Province Meeting for Leinster being held at the Moat, soon after, I went there;
it held two days, and I returned home, and was taken with a great illness,
occasioned by a violent pain in my head, which kept me at home four or five weeks.
Our Province Meeting being at Castledermot, the 20th day of the seventh month, 1702,
and I being somewhat recovered of my illness, went to it.

Finding myself able to travel, I rode to Dublin, and stayed one meeting there;
then took a journey into the north, accompanied by George Rooke,
and we had many full and precious meetings in various places,
both with Friends and others in several counties,
and the Lord`'s power and wisdom were mightily with us,
to divide the word according to the conditions and states of the people;
also his power healed me of my illness,
so that I was well and strong to answer the Lord`'s service.
Having travelled therein about three hundred miles in about five weeks, I returned home.

Before I took that journey.
Friends`' schoolmaster, who taught their children at Mountmellick,
had been cited several times to the bishop`'s court,
and was likely to be excommunicated for teaching school without the bishop`'s license,
and I having some acquaintance with the bishop, wrote the following letter,
and sent it to him:

May it please the bishop.

This comes as an address in the behalf of a friend of mine,
who teaches our children at Mountmellick, for which, and no other cause of offence,
some persons have presented him in the bishop`'s court,
which may be supposed was done out of prejudice or self-interest;
for he is a quiet harmless Englishman,
capable to instruct children in learning and sobriety.
We understand,
that the officers of the said court are proceeding against him to an excommunication;
and the issue must be a prison if not prevented by you.

Be pleased to hear a few sentences, though in a plain dress, yet true in themselves.
We are Christians,
and hold the faith and doctrine as delivered by our Saviour Christ Jesus and his apostles,
before the apostasy and falling away,
according as it is left on record in holy Scriptures,
and we are conscientious in our duty, as much as in us lies,
to educate and train up our children accordingly.

Experience has taught us, that in sending children to schools where books are used,
filled with idle stories, lying wonders, fopperies, and invented ceremonies,
besides evil conducts, both in words and actions,
being countenanced if not encouraged by too many school-masters and mistresses,
childish nature in youth is prone to listen thereto,
rather than to things that tend to virtue and sobriety,
and being grafted in their minds when young, grow up with them,
and so obstruct better things, that tend to godliness and their salvation.

This is our case plain and simple, which I desire you may in moderation consider,
and let it have your favourable construction; and that we are Protestants,
according to the faith and doctrine in the reformation from Popery and apostasy,
the truth whereof has been tried on many accounts and occasions,
that have happened since the Lord gathered us to be a people,
and the same has turned to the credit of our Protestant profession.
And further, in the late calamities in this nation,
we suffered with the Protestants of the church of England, so termed,
and some of us can say, when there was but a step between us and death;
and the Lord`'s hand of Providence interposed, and restrained cruel vile men.
We have not sought any reparation for our sufferings; but desire,
that as we are Protestants, and have suffered with you, we may now, in time of peace,
live quietly under you in our lawful callings,
to maintain our families according to a good conscience towards God and all men.

And now the Lord being highly provoked by wickedness of all sorts, I say,
if he in justice should again bring his scourge and overflowing tempest over this nation,
we must suffer with the Protestants; for we can flee to no people but to them:
So what you do against us, you do against yourselves,
and pull the house down with your own hands, contracting troubled to yourselves,
by troubling us.
For if you excommunicate us,
and throw us into prison upon the account of our consciences, you must release us again;
or if we die in prison upon the account of a tender conscience,
it will be charged to him or them who are the cause of it;
and I am sure it is the principle of the right church of Old England,
who are not biased with self-interest, not to imprison people upon conscience,
and much less a man for teaching children to read
the holy Scriptures and good books tending to virtue.

I have a secret belief, that you have no delight or inclination,
that people should be cast into prison on such accounts,
which makes me the more willing to let you know the proceedings
of your officers in court against our said friend,
desiring you to read this, and so leave it to your discretion, and the issue to the Lord.

Postscript: A worthy saying of Bishop Boyle, called Primate of Ireland,
against controversy and strife among Christians, is in these words:
"`Heaven is a quiet place, there no quarrels are;
and religion is a holy and peaceable thing, which excites to piety and charity;
but not to strife and debates.`"
And that noble and worthy Prince, King William, in his speech to the parliament, says,
"`That differences of names among Protestants might be taken away,
and no other distinction of religion exist among his subjects,
but Protestants and Papists.`"
