== Journal of the Life of William Edmundson.Section I.

Giving an account of his birth, parentage, trade, marriage, convincement, etc.

I WAS born at Little-Musgrove in Westmoreland, in the north of England, in the year 1627:
my father`'s and mother`'s names were John and Grace Edmundson.
My father was well esteemed among men who were acquainted with him,
and religious in what he knew.
I was the youngest child of six, and my mother died when I was about four years old,
my father also when I was about eight years old.
We were left to the care of an uncle, my mother`'s brother, who treated us poorly;
and my brothers and sisters left him, but I stayed with him several years, being young.
My eldest brother, who was heir to the estate my father left,
when he came to the age of twenty-one years, with my eldest sister`'s husband,
went to law with my uncle about our portions, and other injuries and wrongs,
and they spent much money.

In those times I went through many hardships and exercises of various kinds.
After some time I was bound apprentice in York, to the trade of a carpenter and joiner,
where I lived some years.
In this time the Lord began to work in the hearts of many people in that city,
so that there were great openings in the things of God, both in preachers and hearers.
Then the Lord began to visit me with his judgments, and to set my sins before me:
many times I was under great exercises concerning my salvation,
and also about election and reprobation.
So many things wrought mightily in my mind about religion,
that I was often brought very low in my spirit,
and at public worship in the steeple-house, at times,
the Lord`'s judgments would seize upon me heavily.
One time, in the public worship, the hand of the Lord was so upon me,
that I shed abundance of tears in weeping and bewailing my wretched state;
and the priest and congregation took notice of me,
but none directed me aright to the Physician who could heal my wounded spirit.

About this time I went into the parliament`'s army,
and there continued part of the war between the king and parliament;
and when that was over I went into Scotland under Oliver Cromwell in the year 1650.
The Lord began afresh with me, and many times his heavy judgments would seize upon me,
and bring me low in a consideration of the life I lived in, and what the end would be;
and sometimes his mercies would spring in my heart to my great refreshment,
and cause tears of joy and gladness.
But I knew not the secret hand that was dealing with me,
neither met I with any who informed me,
although in the army we had many high professors of religion.
Sometimes when I had been on service most of the day,
and was lying down in my tent at night,
then would arise in my mind the imminent dangers I had passed that day,
and the narrow escapes my life had, and what would have become of my soul,
if I had fallen while in uncertainty of my future happiness;
with resolutions to turn to the Lord by repentance and amendment of life;
but when action presented, which I was active in at that time,
I got over it again in my vanity.

In the year 1651, the Scotch army marched for England;
we followed and engaged them at Worcester, and overthrew their army.
After the fight I was troubled in mind for my vanity,
for the Lord preserved my life still; but I fled from judgment,
and made merry over God`'s witness in my conscience, which testified against me.
From there we were commanded to the Isle of Man, which was delivered to us,
and in two weeks time returned to England and quartered in Derbyshire,
at Chesterfield and the towns thereabout.
At this time the common discourse of all sorts of people was of the Quakers,
and various reports were of them; the priests everywhere were angry against them,
and the baser sort of people spared not to tell strange stories of them;
but the more I heard of them, the more I loved them,
yet had not the opportunity to speak with any of them.

One market-day at Chesterfield, I was in a tavern with others of my companions,
and two women of the people called Quakers,
spoke of the things of God to the people in the market.
I did not hear of them until they were gone, but the priest of the town,
and several with him, abused them.
When they had done, they came to the tavern,
into the room where I and my companions were, it being a large dining-room,
where the priest boasted of what he had done to the two women,
thinking we would praise him, but I loved to hear of the women,
and hated his behaviour towards them.

A young man, a merchant, then present, who frequented my company,
and would often speak of the people called Quakers,
and say their principles were the truth,
hearing the priest boast of his abusive behaviour to the said two women,
answered and said.
It was a poor victory he had gotten over two poor women;
at which the priest was very angry, and began to storm.
My spirit rose against him; I started up from my seat,
and asked the priest and them with him, if they came to quarrel?
saying, if they did, they should have enough.
The priest answered.
No, not with you sir.
I bid them leave the room, which they presently did; but these things came close to me,
and the more I heard of this people the better I loved them,
and earnest desires sprung afresh in my heart
that the Lord would show me the way of truth.

After some time spent in various exercises, we marched again for Scotland,
at which time I had charge of some men for recruiting other companies then in Scotland.
I marched them with our regiment, and delivered up my charge in Scotland;
then left the army, came back for England, and visited my relations in the north;
from there rode into Derbyshire, and married a young woman,
to whom I was contracted before.
After some time I was about to settle in Derbyshire in the way of shop-keeping,
when my brother, who was a soldier in Ireland, came into England to see his relations,
and highly commending Ireland, persuaded me to go and live there,
which I with my wife concluded to do.
The troop my brother served in quartered near Waterford;
we proposed to ourselves to settle a trade of merchandize in Waterford,
and to live at a place two miles from it, where we could pass and repass in our boat;
promising great matters to ourselves and religion besides.
So with this result, when my brother returned,
I sent with him a little parcel of merchant goods, and not long after, I,
my wife and servant went for Ireland, with a larger quantity of merchant goods.
We came through Westmoreland to take leave of our relations,
and some of them went with us to Whitehaven, where we took shipping,
and landed at Dublin.

All our great promises, however, came to nothing; the Lord,
who had been often striving with me both in mercy and judgment, had other service for me,
which I knew not of and was a stranger to.
At Dublin I expected my brother had made some preparations for us and our trade,
but instead thereof the troop and he with it were marched into the north.
I wrote to him, and gave him an account that we were landed;
in the mean time I was strongly importuned to settle in Dublin,
trading being then very brisk, and houses on easy terms,
it being not long after the plague.
But I was prevented by a secret hand that I did not then know,
which preserved me from the deceitfulness of riches,
which according to all probability I should have been laden with, as with thick clay,
and thereby been hindered from the Lord`'s service, as some others are.

When my brother had received my letter, he came to Dublin,
with horses to take us into the north to Antrim, where their troop was to quarter;
there I took a house, and my brother dwelt with me.
The officers of the troop were very kind, they would have had me ride in the troop,
and receive constant pay, yet might follow my own business and be duty free;
for they would procure an order on their own account,
none being then admitted into troops without the general`'s order.
I refused, and would not accept of their kind offers;
for my inclinations were after religion,
and my conscience began to be awakened by the Lord`'s judgments mixed with mercy,
which preserved me.

I soon sold the goods I brought over, and forthwith went for England to buy more;
and coming into the north of England among my relations,
at the time George Fox and James Nayler were in that country,
James Nayler having a meeting about three miles from where I was,
I went to it with my eldest brother Thomas, and another kinsman,
having an earnest desire to converse with some of that people, retaining a love for,
and believing well of them from the first hearing the report of them;
and I was glad of this opportunity.
We were all three convinced of the Lord`'s blessed truth;
for God`'s witness in our hearts answered to the truth of what was spoken,
and the Lord`'s former dealings with me came fresh into my remembrance.
Then I knew it was the Lord`'s hand that had been striving with me for a long time.
This was in the year 1653.

Then my understanding began to be opened,
and many Scriptures were brought to my remembrance, which I had often read,
yet understood not;
but now being turned to a measure of the Lord`'s spirit manifested in my heart,
which often had reproved me for evil in my ignorance,
I knew it was the truth which led into all truth,
agreeably to the holy Scriptures of the law and prophets, Christ and his apostles,
and I thought all that heard it declared must own it, it was so plain to me.
A few days after I was thus far convinced of the blessed truth,
the Lord`'s power seized upon me through his Spirit,
whereby I was brought under great exercises of mind; yes,
all my parts came under this exercise, for the Lord`'s hand was mighty upon me,
in judgments mixed with mercies; so that my former ways were hedged up.
But I loved the Lord`'s judgments, for I knew I had sinned against him,
and must be purged through judgment.
And though under this exercise of conscience towards God,
yet I did my business in England,
and shipped my goods to be landed at Carrickfergus or Belfast.
