== Chapter III

[.chapter-synopsis]
* Of his first public ministry
* His visit to George Fox in England
* The settling of a meeting in Dublin
* His imprisonment at Armagh, and dispute with a priest and a justice of the county, etc.

Some time after this,
John Tiffin was moved of the Lord to come into Ireland in truth`'s service.
He came to my house, abode a while, and sat with us in our meeting,
sometimes speaking a few words, which were edifying.
Then began a concern to come upon me to travel with him to some places,
although he had but few words, yet very serviceable.
Our going abroad to fairs and places of concourse,
put many to inquire into the Quakers`' principles and religion;
and sometimes we had discourses with professors,
but people in general were very shy and fearful of us, lest they should be deceived;
for the priests persuaded the people against us,
by telling them stories and lies which the priests in England had forged and sent abroad,
too many to mention here, neither is it needful,
being printed in several books with Friends`' answers to them.

At this time but few would lodge us in their houses.
At Belfast, that town of great profession,
there was but one of all the inns and public houses that would lodge any of our Friends,
which was a widow Partridge, who kept a public house, and received us very kindly.
There John Tiffin lodged, often endeavouring to get an entrance for truth in that town,
but they resisted, shutting their ears, doors and hearts against it.

Near this town there dwelt one Laythes, who promised to let us meet in his house,
and the day was appointed; accordingly we came there, that is, John Tiffin,
my brother and I, but when we came, the man was gone from home, as they said;
we supposed on purpose, that we might not meet at his house.
His wife was a proud woman, and would not allow us to meet there.
A little way from that house in the great road, three lanes`' ends met;
there we three sat down and kept our meeting.
People came about us; we were a wonder to them,
and something was spoken to direct their minds to God`'s spirit in their own hearts.
These exercises, though in much weakness and fear, spread the name and fame of truth;
the minds of many honest people began to inquire after it,
and to see that the reports which the priests had told them of us, were false,
which made them more desirous to hear us, and some were added to our meeting at Lurgan,
then kept at my house.

Soon after John Tiffin went for England, but our meeting increased,
and sometimes the Lord`'s power and spirit would move in me,
to speak a few words in meetings; which I did in fear, being under a great concern,
lest a wrong spirit should get entrance,
and deceive me in the likeness of an angel of light;
for I was sensible of my own weakness.
Several gathered to our meeting, and were convinced and received the truth.
So we got meetings in several places, there being a great openness among people.

About this time I had some drawings on my spirit,
to go for England and to see George Fox, whom I had not yet seen.
I went over and met with him at Badgley in Leicestershire,
where there was a great meeting of Friends from several places.
When the meeting ended I went to George Fox, and he took notice of me.
We went into the orchard, and kneeling down he prayed.
The Lord`'s heavenly power and presence were there; and he was tender over me.
I told him where I lived, of several being convinced in Ireland,
of the openness among people in the north of that nation, to hear the truth declared,
and of the lack of ministering Friends in the Gospel there.
He wrote the following epistle to Friends, which he sent with me:

[.embedded-content-document.epistle]
--

Friends, in that which convinced you, wait,
that you may have that removed you are convinced of; and all my dear Friends,
dwell in the life, and love, and power and wisdom of God, in unity one with another,
and with God; and the peace and wisdom of God fill all your hearts,
that nothing may rule in you but the life, which stands in the Lord God.

[.signed-section-signature]
G+++.+++ F.

--

He bid me, when I came to Ireland, go to Edward Burrough and Francis Howgill,
for they were in the south of that kingdom in the service of truth.
So, when I had been at Swarthmore, and some other places in England to visit Friends,
I returned to Ireland, and read the foregoing epistle to Friends in the meeting;
there the power of the Lord seized on us,
whereby we were mightily shaken and broken into tears and weeping.
The priests and professors in the south of Ireland, were so envious against truth,
that they got an order from Henry Cromwell, then lord deputy of Ireland,
to banish Edward Burrough and Francis Howgill out of the nation,
and a guard of soldiers were ordered to conduct them from place to place,
till they were shipped off.
But the guards were loving to them, and allowed them to have meetings where they came;
so that several received the truth, and small meetings were settled in various places,
particularly one in Dublin.

About this time Richard Clayton was moved of the Lord to come for Ireland,
in the service of the Gospel; he came by the Lord`'s directions straight to my house,
as he himself told me; and stayed with us some meetings;
then was moved of the Lord to travel to Colerain and Londonderry;
I also was moved to go with him.
He published the day of the Lord in Colerain in the street, warning all to repent.
We put up papers which we had written, in several places;
one we put on the worship house door; but the professors were highly offended,
and banished us over the water, giving charge that no boat should bring us back.
We travelled the road towards Londonderry,
lodging that night in a cabin in the mountains; and next day came to Londonderry on foot,
and got two meetings there, where several received the truth:
the governor was at one meeting, where he was convinced,
confessing it to be truth that we declared, and while we stayed he was very loving.

Then we travelled to Strabane, Clougher, Omagh, and six miles across to Dungannon;
and to Kilmore in the county of Armagh;
several honest tender-hearted people lived thereabouts, who had a desire to hear Friends.
We came to Margery Atkinson`'s, a tender honest woman, whose house I had been at before:
she was convinced of the truth and received us lovingly.
We had a meeting there, and the tender people thereabouts generally came to it;
most of whom received the truth in the love of it in much tenderness;
for they were waiting for it.
We settled a meeting there, which became large.

Richard Clayton went for England;
and about this time there were two women Friends from London,
Anne Gould and Julian Wastwood, who came to Dublin, and travelled to Londonderry,
having some drawings to that place.
After some service for the Lord there, they travelled to Colerain,
so through the Scotch country to a place called Clough, all on foot in winter time,
wading rivers and dirty miry ways.
Anne Gould being a tender woman, was much spent, and stayed at Clough;
the enemy persuading her, that God had forsaken her,
and that she was there to be destroyed, so that she fell into despair;
but I knew nothing of them.

At this time my brother and I were at a fair in Antrim; being late there,
we proposed to lodge that night at Glenavy, six miles on our way homeward.
Before we got to Glenavy I was under a great exercise of spirit,
and the word of the Lord came unto me,
that my shop was in danger to be robbed that night.
I told my brother of it; so we concluded to travel home,
and went about a mile beyond Glenavy; but my spirit was still under a great exercise,
the word of the Lord moving me to turn back towards Clough.
I was brought under a great exercise between these two motions,
to travel back and my service unknown;
and my shop on the other hand in danger to be robbed,
which brought me into a great strait, for fear of a wrong spirit.
I cried to the Lord in much tenderness of spirit, and his word answered me,
that which drew me back should preserve my shop; so we went back to Glenavy,
and lodged there.
That night I slept little, because of many doubts about the concern:
on the other hand I dared not disobey, for I knew the terrors of God for disobedience.

The next morning my brother went home, but I rode back to Antrim.
Towards evening I came to Clough, and took up my lodging at an inn,
the country being generally inhabited by Scotch people and Presbyterians.
When I came into the house I found Anne Gould in despair, and Julian Wastwood with her,
but when they knew who I was and heard my name, for they had heard of me before,
the poor disconsolate woman revived for joy and gladness, and got up,
for she was in bed overwhelmed under trouble of mind.
I saw then that my service of coming there was for her sake.
When we came to discourse of matters,
I told them how I was brought there by the good hand of God,
led as a horse by the bridle, to the place where they were;
they therefore greatly rejoiced and praised God,
the tender woman was helped over her trouble,
and she saw it was a trial of great temptations she had lain under.

They had a mind to go to Carrickfergus, to my house,
and to Dublin to take shipping for England;
but neither of them would undertake to ride single,
therefore I was forced the next day to carry them behind me,
first one and then the other.
When we came in very foul way, I set them both on horseback,
and waded myself through dirt and mire in my boots,
holding them both on horseback with my hands.
We came to Conyers that night and lodged there, the next day I got them to Carrickfergus,
and there leaving them, rode home and sent my brother and two horses,
to bring them to my house.

When I came home, I inquired about my shop, whether it had been in danger of robbing?
They told me, the night I was under that exercise about it,
the shop window was broken down and fell with such violence on the counter,
that it awakened our people, and the thieves were affrighted and ran away.
So I was confirmed it was the word of the Lord that said,
that which drew me back should preserve my shop,
and I was greatly strengthened in the word of life,
to obey the Lord in what he required of me;
for I was much afraid lest at any time my understanding
should be betrayed by a wrong spirit,
not fearing the loss of goods nor sufferings for truth,
its testimony being more to me than all other things.
When these two women had stayed some time at my house, and visited Friends,
my brother sent them on horseback to Dublin, so they went for England.

At this time I travelled in truth`'s service,
for the Lord had given me a testimony for his truth in meetings and public places,
sometimes at worship houses, where I met with rough usage.
Truth gained ground, many received it and came to meetings,
we having meetings in several places, and some meetings settled for the worship of God.
About this time I was put in prison at Armagh for the testimony of truth,
before the common jail was repaired,
so I was prisoner in a little room in the jailer`'s house.
Though I was weak and contemptible in my own eyes, yet the Lord was with me,
and his power and dread was my strength and refuge.
I was a terror to the jailer and his wife,
for if I came out of my room to where the jailer was, he hung down his head,
not looking me in the face.
His wife would sometimes be tormented and cry out, for my presence was a torment to her,
though I said nothing.

At this time there came a Presbyterian minister out of Scotland,
pretending to visit the churches, and in his company was one Colonel Kerr;
this priest came to the jailer`'s house to lodge, for he kept a public-house.
It was on a seventh-day of the week he came; and I was then fallen sick, and in bed,
and the priest lodged in the next room to me, so that I could hear what they said.
Towards evening many Presbyterians came to visit their minister,
and he read a chapter and expounded it to them, sung a psalm, and prayed;
after which they left him that night.

The next morning early, being the first day of the week,
Colonel Kerr came into the priest`'s room, and asked him,
what was the meaning of the apostle John`'s speaking so much of abiding in Christ?
and how we must abide in Christ?
The priest did not answer him, therefore he was under trouble and dissatisfaction.
At this the Lord moved me to rise, put on my clothes,
and speak to the priest as he went to his worship,
for they passed by the door of my room.
I arose and put on my clothes, the Lord`'s power strengthening me:
many of the chief of the Presbyterians came to accompany
the priest to their place of worship.
I stood in my room door, and as he went by I asked him, if he were a minister of Christ?
He answered, yes.
Then I asked,
what was the reason he did not understand the doctrine of the former ministers of Christ?
But he was smitten, and making me no answer got away.

I laid down again, being sick; the next morning early, Colonel Kerr came to my bedside,
saying, he heard I was in restraint for my conscience, adding,
he was a man of tender conscience and sympathized with my sufferings,
therefore came to see me, desiring to have some discourse with me;
but he heard I was not well;
yet if I would arise he offered to help me on with my clothes.
I told him, I would arise and put on my clothes,
for I felt the Lord`'s power strengthening me.

So he went out of the room;
and this was but an apology to get an opportunity for the priest
and several of their elders and disputants to run me down,
and to glory over truth and Friends.
I got up and dressed myself; and presently the priest, Colonel Kerr,
Colonel Cunningham and a great many of their leading men came into the house,
more than the room would hold.
I was greatly afraid of my own weakness for truth`'s sake;
therefore I prayed to the Lord in secret for his assistance,
and he was pleased to fill me with his spirit, being mouth and wisdom to me;
so that the Lord`'s power, and the testimony of his blessed truth was over them;
the priest was confounded in himself, and being restless,
went out and came in several times.
When the priest had finished,
Colonel Cunningham began with me; he was a justice of the peace and a great disputant.
We discoursed of several things, too tedious to mention the particulars;
but the Lord`'s power foiled him, his mouth was stopped and he sat silent.
Then was my heart and tongue full of the word of life,
to declare the way of truth to them, and they went away quiet;
the Lord`'s power and testimony were over them, everlasting praises to his great name.

In this morning`'s work the Lord healed me of my illness.
Afterwards I was brought before the justices of the county at the sessions,
where Justice Cunningham before-mentioned was chairman.
He had a nimble tongue, but left the matter for which I suffered,
and would dispute about religion, which I would have avoided,
being unwilling to enter thereinto,
knowing my own inability without the assistance of the Lord`'s spirit and power,
but he urged the discourse.
So we went close to it, and he was so pinched with his own argument,
that he perceived the court took notice of it, therefore he grew angry,
threatening me with his authority; but one Justice Powel,
a sober man upon the bench with him, stood up and told him, he did not do fairly with me;
for, said he, if you will dispute of religion, you must come on equal terms,
and lay aside your authority of a justice;
and give liberty to be opposed as well as oppose.
He commended what I had said, the people seemed to be satisfied,
and there was a great appearance of the country at that sessions:
after some more discourse, they set me at liberty,
for they were ashamed of my commitment.
