== Chapter IV

[.chapter-synopsis]
* Of his leaving shop-keeping to take a farm in the county of Cavan
* Friends`' sufferings increased
* He was put in the stocks at Belturbet
* His discourse with the governor, etc.
* A Baptist preacher and Captain Morris both convinced

About this time it came weightily upon me to leave shop-keeping, and take a farm,
to be an example in the testimony against tithes; for as yet that was not broken through,
few, if any, stood in that testimony in this nation.
There was one Colonel Kempston, who was convinced of the truth,
though he did not join with Friends; he had a great deal of land in the county of Cavan,
and other places, and was desirous to have Friends live on his land,
promising he would build a meetinghouse, and do great matters to promote truth.

My brother and I rode to his house in the county of Cavan,
and treated with him about taking several parcels of land for ourselves,
and several other families of Friends who were willing to live near us;
but for some time we could not close a bargain with him, for he was a hard man.
After a while the Lord`'s power filled my heart;
and I was moved in the word of life to tell him, I would take his land,
let him take what he would for it, and make his own terms; at which he was amazed.
Pausing a little, he desired half an hour to consider.
He walked into his orchard, and in a little time returned to us,
and closed a bargain with us for the land,
on such easy rent and terms as we could not have brought him to by arguments;
whereupon several families of Friends came with us and settled on his land.
We kept a meeting for the worship of God twice in the week,
in which our hearts were tender before the Lord, and, in his love,
near and dear one to another.
Truth was much spread, and meetings settled in several places,
and many being convinced and brought to the knowledge of God were added to Friends.
But sufferings increased for not paying tithes, priests`' maintenance,
and towards repairing their worship houses, for not observing their holy days so called,
and such like; they fleeced us in taking our goods, and imprisoned some of us.

In those days the world and the things of it were not near our hearts,
but the love of God, his truth and testimony lived in our hearts;
we were glad of one another`'s company, though sometimes our outward fare was very mean,
and our lodging on straw; we did not mind high things,
but were glad one of another`'s welfare in the Lord, and his love dwelt in us.

I was often abroad in truth`'s service, visiting Friends,
and getting meetings in several places.
I was moved to travel into Leinster province, and went from place to place,
as the Lord`'s good spirit guided me.
I came to Rossenallis, and there met with two families come out of England,
convinced of the truth.
From there I went to Nicholas Starkey`'s near Athlone, and had a meeting on a first-day,
to which several sober people came, and the Lord`'s power and presence were with us.

From there I went to Mullingar, and lodged one night,
where was a trooper that was convinced, who rode with me several miles the next day,
and continued coming to meetings.
I came that night to Finagh, but the innkeepers in the town refused me lodging,
for that they knew I was a Quaker.
It was in winter time and cold weather; upon which I inquired for the constable,
and they showed me his house.
I told him he must provide me a lodging, for I was a traveller,
and had money to pay for what I should have, and had been at the inns,
where they refused me lodging.
He kept an ale-house, and had also refused me, but after much discourse with him,
he told me I must be content with such lodging as he had for me.
I told him to let me have a room with a fire to sit by, and hay for my horse,
and I would be content.
So I alighted, went into the house, and there were troopers drinking,
who soon perceived what I was, and began to scoff and to ask me many questions,
which I answered in my freedom.
But when I thee`'d and thou`'d them in our discourse, they were very angry,
and one of them swore, if I thou`'d him again, he would cleave my head.
In our discourse, when it came in its place I thou`'d him again,
and he starting up in anger drew his sword;
but one of his corporals sitting by him stopped him,
and commanded him to put up his sword, for there should be no cleaving of heads there.
He caused the troopers to go to their quarters,
but stayed with me discoursing until late in the night, and was convinced, being tender,
received the truth, and came to meetings.

About this time we had a meeting at Belturbet,
and the Lord`'s power and presence was with us;
but the provost of the town was an envious man, who came with some rude people,
broke up our meeting and took us to prison, both men and women.
We were all night in a very cold place, the women were mightily pinched with cold,
it being frost and snow.
The next morning he set all the other Friends at liberty,
but he put me in the stocks in the market-place, and people gathered about me,
where I had an opportunity to preach the truth to them, which they heard with soberness,
were tender and reflected much upon the provost for abusing us.

Robert Wardell, being then but a boy,
told the provost he had set a better man than himself in the stocks,
and there was a time when such as he dared not have meddled with me.
Therefore the provost took him, and set him in the stocks by me;
but his father soon heard of it, and threatened the provost with the law;
for he was then master of the store, there being a garrison of soldiers there;
so that Robert Wardell was soon taken out of the stocks, who being convinced,
kept to truth and with Friends, afterwards became a serviceable man for truth,
and a preacher of it.

The people were much dissatisfied with the provost;
so he sent his officer to let me loose, who opened the stocks and bid me take out my leg,
for I might go my way.
I told him, I had been grossly abused, and made a public spectacle to the people,
as though I had done some great offence, but was not convicted of the breach of any law;
so let the provost come himself and take me out, for he put me in.
The provost came and opened the stocks, bidding me take out my leg.
I told him, no, for he had made me a spectacle to the people,
and I knew no law that I had broken; but let him take out my leg that put it in.
Upon which he opened the stocks with one hand, and took my leg out with the other.
His name was Richard West.

At this time Oliver Cromwell had put forth a declaration,
"`That such should be protected in their religion,
as owned God the Creator of all things, and Christ Jesus the Saviour of man,
and the Scriptures,`" and several other things mentioned therein.
So the governor of that garrison, with the officers and chief men in the town,
and abundance of people with them, who filled the courthouse,
would try us by the declaration,
whether we and our religion were under Oliver`'s protection or not;
the provost was there, and I was sent for.
The clerk of the garrison, who was then a Baptist, but afterwards a Friend,
read the declaration, and I was called to answer to the particulars.
I answered them so, that the governor and they with him gave their judgment,
that we were under protection, and our religion was to be protected.

Then I called aloud, that they would bear witness,
how long we had been imprisoned illegally,
and that I sat in the market-place in the stocks wrongfully,
and that the law provided reparation in such cases.
Several of the chief of them offered to be evidence,
if we would take the advantage of the law against the provost.
He was quite dashed and looked very pale.
The governor came from his seat, and took me by the hand, saying,
he was sorry that I and my Friends were so abused;
and did assure me he had no hand in it.
I asked him, who he was?
He said he was the governor of that garrison.
I asked him, where he had been those two days,
that he did not appear with his band of soldiers to appease the uproar;
for I had read in the Scriptures, that at Jerusalem,
when there was an uproar on the like account, the governor came with a band of soldiers,
and rescued Paul from them, and appeased the uproar; and was it not a shame for him,
that a heathen should outdo him who professed to be a Christian?
He was a Baptist, and so were several who were in authority thereabouts.
My spirit was borne up in the power of the Lord, as upon the wings of an eagle that day;
truth`'s testimony was over all their heads,
and my heart was filled with joy and praises to the Lord:
many were convinced and several of them received the truth, and abode in it.

There was one William Parker, a preacher among the Baptists,
who had opposed me strongly at a court a little before this; his wife was a Friend,
convinced in England, and was a prisoner with us: they lived then in the country,
and his wife not coming home, in the morning he came to look for her,
and finding me sitting in the stocks in the cold winter, in the open market-place,
he was smitten to the heart.
After I had done with them all I was at liberty,
and came to Friends with my heart full of joy.
Parker was with Friends; so I asked him,
what he thought of his brethren to allow us to be thus treated,
and they chief in command in that place?
He answered with tears in his eyes, he was ashamed of them,
who had been so long professing and fighting for conscience,
now to allow conscience to be trodden in the dirt.
He went to them no more, but came to our meetings, taking up the cross of Christ:
he became an honest, zealous man for the truth, having a public testimony in meetings,
and died in the true faith of which Jesus is the Author.

There was also one William Morris, an elder among the Baptists in great repute,
captain of a company, justice of the peace, commissioner of the revenues,
chief treasurer in that quarter; also chief governor of three garrisons,
to whom the news of this day`'s work was soon carried;
whereat he was much troubled in mind, and told the messenger, who was a justice of peace,
it was a shame for them to allow us to be so abused, saying,
the time would come that they would be glad to take shelter under our wings.
The rumour soon went among the Baptists, and also to the court at Dublin,
that Captain Morris was turned Quaker:
whereupon he was removed with his company southward.
Not long after he was sent for to Dublin,
to appear before the general and chief officers, many of whom were Baptists.
He was examined about his being turned Quaker, which he did not deny,
but confessed our faith and principles, and at that time was discharged from his command,
because he was a Quaker.
He was a worthy wise man, had a testimony in our meetings, and died in the faith of Jesus.
I was at Dublin at the time when they took his command from him.
He would often say, that I was a great help and strength to him in the truth.

Our meetings increased, and our sufferings also increased; but Friends being innocent,
were careful to keep up truth`'s testimony punctually and faithfully;
so that truth gained ground.
Our landlord, Kempston, would not confirm our leases according to covenant,
but would impose several things on us, which Friends would not submit to:
so that several Friends left his lands,
and removed with their families towards Mountmellick; but some abode there longer,
and kept up a meeting for Divine worship twice in the week.
