== Section V.

Of his hard imprisonment at Cavan in a nasty dungeon.
His speech in public court, release and removal afterwards to Rossenallis.

I WAS then kept close prisoner in Cavan jail for the testimony of truth,
in a nasty dungeon among thieves and robbers, which was very noisome, arched over head.
In the day we had the benefit to look out through an iron grate;
but at night the door was close shut, and then we were as if we had been in an oven.
In the day the prisoners would beg turf, and at night, when the door was close shut,
they would kindle a fire, which filled the dungeon with thick smoke.
There being little air, this annoyed me very much, but they could endure it,
being used to the like in their cabins.

One night the smoke stifled me, and stopped my breath,
so that I fell down and lay on the ground.
The prisoners cried out that I was dead; then the jailer threw open the door in haste,
and when he saw me lying on the ground, he was in a rage, and thought they had killed me,
but when he understood the cause, he carried me into the air.
In a little time I recovered, and he called for a pail of water, and quenched the fire.
After this when he locked the door at nights he was careful to put the fire quite out;
so it wrought for my good, being eased thereby from that noisome smell and smoke,
which had before very much impaired my health, and was so offensive,
that when people came to the grate to see me, they could not endure the smell,
but many times would go away with tears.
Thus the minds of people were moderated, and their hearts tendered towards Friends.

But what added to my trouble, news was brought me of James Nayler`'s miscarriage.
This came very near me, and brought me under great trouble of mind,
so that I said in my heart,
how shall I be able to stand through so many
temptations and trials which attend me daily,
since such a one as he is fallen under temptations?
And I mourned in my spirit.
In the interim the Lord answered me, and said, truth is truth, though all men forsake it.
This strengthened me, and comforted me in my trouble.
I was kept in that dungeon fourteen weeks.

When the court sessions came, the judge and justices being on the bench,
as I was looking out through the iron grate, a justice of the peace,
one of those who committed me, whose name was William Moore, going by,
saw me standing and coming up to me, said, he was very sorry to see me there,
and had been many times troubled in his mind for me, since I was committed,
but he could not now help it, for I was committed without bail or mainprize.
I told him, he had brought that trouble on himself,
by his haste and passion in committing me on those terms,
for my faith and conscience towards God.
He said he was very sorry for it, and if he could do anything for me,
he would readily do it.
The enemies of truth reported, that I was in prison,
because I and the Quakers were for having no law or government, but the light in man.
I thought it would be a good opportunity to show
the falsehood of this report to the country;
and I desired him to get me leave to come into court before the judge,
for I had something to say.
He said, he had spoken to the judge about me, but he would not meddle with me,
being I was committed at the sessions.
I desired him however, to let me come into court:
so he went into court and presently sent the jailer for me;
but so soon as he put me into the session-house, he slipped away.

I spoke to the people, who thronged in, bidding them make way for the prisoner.
On which they made way, and I got near the judge; but he spoke aloud and asked, who I was?
what I was?
and what I came there for?
I answered with a loud voice and said, I am a prisoner,
and have been a close prisoner fourteen weeks, for my religion and faith towards God,
and I want justice, and to be tried by the law now established;
for I know no law that I have broken.
And I am one who have ventured my life to establish the government as it now stands;
and own the government and the laws.
But the judge was disturbed, and cried out to the jailer to take me away.
The jailer came, and I cried aloud to the people, to take notice and bear witness,
I owned government and wholesome laws, and desired justice accordingly;
but could not have it.
He took me away, but presently one was sent to bid him not put me in the dungeon.
I was very easy in my spirit, and much comforted in the Lord, for his power was with me;
some sober professors came to me and said, they were very glad,
and well satisfied with what I said of our owning the government and laws,
for they had heard other things concerning us.
This wrought mightily in the minds of people, and truth got ground.
The next day I was turned out of prison without any trial.

Now the most of the land we had of Kempston was recovered from him by law,
so that we sent our cattle to graze near Rossenallis, and being now at liberty,
I went there to live with my family; the Friends that removed having settled thereabouts,
we kept a meeting twice in the week for the worship of God,
and we also got meetings in several other places to spread truth.
