== Chapter VII

[.chapter-synopsis]
* The government and Chancellor Boyle`'s clemency towards Friends, upon William Edmundson`'s petitioning them against G. Clapham`'s cruelty, then priest of Mount-melick
* Prophetic warning to the inhabitants of Londonderry
* Conference afterwards with the bishop and mayor of that place
* Settling of meetings for Discipline in Ireland, by George Fox, in 1669

1665+++.+++ Having my liberty,
I found a concern on my mind to solicit the government
against the priest`'s fierceness and cruelty;
for George Clapham, priest of Mount-melick,
endeavoured to prevent the miller`'s grinding corn for our families,
or any speaking or trading with us, or any of our families.
He watched the market and Friends`' shops, and those whom he saw or knew to deal with us,
he sent the apparitor to summon to the bishop`'s court;
and so forced them to pay him and the apparitor money to get freed from that trouble,
they being afraid of the bishop`'s court, it bore such a great name.

This priest told his hearers that if they met any of us in the high-way,
they should shun us as they would shun the plague; and if they owed us anything,
they need not pay it; or if they knocked us on the head, the law would bear them out.
At which the people were much troubled,
and in general their love declined from the priest, and drew towards Friends;
and they would offer their servants to carry our corn to the mill,
that we might get bread for our families, or any other kindness they could do for us.

I drew up a statement of several of his gross proceedings,
and got many of his own people to sign it, who had been abused;
then went to Dublin and petitioned the government,
who with the primate took notice of it, and the privy-council resented it,
being contrary to all law and rule.
They sent an order for the priest and apparitor to appear before the council;
where they were sharply reproved, and would have been punished,
for the primate said he would make them examples.
But I told him, we desired nothing but to be quiet, and live peaceably in our callings,
and that they should desist from their cruelty.
The primate, who was also chancellor, said, if they did not desist,
we should write to him, and he would make them examples to the nation.
So I forgave them, and let all proceedings fall.
This gained much on the minds of many chief men in authority.

Priest Clapham was very angry against me, although I had forgiven him;
being very greedy and covetous.
One time he took my neighbour`'s horse and car,
came to my house and loaded up and carried away a great deal of cheese;
also at that time he took away much goods, corn,
and wearing clothes from Friends of our meeting, for some church dues, as he said.
While I was at a meeting in Mount-melick, where I used to attend when at home,
he being a justice of the peace, sent a constable to apprehend me,
and made a court order to send me to Maryborough jail,
but the earl of Mountrath superceded his warrant,
and set me at liberty until the court sessions.

When the court sessions came, he stood by me against the said priest,
who had drawn up two indictments against me; and when they came into court,
four lawyers one after another pleaded for me,
though I knew nothing of them or gave them any fee.
But the Lord gave us place in the minds of people, and their hearts yearned towards us,
so that as I passed through them in the courthouse, they would say, the Lord bless you,
William, the Lord help you, William.
The indictment was quashed, and the priest was hissed at by the court to his shame;
the judge also turning against him.
Several Friends came a great way to see and hear the trial,
and greatly rejoiced in the Lord to see the priest frustrated in his evil designs.

Another time this priest Clapham indicted several Friends of
our meeting at the court sessions at Maryborough,
and me for being at a meeting on such a day, which he called an unlawful assembly;
and for not being at church, as he called it, on the same day.
He also indicted me for not paying a levy,
or assessment towards the repairs of his worship house,
though the wardens and constable had before taken from me, for the same,
a mare worth three pounds ten shillings.
Several Friends were thus proceeded against,
and we were fined and an order given to distrain our goods;
on which account I rode to Dublin, and petitioned the lord lieutenant and council.
I and one other Friend were admitted into the council-chamber, to state our grievance,
and had a very fair hearing,
that judge being present who gave judgment against us at the court sessions.
The council gave their judgment, that the proceedings were illegal.
The lord lieutenant wished to know, why we did not pay tithes to the ministers?
I showed him out of the Scriptures that the law was ended which gave tithes,
and the priesthood changed which received them, by the coming and suffering of Christ,
who had settled a ministry on better terms, and ordered them a maintenance.
He would know what maintenance the ministry must have?
I told him, Christ`'s allowance, and I showed him from the Scriptures what it was,
as the Lord opened them to me by his spirit and power,
which gave me wisdom and utterance, and set home what I said unto their understandings.
There were three bishops present, and not one of them replied in all this discourse,
though so nearly concerned in it.
In the conclusion, the lord lieutenant bid God bless us, adding,
we should not suffer for not going to their public-worship,
neither for going to our meetings.
This quieted the priest,
and it soon went abroad that the Quakers had the liberty of their religion,
which was a great ease to Friends,
for we had been often imprisoned and had much goods taken from us on that account.

While I was in the county of Armagh visiting Friends,
our meetings were broken up by the soldiers, and many of us put in prison.
There we had living powerful meetings,
many Friends and friendly people came out of the country to them,
and though under sufferings, we had a sweet heavenly refreshing time,
for the glory of the Lord shone among us.
There were in the ministry George Gregston and myself.
The priest of the town kept his worship in the session-house,
and it being under one roof with the jail, we could hear him at his worship;
likewise he and his people could hear us at ours.
The Lord`'s power so confounded him, that he could not get on in his devotion,
but left the place and came no more to worship there while we were prisoners.
The Lord`'s power, truth and testimony were over them all,
everlasting praises to his great name.

Another time I was moved of the Lord to go from my own house to Londonderry,
to warn them to repent, or the Lord would bring a scourge over them.
So in obedience to the Lord I went,
and when I came there it happened to be a day of humiliation, as they called it,
being at the time the plague was in London.
They were gone to their worship at the cathedral, and I was moved of the Lord to go there.
When I came to the door, the man who used to ring the bells met me,
and took me by the hand, and led me near the pulpit, where the bishop was preaching.
He thought he had got a Presbyterian convert, and did not take off my hat,
until he saw the people gaze at me, observing which, he took my hat off and laid it by.
I stood there until the bishop had done preaching; the people`'s eyes were on me,
and I spoke what the Lord gave me to say, warning them to repent,
or the Lord would bring a scourge over them, and scale their walls without a ladder.
The bishop called to the mayor and officers to take me away,
but the dread of the Lord`'s power was over them, they all sat still,
and did not molest me.
When I had delivered the Lord`'s message, I went towards the door,
where the man who led me in met me, and took me by the hand,
having my hat in his other hand; he led me to the door, put my hat on my head,
and bid God speed me well.

I went to my lodging, which was a public house, kept by John Gibson, who with his wife,
were convinced of the truth.
There I was moved to write a paper to the bishop and magistrates,
and the next day I went to the bishop`'s house with it, he living in the city.
I knocked at the door,
and the man who led me in and out of the worship house the day before, opened the door,
and made his apology, that he did me no harm at the church.
I told him he did well, and asked him for the bishop.
He said he was gone to dinner, and a great many gentlemen with him;
for there was a great meeting of them;
and he told me it would be better to come when they had dined.

I went back to my lodging, and in a little time came again, and they having then dined,
I sent my paper to them, and they sent a priest to call me up.
As I was going up the stairs, the word of the Lord said unto me,
I will make you as a wall of brass.
There were the bishop, the governor, the mayor, several justices, priests and others,
in a great dining room; the bishop sat with his hat on,
and the rest all stood bare-headed.
When I came into the room, the bishop rose up from his seat, put off his hat,
and met me with several low bows; but I was as a wall of brass,
and stood in the power of the Lord, that was with me, which smote him.
Then he sat down, and told me that what I said at their worship the day before was true,
and he preached the same, and pointed to two of the priests, saying,
they preached the same, therefore there was no need of me.
I told him, the more preachers of truth the better, and there was need enough;
and he being a bishop, ought to encourage me.
He said he must know what I came to the city for and who sent me,
and he bid the mayor examine me.
So the mayor came from among the rest, and asked me where I dwelt?
I told him, in the Queenscounty.
He asked what trade I was?
I told him, a ploughman.
He asked my business there, and who sent me?
I told him, the Lord Jesus Christ sent me, to warn them to repent,
or he would lash them with his judgments.
As I declared this, the Lord`'s power reached him, and he could not refrain from tears,
being a tender-spirited man; so he went back behind the rest.

The bishop seeing this, was amazed,
and bid two of his waiting men take me into the buttery and make me eat and drink.
They took me by the arms down the stairs, and bid me go into the buttery to eat and drink.
I told them I would not eat or drink there; but they urged me, saying,
I heard their lord command them to make me eat and drink.
I asked them if they were Christians at that house?
They said, yes; then said I, let your yes be yes, and your no be no,
for that is Christ`'s command.
I said, I will not eat or drink here, and you take no notice of it,
being accustomed to break your yes and no.
They stood silent, and let me go,
for the Lord`'s power astonished them and was over them all.

I went to my lodging, and was moved of the Lord to write a paper,
and put it on the gates of the city,
and to declare the Lord`'s message through the streets.
Accordingly I wrote a paper that evening, and in the morning went first to the mayor,
and told him the message I had to the city.
He said the bishop had chided him the day before, because he did not send me to prison;
but he did not intend to do it, so long as the law would bear him harmless,
and wished he had me living by him,
and then I should soon have another to help to suppress wickedness.
I went from the mayor, and beginning near Water-gate,
sounded the Lord`'s message through the streets; it was dreadful to the people,
and several ran as if before naked swords.
As I came near the main guard, a soldier being at the door mocked,
but in the dread of the Lord`'s power I looked in at the guard-house door, and cried,
"`Soldiers! All repent.`"
The soldiers on the guard were smitten, as men affrighted,
for the power of the Lord was mighty, in which I performed this service;
and when I had done, I put a paper on the gates, as the Lord moved me.
Being clear, I left the city, and visited Friends`' meetings in the north,
and they admired the Lord`'s goodness that
carried me through that service without a prison.

The day I left Londonderry, the bishop took his journey towards Dublin, and,
as I was informed by those who said they heard him,
he preached a sermon before the lord lieutenant and government against the Quakers,
comparing us to Korah, Dathan and Abiram, urging them with many arguments to suppress us;
but he was taken sick in the worship house, carried to his lodging, and died,
having preached his last sermon against the Lord`'s people and servants,
who truly fear him.

The people of Londonderry afterwards remembered these warnings,
and spoke of them in their great distress in the last siege,
when thousands died for lack of bread, and through other miseries,
the Lord having scaled their walls without a ladder,
yet allowed not their enemies to get the city with force of arms, or scaling-ladders.
And thus the warning before given them was fulfilled.

In the year 1609, George Fox came to Ireland,
and several Friends in the ministry with him.
He settled men`'s and women`'s meetings among Friends throughout the nation,
that faithful men and women should take care in the government of church affairs,
among our own Society, which meetings are of great service.
I was much eased by it, as I told George Fox at that time,
for I had a great concern in those things,
which had lain heavy upon my spirit for several years before;
and this gave every faithful Friend a share of the burden.
I travelled with George Fox from place to place in the several provinces.
When he had answered his service here, and was gone for England,
I laboured among Friends in this nation, both in doctrine and church discipline,
the Lord having given me an understanding in the government of his church,
and his heavenly power attending, which enabled me to go through,
and carried me over all opposition.
