== Section IX.

Of his difficult voyage to the West Indies in 1675.
His public dispute with Priest Ramsey,
in the presence of about three thousand--Of his
manifold perils and services in North America,
both in the islands and continent, by sea and land, until his return, in 1677.

About the year 1675,
I was moved of the Lord to go to the West Indies again in truth`'s service;
and after some time, many Friends being acquainted with it, and having unity therewith,
my wife also being willing to give me up, I inquired for shipping to Barbadoes,
and heard of a ship at Cork bound there, one Edward Hunt, a Friend,
being merchant and part owner, who also went in her himself.
I had an account near the time when they would be ready to sail,
and accordingly went to Cork, my wife accompanying me there,
and several Friends of our meeting; when we came to Cork,
I agreed with the said Edward Hunt for my passage.
My wife and Friends who went back,
took their leave of me in much tenderness and brokenness of spirit, in the love of God,
in which we gave up one another to be disposed of in his heavenly will.

A few days after this we sailed from Cork harbour, and things were well,
the Lord`'s goodness being enjoyed at sea, as well as on land;
but before we made our voyage we fell short of water,
and went to allowance in the hot climate.
We had six horses on board, belonging to the merchant, and their hay was spent;
so were forced to shave deal boards, and pull the straw out of the men`'s cabins,
to mix with the shavings to give the horses to eat, and gave them biscuit;
thus preserved their lives until they got ashore.

In the latitude of Barbadoes, we met with a ship from Guinea,
bound for Barbadoes with three hundred negroes;
we desired the master to let us have a barrel of water,
but he told us he would not let us have a barrel of water for a barrel of silver;
for he had been at allowance many weeks, and was afraid of running out.
The day we espied Barbadoes we had scarcely half a barrel of water left.
In about eight weeks we made our voyage, and landed well in Barbadoes,
where Friends received me gladly;
and I had a largo and open door among the people in the labour of the Gospel.
People`'s lofty spirits were brought down, by reason of a very extraordinary storm,
called a hurricane, which had done abundance of damage in the island, killed many people,
and destroyed many brave buildings, ships and small vessels.

At this time there was great resorting to meetings, so that they were very full.
I travelled through all parts of the island, and had meetings:
many were convinced and received the truth,
and Friends`' hearts were opened and enlarged in the love of God,
both to receive truth`'s doctrine aad discipline.
I had very good service, both in public meetings for the worship of God,
and men`'s and women`'s meetings about church affairs;
also in negroes`' meetings in families,
and several meetings were settled on such accounts, the Lord being with me,
who gave me wisdom and understanding in the managing of those affairs,
and the Lord`'s power attended his work, and blessed and prospered it mightily;
so that things relating to truth`'s affairs, both as to doctrine and discipline,
were settled to great satisfaction.

At this time there was one Tobias Fryer, a man of great substance and repute,
and of authority in commission of the peace, whose wife was a Friend,
and had laid long sick.
She had a great desire to see me, and sent for me twice;
but I being closely employed in the Lord`'s service, sent her word,
to ask her husband`'s leave to have a meeting there,
and I and some other Friends would come and visit her; she did so,
and her husband granted it.
On the day appointed I went, and many Friends and others came;
it was a very thronged meeting, and the parish priest, one Ramsey, was there,
and Justice Fryer got him seated in the midst of the throng of Friends.

After some time I stood up to speak of the things of
God and the divine mysteries of Christ`'s kingdom,
whose heavenly doctrine was clearly opened and preached,
by the Divine operation of his holy Spirit,
to the great satisfaction of the meeting and comfort of Friends,
so that many of them after the meeting, expressed their gladness and satisfaction.
The priest was uneasy, yet could make no opposition,
for the Lord`'s power was over him and chained him down, though he was a very bad man.
But the testimony of truth, in the demonstration of the spirit and power of the Lord,
being set over him, made him fret: he also came to Bridgetown,
and brought many rude people to our meeting there; which was very large and full.
He there abused Friends in foul language, calling us heretics, blasphemers and traitors,
and challenged a dispute with me, to prove his charge,
which he said he would do from our own books.
So after we got things a little quiet, we broke up the meeting;
and at my lodging I wrote a few lines to him, after this manner:

Priest Ramsey,

Forasmuch as you in public hast charged our Society with heresy, blasphemy and treason;
and that you would prove this charge from our own books,
and on that account hast challenged me to a public dispute, I am willing,
with the Lord`'s assistance, to give you a meeting in defence of our faith and doctrine.

William Edmundson

When these came to his hand, he seemed to cool in his hot challenge, saying,
he had not a convenient place,
fit for such a concourse of people as would come to the dispute; and besides,
he would first have an hour`'s discourse with me in private.
To which I replied again in writing, that for private discourse with him,
I was not willing, but in public; and if he could procure leave of Justice Fryer,
to meet at his house where we did before, I would come to him in his own parish,
otherwise I would get leave of Colonel Linn, to meet at his house.

While I was writing this.
Colonel Linn came to see me, and I told him what I was writing,
he said all his house was at my service; and if that were too little,
he had conveniency of trees about his house,
and could make shades for thousands of people.
So I sent my letter to the priest; and he sent his answer,
that he would come to Colonel Linn`'s on such a day.

It soon spread abroad, so that most of the Friends in the island came there,
and abundance of people; it was thought there were above three thousand.
There came also several justices of the peace, and others of account.
We met out of doors under shades; and when the meeting was settled,
I proposed that both parties should be limited
to an hour`'s time in questions and answers,
and not to exceed at any time;
and that both parties should prove their assertions by the holy Scriptures,
or else to be void.
This was assented to, but not observed by the priest,
for instead of proving his former charge against Friends,
he went out into railing and slandering of several Friends,
sometimes against us all in general;
and thus manifested his folly to the sight of the people.
Friends were cool in their minds, and, as we had an opportunity,
opened things to the people concerning our faith and principles; and having a Bible,
showed them Scriptures for them.
There was a general satisfaction among them concerning us,
and it was of great service for truth.

This priest Ramsey had been a friar, and went out of England for misdemeanours,
as after appeared by a certificate under the hand and seal of the Earl of Rochester,
occasioned by a slander cast upon a Friend in England,
which he there said in public he had from the said earl,
who was a near kinsman to the Friend accused.
After the meeting, Priest Ramsey went to the governor.
Sir Jonathan Atkins, and made a great complaint against me,
that I was a Jesuit come out of Ireland, pretending to be a Quaker,
and to make the negroes Christians; but would make them rebels,
and rise and cut their throats.
Upon this the governor was about to send his warrant to apprehend me, but I heard of it,
and went to him before the warrant came; one Robert Dree, a Friend, went along with me.

When we came to the governor, and he knew my name and who I was,
he said he had heard of me, and would take a course with me; using many rough words,
and threatening highly what he would do to me.
He sent his man for the marshal, who lived a mile from there;
but before the marshal came, we had much discourse, and among other things he told me,
he was informed that I was making the negroes Christians, and would make them rebel,
and cut their throats.
I told him it was a good work to bring them to the knowledge of God and Christ Jesus,
and to believe in Him who died for them and for all men;
and that that would keep them from rebelling, or cutting any man`'s throat.
But if they did rebel and cut their throats, as he said,
it would be through their own doings, in keeping them in ignorance and under oppression,
giving them liberty to be wicked,
and on the other hand starving them for lack of food and clothes convenient:
so giving them liberty in that which God restrained,
and restraining them in that which God allowed and afforded to all men,
which was food and clothes.
After some time he grew very moderate.

The marshal came, and asked him what his pleasure was?
He answered, bethought to have committed me to prison, but his mind was altered;
and asked me if I would appear before the council next day?
I told him I would, if he commanded me; he said he did command me,
and so dismissed me for that time.
Next day I came to the council-house,
and many eminent Friends of the island came with me;
I was called into the council-chamber, and Friends stayed without.
There were the governor and most of the chief men of the island;
also the envious Priest Ramsey was there, strongly accusing Friends of heresy,
blasphemy and treason, and would prove it out of Edward Burrough`'s book.
The book was in town, I sent a Friend for it, who brought it to the governor.
The priest turned it over and over but could find nothing to prove his charge.
The governor checked him, and several of the council frowned on him:
then the priest went on his knees, and asked them forgiveness;
and from that time the governor was kind to me.

I laboured in the island about five months and had great service for the Lord;
many received the truth, and things were well among Friends, and in good order.
Being clear of the service there, and having drawings in my spirit to New England,
I took passage for Rhode Island in a yatch, of which Joseph Bryar, a Friend, was master.
When they were near ready to sail, I went and took leave of the governor,
and he was very kind and friendly.
The day we sailed, many Friends came to Bridgetown, to take their leave;
and we parted in the love of God and sweet unity of his blessed spirit,
in much tenderness.
Thomas Redman, a Friend and doctor, went with me.
We had a good comfortable passage, and came well to Rhode Island in about three weeks.

At that time New England was at war with the Indians, except the colony of Rhode Island,
the governor of it being a Friend, yet the Indians burnt some towns out of the island,
and killed several people who belonged to the government;
but by the Lord`'s providential hand, were not allowed to come into the island.
The Indians prevailed mightily, burnt many considerable towns, and murdered people daily.
It was a perilous time, and the ways infested with murderers,
the Indians lying hidden in bushes, shot men down as they travelled,
before they saw them; and many were killed afier that manner.

When I had stayed to some meetings with Friends in Rhode Island,
it was with me to travel eastward towards Piscataway,
to visit Friends there who were under distress by reason of the war,
though all looked upon it dangerous travelling; however,
I committed my life to God who gave it, and took my journey.
One Friend ventured to go with me, to guide me through the woods to Sandwich,
and by the Lord`'s good hand we got safe there.
Friends were glad of my coming, for there was an honest tender people there,
who loved the Lord and his truth.
I stayed with them two meetings, and we were well refreshed in the Lord,
and one in another.
I travelled from there to Seffenase, and had a meeting; from there to Boston alone,
being thirty miles, and stayed one meeting: then went to Salem,
and so to Piscataway river, visiting Friends, and having meetings at several places.
I came to Great Island, and stayed a meeting or two with Friends there,
and we were well refreshed together in the Lord.

Leaving my horse there, I went in a boat to Nicholas Shepley`'s,
a man of note in that country, he and his wife both being honest Friends;
from there over the river several miles, where there were many honest Friends,
and had a meeting with them on a first-day of the week;
which was very large and precious.
Many came from far to it, and blessed the Lord for that comfortable opportunity.
After the meeting I took leave of Friends in the love of God,
and going back to Nicholas Shepley`'s, stayed there two or three days,
and had a good meeting, to which many Friends and others came;
we had also a men`'s meeting about church affairs.

About this time, there was a cessation of the war with the Indians on that river,
and one evening, while I was at Nicholas Shepley`'s,
there came in fourteen lusty Indian men, with their heads trimmed,
and faces painted for war; they looked fierce--I sat down with them in the hall,
and would have discoursed with them familiarly, for some of them spoke broken English;
but they were churlish, and their countenances bloody.
So I left them, and told the Friend, I saw they intended mischief in their hearts,
but the Lord chained them; and they went away in the night, without doing us any harm.
Next day I was to go to Great Island, and in the morning Nicholas Shepley told me,
that he was informed the Indians intended to make a new insurrection.
I went by water to Great Island, as I intended,
and had a heavenly meeting with Friends before parting: I left them tender,
in a sense of the love of God.
After I left them, the Indians rose in arms and murdered about seventy Christians,
as the post brought news, but I did not hear of one Friend murdered that night.

I came back to Salem, and had several meetings in that quarter,
in some places where none had been before.
I had two meetings at Marblehead, many resorted to them,
and several were convinced and received the truth.
People`'s minds were cast down,
because of the Indian wars that prevailed mightily upon them.

I travelled in many places as with my life in my hand,
leaving all to the Lord who rules in heaven and earth.
I heard of some tender people at a place called Reading,
so I and five or six Friends went there to an ancient man`'s house, whose name was Gould;
his house was a garrison, for at that time most of the people in those parts,
except Friends, were in garrisons for fear of the Indians.
When we came to his house the gates were locked, we called,
and the old man opened the gate.
One of their elders was at prayer, so I stopped Friends until he had done,
then we went into the room, where several were met to exercise religion,
but they seemed to be disturbed at our coming.
I stood still, and told them we came not to disturb them, for I loved religion,
and was seeking religious people; the old man of the house bid us sit down,
and he sat by me.

As I sat, my heart being full of the power and spirit of the Lord,
the love of God ran through me to the people.
I told them I had something in my heart to declare among them,
if they would give me leave.
The master of the house, who sat by me, bid me speak;
and my heart being full of the word of life, I spoke of the mysteries of God`'s kingdom;
and as I was speaking I touched a little upon the priests;
the old man clapped me on the shoulder, and said he must stop me,
for I had spoken against their ministers--I stopped, for I was tender of them,
and felt they were a tender people; yet my heart was full of heavenly matter.
After a little pause, I told them,
I had many things to declare unto them of the things of God; but being in that house,
must have leave of the master of it.
lie bid me speak on,
which I did in the demonstration of the spirit and power of the Lord;
so that their consciences were awakened,
and the witness of God in them answered to the truth of the testimony;
they were broken into many tears, and when I was clear in declaration,
I concluded the meeting with fervent prayer to the Lord.

The old man rising up, got me in his arms, and said he owned what I had spoken,
and thanked God that he could understand it;
and said he had heard that we denied the Scriptures, and denied Christ who died for us;
which was the cause of that great difference between their ministers and us.
But he understood this day, that we owned both Christ and the Scriptures;
therefore he would know the reason of the difference between their ministers and us?
I told him their ministers were satisfied with the talk of Christ and the Scriptures;
and we could not be satisfied without the sure, inward,
divine knowledge of God and Christ,
and the enjoyment of those comforts the Scriptures declared of,
which true believers enjoyed in the primitive times.
The old man replied with tears, those were the things he wanted.
He would not let us go until we had eaten some food with him,
though at that time provisions were scarce, because of the great destruction by the wars.
Thus leaving them loving and tender, when we parted the old man wept, got me in his arms,
and said he doubted he should never see me again.

I went from there to Boston, and had meetings there,
and in several places in that quarter,
having great exercise with some who professed truth and lived not in it;
who did much hurt, and hindered the Lord`'s work.
When I was clear of those parts, I went back to Rhode Island by sea,
in a little bark belonging to Edward Wharton, a Friend, who lived at Salem.
In a few days we landed at Rhode Island,
where great troubles attended Friends by reason of the wars,
which lay very heavy on places belonging to that quarter without the island,
the Indians killing and burning all before them; and the people, who were not Friends,
were outrageous to fight: but the governor being a Friend, Walter Clark,
could not give commissions to kill and destroy men.
Friends were glad of my coming,
and it pleased God that it was to good purpose in several respects;
the faithful and honest-hearted among Friends were much
helped and strengthened by my being there.
I stayed some time among them, and had many blessed and heavenly meetings to worship God;
also men`'s meetings for church affairs.

While I stayed at Rhode Island, the heat of the Indian war abated, for King Philip,
the chief in that war, was killed, and his party destroyed and subdued;
presently after a sickness came which proved mortal and took many away,
so that there were few families in the island
but lost some in two or three days`' sickness.
Many Friends died, yet I constantly visited sick families of Friends,
although the smell of the sickness was loathsome,
and many times I could feel all the parts of my body as it were loaded with it,
so that I would say to sick families, it was much if I did not carry their sickness away,
I was so loaded therewith.
After some time it seized on me with such violence,
that I was forced to keep my bed at Walter Newberry`'s, in Newport.

Then some loose spirits, whom I had dealt with for their looseness, were glad,
and thought their curb and reins were taken off; but the Lord healed and raised me up,
so that in about ten days`' time I was able to appear in public meetings,
and although my body was weak by reason of travels and troubles with wrong spirits,
loose livers and false brethren, yet the Lord`'s power carried me over all.
When I had stayed some time labouring in those parts, and was clear of that service,
I was drawn towards New York, and James Fletcher being here in the service of truth,
would go with me.
So we took our leave of Friends in the love of God,
and took shipping at Rhode Island for New York.

While we were on board the sloop, it came upon me to go to New Hertford,
a chief town in Connecticut colony, which lay about fifty miles in the country,
through a great wilderness, and very dangerous to travel, the Indians being in arms,
haunting those parts, and killing many Christians.
It looked frightful, that I, who was a stranger in the country,
should undertake such a journey in those perilous times;
but the service came close upon me, and I was under great exercise of mind about it,
yet said nothing of it to any man for some days.

We were sorely tossed at sea, forward and backward, by contrary winds and bad weather,
yet got once on shore in Shelter Island, and went to Nathaniel Sylvester`'s, a Friend,
who dwelt there, where we had a meeting.
After this the wind and weather seeming to favour us, we went aboard again,
and set on our voyage, but in the night it was exceedingly stormy,
and we were in great danger of being cast away; yet by the Lord`'s providence escaped,
but were driven back to New London.
The wind continuing against us, we stayed there three days,
and endeavoured to get a meeting, but the people being rigid Presbyterians,
would not allow us to have one.

We heard of some Baptists, five miles from there, who kept the seventh-day as a sabbath.
I had a concern upon me to visit them; so James Fletcher,
and another friendly man who came from Old England, and lived near New London,
went with me.
It was on a seventh-day of the week when we came there,
and they were met together with their servants and negroes, keeping that day,
sitting in silence.
When we came in they seemed to be disturbed; but I spoke gently to them,
and said we came not to disturb them,
but hearing they were a people that differed in
religion from the generality of people in that country,
we came to visit them; and if they had a religion that was good, to share with them.
The master of the house bid us sit down; we sat a pretty while in silence,
and my heart was filled with the word of life, yet I was afraid to raise their spirits,
lest thereby I should lose my service;
for I felt there were desires in them after the knowledge of God.

So I began my service by way of question,
and queried if they allowed to ask questions one of another about religion?
Which they assented to.
I asked them why they kept that day as a sabbath?
They said it was strictly commanded in the Old Testament.
I asked if we were obliged to keep all the law of Moses?
They said, no,
but the keeping of the sabbath seemed to be more required than the rest of the law,
for the priests blamed the Jews for breaking the sabbath,
more than any other part of the law.
I told them they were under a mistake, for they might find that our Saviour Jesus Christ,
when he was in the flesh,
did many things which the Jews accounted a breach of the sabbath;
as healing people on the sabbath-day, travelling with his disciples,
who plucked ears of corn; and doing many things on the sabbath,
with which the Jews were highly offended.
So I opened many Scriptures to them, showing,
that Christ had ended the law of the old covenant, and was the rest of his people,
and that all must know rest, quietness and peace in him.

Then they asked me about water baptism and breaking of bread,
and we had much discourse concerning it.
They were very moderate and ready in the Scriptures.
I showed them, that John, who had the ordinance of water baptism,
said he baptized with water, but Christ should baptize them with fire and the Holy Ghost;
and that his must decrease, and Christ`'s must increase.
That by our account it was drawing towards seventeen hundred years since that day,
which was sufficient time to wear to an end that which decreased,
and establish that which increased.
It was material for such as held water baptism to be in force,
to show how far it was decreased and when it would be at an end;
and Christ`'s baptism increased to perfection,
and established according to John`'s testimony.
But as for me, I believed that John`'s water baptism was ended long ago,
and Christ`'s established, and that there was but one faith and one baptism,
as the apostle witnessed to the Ephesians.
I opened to them, that Christ was the substance of all those things,
and his body the bread of life, that we must all feed upon.
They were all quiet, and I declared to them, in the openings of life, the way of truth;
and when clear, concluded in fervent prayer to God; and they were very tender and loving;
so we parted.

The next day, being the first day of the week, we appointed a meeting near New London,
at a friendly man`'s house who was with us; to which several of the Baptists came,
and many other sober people.
The Lord`'s power and presence were with us;
but the constable and other officers came with armed men,
and forcibly broke up our meeting, haling and abusing us very much;
but the sober people were offended at them.

That evening we weighed anchor and set sail, the wind seeming somewhat fair for us;
but it still remained with me to go to New Hertford,
yet it seemed hard to give up to be exposed to
such perils as seemed to attend that journey;
but I kept it secret, thinking that the Lord might take it off me.
We had sailed but about three leagues, when the wind came strong ahead of us;
that night we had a storm, and were glad to get a harbour, where we lay some days,
the wind blowing stiff against us.
The hand of the Lord came heavy upon me, pressing me to go to New Hertford;
so I gave up to the will of God, whether to live or die.
Then I told the company, that I was the cause,
why they were so crossed and detained in their voyage.
And I showed them how the Lord required me to go to New Hertford,
and the journey seeming perilous, I had delayed; but now must go,
in submission to the will of God, whether I lived or died.
The owner of the sloop wept and the rest were amazed and tender.

James Fletcher would go with me: so we went on shore, and bought each of us a horse,
and the next morning took leave of our sloop`'s company;
and went on our journey without any guide, except the Lord,
and travelled through a great wilderness, which held us most of that day`'s journey.
We travelled hard,
and by the Lord`'s gracious assistance got that night within four miles of New Hertford,
where we lodged at an ordinary, and the people were civil.
I got up next morning very early, it being the first day of the week,
and went to Hertford on foot, leaving my horse at the ordinary,
and desired James Fletcher to stay there until he saw the issue of my service,
for I expected at least a prison at Hertford.

I got there pretty soon in the morning, and I was moved to go to their worship.
I came to one great meeting-house,
but the priest and people were not come to their worship, it being early;
and my spirit was shut up from that place.
Then I was brought under great exercise of mind, fearing that the Lord was angry with me,
and rejected my service, for my delay under this exercise.
I went forward about half a mile, and came near to another great meeting-house,
where I found openness in my spirit to go.
I was glad of the Lord`'s countenance,
though the people were not yet come to their worship.

There was a large river, where they built many ships, about a quarter of a mile distant;
there I went and sat down, until I saw people go to their worship.
When they were gathered I went and stood in the worship-house, near the priest,
until he had done his service, when I spoke what the Lord gave me.
They were moderate and quiet, and the priest and magistrates went away,
but many of the people stayed, and I had good service among them.
When I had cleared my conscience we parted, and I went again towards the riverside.
As I was going a man called me to come to his house and dine with him.
I stood a little and looked at him, his spirit seemed to be deceitful;
I asked him if he would take money for his food?
He said, no; then I told him I would not eat with him.
So I went to the river-side again and sat down, though I had not eaten anything that day.

After some time the bells rang for their afternoon worship,
and I was moved to go to the other worship-house afore mentioned,
from which in the morning my spirit was shut up.
I went there, and the priest and people were gathered, having a guard of fire-locks,
for fear of the Indians coming upon them while at their worship.
I went in, and sounded an alarm in the dread of the Lord`'s power, and they were startled,
yet were kept down by the Lord`'s power,
in which I declared the way of salvation to them a pretty while; but after some time,
by the persuasions of the priest, the officers haled me out of the worship-house,
and hurt my arm so that it bled; then they took me to the guard of fire-locks on a hill.

And though it was a very piercing cold day, and I still fasting,
my body also thin by reason of the sickness I had in Rhode Island not long before,
and other exercises which I travelled through, yet the Lord`'s power supported me,
so that the officer who had me in charge,
first complained of the sharpness of the weather,
and asked me how I could endure the cold, for he was very cold?
I told him it was the entertainment that their great
professors of religion in New England afforded a stranger,
and yet professed the Scriptures to be their rule,
which commanded to entertain strangers; and besides they had drawn my blood.
I showed him my arm which was hurt; he seemed to be troubled,
and excused their magistrates.
I told him the magistrates and priests must answer for it to the Lord,
for they were the cause of it.
Then he took me to an inn, and presently the room was filled with professors:
much discourse we had, and the Lord strengthened me,
and by his spirit brought many Scriptures to my remembrance;
so that truth`'s testimony was over them.
As one company went away another came.

When they were foiled, a preacher among the Baptists took up the argument against truth,
charging Friends with holding a great error, which was,
that every man had a measure of the Spirit of Christ;
and would know if I held the same error?
I told him that was no error, for the Scriptures witnessed to it plentifully.
He said he denied that the world had received a measure of the Spirit,
but believers had received it.
I told him that the apostle said a manifestation of the
Spirit was given to everyone to profit withal.
He said that was meant to everyone of the believers.
I told him Christ had enlightened everyone that came into the world,
with the light of his Spirit.
He said that was everyone of the believers that came into the world:
and as I brought him Scriptures, he still applied them to the believers, saying,
there was the ground of our error,
in applying that to every man that which properly belonged to believers.
Then the Lord by his good Spirit brought to my mind the promise of our Saviour,
when he told his disciples of his going away, that he would send the Comforter,
the Spirit of Truth, that should convince the world of sin,
and should guide his disciples into all truth.
Thus the same Spirit of Truth, that leads believers into all truth,
convinces the world of sin.
So you must grant that all have received it,
or else show from the Scriptures a select number of believers; and besides them,
a world of believers who have the spirit; also another world of unbelievers,
that have no measure of the spirit to convince them of sin.
Here the Lord`'s testimony came over him, so that he was stopped,
and many sober professors, who stayed to see the end, acquiesced therewith,
and said indeed, Mr. Rogers, the man is in the right;
for you must find a select number of believers,
besides a world that have a measure of the spirit, that convinces them of sin,
and a world that has not the spirit, so not convinced of sin: this you must do,
or grant the argument.
He was silent, and the people generally satisfied in that matter,
their understandings being opened; so they took their leave of me very lovingly,
it being late in the night.

When they were gone, I desired the woman of the house to boil me a little milk,
for I had not eaten that day.
The aforesaid Baptist, Rogers, lodged there that night, but lived fifty miles off,
and was pastor to those seventh-day sabbath people,
that I had been with above a week before near New London.
The people of this house where we lodged being Presbyterians,
I called the Baptist from them into another room; he told me where he lived,
and what people he was pastor to.
I told him I was with his hearers, and they were loving and tender.
He also acquainted me, that he was summoned to Hertford,
to appear before the assembly then sitting, who had taken away his wife from him,
whom he had married some years ago, before he was of the persuasion that he now was of.
And since he became a Baptist, her father, being an elder of the Presbyterians,
was set violently against him, and endeavoured to divorce his daughter from him,
though he had two children by her,
for some ill act he had committed before he was her husband,
and while he was one of their church; whereof, under sorrow and trouble of mind,
he had acquainted her, and she had divulged the same to her father; for which,
he said they had taken away his wife.
I asked how he could join with them in opposing me;
and at such a time when I was but one, being a stranger,
and they abundance in opposition?
And, whether it was not unmanly to do so?
It being late, I desired some further discourse with him in the morning,
which he assented to; but although I was up before the sun rose, he was gone away before.

I sent to the officer, who had the charge of me the day before,
to know if he had any further to do with me,
who said I might go when and where I pleased.
So I paid the people for my night`'s lodging, and being clear of the service there,
I went towards the place where I left James Fletcher and our horses;
and in the mean time James Fletcher came another way to look for me:
thus we missed one of another.
When he came to Hertford, he heard by several where I was gone,
and came back and told me that I had set all the town a talking of religion.

The next morning we took our journey towards Long Island, and in three days came there,
where Friends received us gladly;
but were much troubled in their meetings with several who were gone from truth,
and turned Ranters, i. e. men and women who would come into Friends`' meetings,
singing and dancing in a rude manner, which was a great exercise to Friends.
We stayed among Friends in that part for some time,
and had large and precious meetings at several places;
many of those Ranters came to meetings,
yet the Lord`'s power was over them in his testimony, and chained them down.
Some of them were reached with it and brought back to the truth,
to own condemnation for their running out into liberty and wickedness.

When we were clear of that quarter, we took boat to East Jersey, and came to Shrewsbury,
where we stayed some meetings, and were refreshed with Friends in the Lord.
From there we went to Middletown, and had a meeting at Richard Hartshorn`'s,
which was full and large;
to which there came several people who were tainted with the ranting spirit.
One Edward Tarff came into the meeting with his face blacked,
and said it was his justification and sanctification; also sung and danced,
and came to me, where I was sitting waiting on the Lord, and called me old rotten priest,
saying, I had lost the power of God; but the Lord`'s power filled my heart,
and his word was powerful and sharp in my heart and tongue.
I told him he was mad, and that made him fret; he said I lied,
for he was moved of the Lord to come in that manner to reprove me.
I looked on him in the authority of the Lord`'s power, and told him I challenged him,
and his god that sent him, to look me in the face one hour, or half an hour;
but he was smitten, and could not look me in the face, but went out.
The Lord`'s power and sense of it was over the meeting,
in which I stood up and appealed to the rest, whether this was not the same power of God,
in which I came among them at the first, unto which they were directed and turned,
when they were convinced of the truth, showing them how the ranters went from it,
and were bewitched by a transformed spirit, into strong delusions.
It was a blessed heavenly meeting, people were tender and loving,
and Friends comforted and glad of that blessed opportunity.

Next morning we took our journey through the wilderness towards Maryland,
to cross the river at Delaware Falls.
Richard Hartshorn and Eliakim Wardell would go a day`'s journey with us;
we hired an Indian to guide us, but he took us wrong, and left us in the woods.
When it was late we alighted, put our horses to grass,
and kindled a fire by a little brook, convenient for water to drink;
then lay down till morning, but were at a great loss concerning the way,
being all strangers in the wilderness.
Richard Hartshorn advised to go to Rariton river, about ten miles back, as was supposed,
to find out a landing place from New York,
from which there was a small path that led to Delaware Falls.
So we rode back, and in some time found the landing place and little path;
then the two Friends committed us to the Lord`'s guidance and went back.

We travelled that day, and saw no tame creature;
at night we kindled a fire in the wilderness, and lay by it,
as we used to do in such journeys; next day about nine in the morning,
by the good hand of God, we came well to the Falls,
and by his providence found an Indian man, a woman and boy with a canoe.
We hired him for some wampampeg, to help us over in the canoe; we swam our horses,
and though the river was broad, yet got well over; and,
by the directions we received from Friends,
travelled towards Delaware town along the west side of the river.
When we had rode some miles, we baited our horses,
and refreshed ourselves with such provisions as we had,
for as yet we were not come to any inhabitants.
Here came to us a Finland man well horsed, who could speak English,
he soon perceived what we were, and gave us an account of several Friends;
his house was as far as we could ride that day; he took us there, and lodged us kindly.

Next morning, being the first-day of the week, we went to Uplands,
where were a few Friends met at Robert Wade`'s house, and we were glad one of another,
and comforted in the Lord.
After meeting we took boat and went to Salem, about thirty miles,
where lived John Fenwick, and several families of Friends from England.
We ordered our horses to meet us at Delaware town by land;
so we got Friends together at Salem, and had a meeting,
after which we had the hearing of several differences
and endeavoured to make peace among them.

Next day we went by boat, accompanied by several Friends, to Delaware town,
and there met with our horses according to appointment,
but for a long time could get no lodging for ourselves, or them;
the inhabitants being most of them Dutch and Fins, and addicted to drunkenness.
That place was then under the government of New York, and is now called Pennsylvania,
there was a deputy-governor in it; so when we could not get a lodging,
I went to the governor, and told him we were travellers,
and had money to pay for what we called for, but could not get lodging for our money.
He was very courteous, and went with us to an ordinary,
and commanded the man to provide us lodging, which was both mean and dear,
but the governor sent his man to tell me to send
to him for what I needed and I should have it.

The next morning we took our journey towards Maryland,
accompanied by Robert Wade and another Friend.
We travelled hard and late at night, to William Southerby`'s at Sassafras river.
From there we went among Friends on the Eastern Shore in Maryland,
where we had many precious heavenly meetings for the worship of God,
and men`'s and women`'s meetings to order the affairs of the church.
A blessed time we had together, to our mutual comfort.

After some well-spent time there in truth`'s service,
I had drawings to go over the great bay of Chesapeake,
to the Western Shore to visit Friends; and Samuel Groom of London, master of a ship,
being there, sent his boat and two of his men to take me over;
that night one of the men was under much trouble of spirit,
but we landed well early next morning at the cliffs.
I had many good meetings on that side of the bay, and good service several ways,
for there were some troublesome spirits gone out from truth,
who were a great exercise to honest true-hearted Friends;
the Lord gave me ability and understanding to deal with them,
and to set truth and its testimony over them, to the joy and satisfaction of Friends.

After some time spent there, I went to the Eastern Shore again,
and had many precious meetings with Friends, then took my leave in the love of God,
in order to go down the great bay of Anamessy, to visit Friends there,
accompanied by James Fletcher, and three other Friends to manage the boat;
but meeting with very foul weather, and contrary winds,
we were forced to put ashore on an island and pitch the boat,
having sails spread for our covering, and we lay there all night.

Next day, the weather being very foul with sleet and snow and the wind against us,
we stood over the bay to Patuxent river, and came to Benjamin Lawrence`'s house,
who received us kindly; and we had a good meeting there.
After which the wind turning somewhat fair, we took boat and went on our journey;
but it was very cold foul weather, sleet and snow,
and we were all that day and most of the night e`'re we got to the place intended,
which we reached with much difficulty.

When we came on shore, I could neither go nor stand,
but as two bore me up one by each arm,
I had such violent pains and weakness in my back and loins with the piercing cold.
We stayed to two meetings,
and soon after they took me to the boat in order to go to Virginia,
for I could not go without help.
We put into the great bay of Chesapeake, and as we crossed the mouth of York river,
a storm took us, and the wind came against us,
so that we were hard put to it to escape the breakers;
yet the Lord`'s eminent hand saved our lives.

A report went to Friends in Maryland, that we were drowned,
but we got to a little creek in a small island uninhabited,
and were forced to stay there three nights, the wind being against us,
also the weather foul and stormy with rain, sleet and snow.
We had no shelter but the open skies, and the wet ground to lie on,
this augmented my cold and pain, but the Lord bore up my spirit,
and enabled me to endure it, as he had done in many other afflictions.
As soon as suitable wind and weather presented, we took boat and set on our journey,
and came to a branch of Elizabeth river, to one Yeats`' house, where I had been before;
he and his family were convinced of the truth.

We came there in the night, a little before day,
and he caused a servant to open the door; they took me out of the boat,
and led me into the house, for I was not able to go alone, and set me in a chair;
but presently my spirit was uneasy and greatly disquieted,
being sensible things were wrong in that house.
In the morning the people got up,
and then it appeared plainly that they were gone from truth.
After I had discoursed with them concerning their running out, and had admonished them,
my spirit being very uneasy under that roof,
I desired our company to help me into the boat, which they did.
We went to Elizabeth Houtland`'s, about three or four leagues off;
where I stayed some days, and had meetings, and then James Fletcher left me.
In a few days I grew pretty well, so that I could travel,
and had many precious meetings with Friends, both for the worship of God,
and the affairs of truth relating to Gospel order.
There was indeed need enough of help, for things were much out of order,
and many unruly spirits to deal with.
I had good service and success, for the Lord blessed his work in my hand.

The country was in great trouble, and it was dangerous travelling in some places,
the Indians being at war with the Christians, and the governor,
Sir William Berkeley and Colonel Bacon at fierce war one against another;
so that the country was involved in trouble.
Friends stood neuter, and my being there was not in vain on that account.
I travelled from place to place for a time, and frigates came from England with soldiers,
to appease the difference between the governor and Colonel Bacon.
The latter died; several of his party were executed, and others fined in great sums;
but Friends were highly commended for keeping clear.

I was moved of the Lord to go to Carolina, and it was perilous travelling,
for the Indians were not yet subdued, but did mischief and murdered several.
They haunted much in the wilderness between Virginia and Carolina,
so that scarcely any dared travel that way unarmed.
Friends endeavoured to dissuade me from going, telling of several who were murdered.
I considered, that if I should fall by the hands of those murderers,
many thereby would take occasion to speak against truth and Friends;
so I delayed some time, thinking the Lord might remove it from me,
but it remained still with me.
In the mean time I appointed a meeting on the north side of James`' river,
where none had been, and several Friends came a great way to it in boats,
also the widow Houtland`'s eldest son,
with whom I walked near two miles the night before the meeting,
advising him of some disorders in the family, and so we parted.
He, with some Friends, went to one house to lodge, and I, with some other Friends,
went to the house where the meeting was to be the next day,
but before morning a messenger came to tell me, the young man was dead.

It was a great surprise to us: then the word of the Lord came to me, saying,
all lives are in my hand, and if you go not to Carolina,
your life is as this young man`'s; but if you go, I will give you your life for a prey.
So after the meeting, we put his body in a coffin,
and carried him in a boat to his mother, to bury him.

The next day I made ready for my journey, but none dared venture to go with me,
save one ancient man, a Friend.
We took our journey through the wilderness, and in two days came well to Carolina,
first to James Hall`'s house, who went from Ireland to Virginia with his family.
His wife died there, and he had married the widow Phillips at Carolina, and lived there;
but he had not heard that I was in those parts of the world.
When I came into the house, I saw only a woman servant; I asked for her master,
she said he was sick.
I asked for her mistress, she said she was gone abroad.
I bid her show me the room where her master lay; so I went into the room,
where he was laid on the bed, sick of an ague with his face to the wall.
I called him by his name, and said no more; he turned himself,
and looked earnestly at me a pretty time, and was amazed;
at last he asked if that was William?
I said yes.
He said he was affrighted, for he thought it had been my spirit; so he presently got up,
and the ague left him, and did not return.
He travelled with me the next day, and kept me company while I stayed in that part.

On the first-day following,
they appointed a meeting on the other side of Albemarle river,
where the man and woman had been convinced when I was there formerly;
but when we came the man told us his wife was just dying,
and it would not be convenient at that time to have the meeting there.
So we ordered the meeting to be about a mile from there, at one Tems`'s house,
a justice of the peace, who, with his wife,
was convinced and received the truth when I was in that country before.
There we had a full precious meeting,
but after we were gone from the house where the dying woman lay, she came to her senses,
and her husband told her of the meeting, and of me; she said she remembered me well,
and the words I spoke when I was there several years before, were as fresh in her memory,
as if she heard me speak them just then; and said it had been happy for her that day,
if she had lived accordingly.
She died before our meeting was done, so that I could not speak with her.
I had several precious meetings in that colony, and several turned to the Lord.
People were tender and loving, and there was no room for the priests,
for Friends were finely settled, and I left things well among them.
When I was clear of that service,
we returned to Virginia safe under the Lord`'s protection:
praises to his name for evermore!

After some meetings in several places, and settling things among Friends,
I was clear of that country, and it was with me to go for England,
to be at the Yearly Meeting at London;
there being then a Bristol ship in Elizabeth river, in which I took my passage.
The merchant and doctor of the ship, was a Friend, and a good companion in the voyage.
When the ship was ready, many Friends went aboard with me,
where we parted in the love of God.

In our voyage we had several meetings on board the vessel,
and when we came between Newfoundland and Ireland, we met with fierce southerly winds,
which drove us far northward, and for many days we lay under much stress of weather;
then finding a concern upon my mind, I called the master and company down into the cabin,
where I prayed fervently to the Lord with them,
near the conclusion whereof he that was at the helm, called to hand the sails,
for the wind was turned.
Then were all glad, and the weather coming fair, we stood away to the southward,
and after a few days`' sail we got in sight of Ireland.
Having but a small breeze of wind, we stood along the Irish coast,
because England being then at war with France,
the master and merchant of the ship thought it not safe to keep out at sea,
so concluded to put into Cork harbour,
until the wind came fair to take us quickly over the channel for England.

The merchant, the mate and I, purposed, when we came to anchor, to go ashore at Cork,
I having a desire to see Friends there, and they being kind men,
were willing to have gone with me; but the master perceiving our intentions,
when we came to the mouth of Cork harbour, tacked about the ship,
and stood to sea out of mere crossness, being a very perverse drunken man.
He told us he knew our design, and would cross it: but it fell upon himself,
for after coming ashore, he was turned out of the master`'s place, and the mate put in.

When we came to Bristol, I stayed some meetings there,
and was well refreshed in the Lord Jesus with honest Friends,
though I was a stranger to them before, only they had heard of me.
Then I went towards London to the Yearly Meeting,
many Friends from Bristol and several parts of the country being in company.
The first day`'s journey we came to Marlborough, and Friends there having heard of me,
were desirous to have an evening meeting, to which I consented; and a sweet, heavenly,
comfortable meeting it was: after which,
they desired me to give them another meeting as I came back, to which I assented.

It came upon me that evening to be at Reading meeting,
which was to be on the morrow at the second hour in the afternoon,
and was thirty miles off.
I told Friends I must leave them,
and be gone towards Reading by the sun-rising next morning, to be there at the meeting,
and desired that a Friend might go with me, because I was a stranger to the way;
but they were not willing that I should leave them,
so concluded to be ready to travel with me next morning at sun-rising; which they did.
And though we had several women in company, we got to Reading to the meeting,
which was very large, there being many Friends from various parts,
and the Lord`'s power mightily appeared therein.
I was furnished in the word of life to declare the mysteries of God`'s kingdom,
as also to lay open the mystery of iniquity,
and honest Friends were tendered and refreshed;
yet many separate spirits being in that meeting,
they hardened themselves against the testimony of truth, as at other times.

The next day we came to London, where I met with many ancient Friends and brethren,
and we were sweetly comforted in the Lord, and glad to see one another.
I was at many public meetings for the worship of God,
and men`'s meetings with elders and brethren for managing truth`'s affairs.

Having been about two years away in the Lord`'s service,
from my wife and family and Friends in Ireland,
I left London in company with several Friends of Bristol and others,
purposing to take shipping at Bristol for Ireland;
but after I had gone seventeen miles on the way,
I found drawings from the Lord to return to London again,
to be at a meeting appointed there the next day for truth`'s affairs.
So in obedience to the Lord I went back, and was at the meeting,
where Friends were under a close exercise,
occasioned by a separate spirit which had prevailed and led
out some from the truth and unity with faithful Friends,
into a fleshly liberty from under the cross of Christ and self-denial.
I was exercised with Friends in this matter,
and in the dread of the Lord`'s power moved to
bear a testimony against that separating spirit;
also elders and brethren, in a sense of the living power of God then present with us,
judged and condemned it,
and a paper was given forth from the meeting to that effect signed by many.

Being clear, I took my leave of George Fox and Friends,
and proceeded again on my journey to Reading,
accompanied by Thomas Briggs and Thomas Bracey; so to Marlborough next day,
where we had a meeting, according to agreement before I went to London;
then I went to Bristol, and stayed some meetings;
and to King`'s-Road to take shipping for Ireland, several Friends went with me aboard,
where we took leave one of another in the tender love of God.

Setting out to sea, we had not sailed up with the Isle of Lundy,
before the wind turned contrary, and drove us ashore at Tenby, I went to Haverfordwest,
and visited Friends, and had meetings in several places with them;
we were well refreshed together in the Lord; and I stayed about a week.
The wind coming fair we put to sea again, and landed at Cork,
where Friends were glad of my coming.
When I had visited Friends`' meetings in that quarter, I went to John Fennell`'s,
in company with several Friends, where we had a refreshing heavenly meeting.
Here several Friends from Mount-melick, and thereabouts, came to meet me,
in whose company I returned home,
where I met with my wife and children in the same love of God
that had made us willing to part one with another for a season
for the Lord`'s service and truth`'s sake.

Some time after my coming home, I went to visit Friends`' meetings through the nation,
and was frequently at Monthly, Six-weeks and the National Half-yearly meetings,
as they came in course, both for the worship of God and Gospel order,
the Lord`'s presence and goodness still attending, and giving an understanding in matters,
that answered his will and mind both in doctrine and discipline,
and by his divine power he subjected Friends to his holy government,
setting judgment on everything that appeared to the contrary.
A holy, zealous concern was raised in the hearts of many honest Friends,
for the honour of God and his blessed truth.
