== Chatper X

[.chapter-synopsis]
* The just judgment of God upon George Clapham, the cruel priest
* In 1682, William Edmundson was excommunicated, and had a public conference with the bishop, in his court, about tithes, gospel ministers, worship, etc.
* His voyage to the West Indies, in 1683

There being sometimes occasion to appeal to the
government in behalf of Friends and truth,
I with others was willing and ready to answer that service;
and the Lord blessed our endeavours, and gave us favour with those in authority.
Truth prospered and meetings increased, yet the priests were still covetous for tithes,
which Friends for conscience sake could not give them, whereupon they suffered greatly.

The afore-mentioned George Clapham, priest, who had been so cruel against us,
the Lord made an example of, depriving him of his natural senses; yet he kept the parish,
and one James Lloyd, as he called himself,
though others said he changed his name for misdemeanours he had committed,
was hired as his curate.
He was a shameless wicked man on several accounts, and very fierce to get tithes from us;
and being somewhat disappointed by Robert Jackson and me,
he put us in the bishop`'s court, had us excommunicated, taken with an order,
and committed to prison in the year 1682, he himself guarding us there.
When we came to the dungeon, where thieves and murderers were kept,
he in a scornful manner told me, there was my lodging.
We were confined prisoners about twenty weeks, and had many precious good meetings,
having the benefit of Friends`' company, who came to see us from most parts of the nation;
few days passed,
but we had the company of honest-hearted Friends from one place or other.

When the Lord`'s time was come, he made way for our liberty, in the following manner:
The lord of Ely, being then our landlord, was concerned for us,
because of our sufferings, and endeavoured with the bishop for our liberty,
who ordered us to come to the court at Kildare.
Accordingly we came, and there were the bishop, and about ten or twelve priests,
the lord of Ely and his steward, with several other persons of account in the world,
and a great concourse of people.
One Dean Sing, was chancellor of the court;
John Burnyeat and Anthony Sharp accompanied me to the court, yet went not in,
but stood at the door, where they could both see and hear us.

The bishop began to discourse with me concerning tithes,
which I was unwilling to enter upon, being sensible of my own weakness; but he urged:
then the Lord by his divine Spirit, gave me wisdom and understanding,
and brought Scriptures into my memory fluently, so that I proved tithes to be ended,
and that it was anti-christian either to pay or receive them in Gospel times,
which was opened so clear to the understandings of the people,
that there seemed to be great satisfaction in the court.
Then Dean Sing stood up before them all, and said,
if he had known me as well before as he did now, I should not have suffered:
with several other expressions of kindness.

We went through many other things, relating to Gospel ministers, Christian religion,
faith, and the true worship of God.
And my understanding was clear, ripe and ready,
through the assistance of the Lord`'s blessed spirit, to answer to matters;
so that they could not resist what I said.
The bishop himself was silent; then I told him I thought my suffering was illegal,
for that the clause in the statute of Henry the VIII,
by which they had proceeded against me, did not take hold of me;
and if a moderate unbiassed judge had the ministering of the law,
he might have found that I was not the man it took hold of.
For the words in that statute are,
that if any man out of a perverse will and ungodly mind, shall detain his tithes,
he shall be so proceeded against.
But as for me, I did not detain tithes out of an ungodly will or perverse mind;
but out of a tender conscience towards God, and could not believe,
that the king and parliament of England intended
that Act against tender conscientious men,
but against ungodly, wilful and perverse men, according to the clause in the Act.
They had not considered that point, and were all silent, only the bishop,
who enjoined me to give him in writing, the exact words of the aforesaid Act,
and also to give him in writing, the reasons why I dissented from the church of England,
saying,
they must not lose such a man as I. They ordered us to appear there at the next court,
and wrote to the sheriff, to let us have our liberty until then, and broke up the court.
Our discourse held full three hours, in a quiet manner without any other business.
When we came out to Friends, who stood at the court door,
John Burnyeat said he was never better satisfied with a day`'s work in all his life,
the testimony of truth being so over them.

We appeared, as ordered, at the next court, and the bishop then would absolve us;
but I told him I could not come under any of their ceremonies,
and we had much discourse about it; at last he bid God make us good Christians,
and wrote to the sheriff to discharge us from prison, which was readily done.
This suffering and conference through the Lord`'s blessing had a good effect.
For since that time,
both the bishop and officers of that court have been kind to Friends,
and particularly to me.

In the year 1683,
I was moved of the Lord to visit Friends in the Caribbee Islands and Jamaica.
So after acquainting several Friends, and they having unity with me in my concern,
also my wife being willing to give me up in the service of truth, as at other times,
I heard of a ship at Cork bound for Barbados, of which Robert Scotten,
a Friend from London, was master, who was glad of my company.
When I received account that the ship was nearly ready to sail,
I took leave of my wife and children, committing all to God,
and took my journey accompanied by several Friends to Cork,
where I took passage in the said ship.
Friends who accompanied me there, stayed some days,
when we parted in the tender love of God,
and in the sweet unity and comfort of his spirit.
In a few days we went to sea, the wind was fair, but soon after a great storm arose,
which continued with us two weeks; and the tackling of our rudder was broken,
and could not be mended for many weeks.
We were hard put to it to sail without a rudder; but the Lord favoured us with a wind,
and we got well to Barbados in about two months.

As soon as we came to anchor, several Friends came aboard, and were glad of my coming.
I went on shore with them, and laboured in the service of truth,
having meetings in every quarter of the island, both for the worship of God,
and discipline, to settle things that were unsettled,
and rectify things which were amiss, as much as in me lay.
Friends were generally subject to Gospel order, and truth`'s government.

After I had been labouring there some months, it was with me to go to the Leeward Islands.
Ralph Fretwell and some other Friends, then going to Pennsylvania,
took me on board their vessel, and put me on shore in Antigua,
and proceeded on their voyage.
I stayed there some time, and had many meetings both for doctrine and discipline,
where there was great need of labourers.
When clear, I took passage from there to Nevis, where were honest tender Friends,
and we were well refreshed in the Lord, and in one another.
I had many sweet comfortable meetings with them, to which also many people came,
among whom were several justices of the peace, who were tendered and confessed to truth.

The chief judge of the island, Simmons, and his wife,
were both convinced and came to several meetings; the report of which went abroad,
and the general, Stapleton, seemed to be offended,
and threatened to banish me out of the island.
But Judge Simmons told him they had reason to bless God for my coming there,
which had brought a blessing to their island.
For before I came, they had not had a plentiful season of rain for three years past;
and since my coming they had been plentifully replenished with rain,
the effect whereof was like to bring them much increase.
So I stayed until I was clear of that service, and left Friends tender and loving.

I took passage back for Antigua, but by contrary winds was put into Mount-serrat,
and stayed there some days, then came to Antigua, and stayed to some meetings;
and taking leave of Friends, sailed for Barbados, and in four or five days landed there.
I was kindly received by Friends, who were glad of my coming back,
to give them another visit.
When I had stayed several meetings, and was often refreshed together with Friends,
I went for Jamaica, accompanied by Henry Currier;
many Friends from several parts of the island came to Bridgetown, where we took shipping,
and there parted from us in the tender love of God, and unity of his blessed spirit.

In about two weeks`' time we landed at Port Royal in Jamaica,
and came to John Willmot`'s house to lodge.
After having a meeting there, we travelled to other parts of the island,
and had many meetings for the worship of God;
also men`'s and women`'s meetings about church affairs,
for the settling of Friends in Gospel order.
There were some things hard to get through,
so that my spirit was bowed down in suffering with the Seed of God,
and under this trouble of mind, the strength of my body failed for some time;
but the Lord by his spirit and power strengthened and raised me up again.
We travelled much,
and had many meetings in several places of the island and went
through several hardships and exercises of various kinds.
After some months`' service in those parts, Henry Currier went from there to Bermudas,
and so to Barbados; but I stayed, being not yet clear,
and had meetings both for the worship of God,
and men`'s and women`'s meetings for settling the affairs of the church in Gospel order,
in which service the Lord stood by me,
and helped me to go on in his work through strong oppositions,
the word of his testimony being over opposers, whereby honest-hearted Friends,
who loved the truth and government thereof, were greatly strengthened and comforted.
I had good service there for the Lord several ways, for about seven months.

Being clear of that service, I took passage for Ireland, in a vessel bound for Cork,
whereof John Benford was master; when we were ready to sail,
several honest Friends went aboard, and took their leave of me in tender love.
In about seven weeks`' time, we landed well at Cork,
and the Province Meeting being at hand, which was then appointed at Limerick,
I went there accompanied by many Friends from Cork, and those parts.
Here my wife and several Friends from Leinster met me; we were joyful in the Lord,
and glad to see one another.
