== Chapter XI

[.chapter-synopsis]
* After his return from America, he faithfully published in many meetings, a remarkable prophecy of the late troubles.
* His several prudent and successful applications to the government, for the relief of distressed Protestants, until 1690.

King James II being newly come to the crown,
people`'s minds were not settled under the government,
and some officers showed themselves busy in disturbing our meetings,
and at that time committed me and several other Friends to the Marshalsea.
But we were soon released,
and kept our meeting during the time appointed for that service,
and the Lord`'s presence being with us.
Friends were well refreshed and comforted therein, and in one another.

1685+++.+++ When the service of that meeting was over,
I went with my wife and Friends from Limerick to my own house, and as way opened,
visited Friends in the north and other places,
duly attending public meetings both for worship and discipline.
Then a weighty sense came upon my spirit, of great exercise and trials approaching,
which would try us all, and that the Lord would spread the carcasses of men on the earth,
as dung.
So in the spirit and power of the Lord,
I faithfully and plainly warned Friends and others of it in many public meetings,
and often in the Lord`'s movings, advised Friends to lessen their concerns in the world,
and be ready to receive the Lord in his judgments, which were at hand,
and to flee unto him for succour, that they might have a place of safety in him.
The like doctrine, admonition and exhortation often, and in many places,
I was moved of the Lord to publish.
So I am a witness, that his care is over his people, that they be not surprised,
but make ready against the day of trial.
And in a short time trouble came on quickly.

The Earl of Tyrconnel, then lord deputy of Ireland,
armed the Irish and disarmed most of the English;
so that great fear came upon the Protestants, most of the great leading men,
and many others, left their places and substance, and went for England,
others of them got into garrisons,
and those who stayed in their dwellings lay open to spoil.
An open war soon broke out, and abundance of the Irish, who went in bands,
but were not of the army, called raparees,
plundered and spoiled many of the English Protestants; also many of the army,
who were under command in troops and companies, were very abusive,
being countenanced by their officers;
so that the Protestants were under great distress many ways,
though the government gave forth several proclamations against such abuses.

We being sharers with many other Protestants in these sufferings,
a concern came upon my mind to appeal to the government,
to redress abuses committed in the country, by some of the army,
particularly one troop at Mount-melick, who were very abusive,
concerning whom I petitioned the Duke of Tyrconnel, who heard my complaint,
and for example to the rest, cashiered the quarter-master,
and ordered two of the troopers, who had done abuses,
to be cashiered and also sent to jail,
and the troop to be immediately removed to another place.
This eased our quarter for a little time.

The quarter-master was very submissive,
and desired me to solicit the duke to restore him to his place; which I did,
and the duke granted it.
This won much upon many of them, and I gained acquaintance at court.
But things grew worse and worse.
A party of Sir Maurice Eustace`'s troop came our road,
and did great abuses to several Protestants in Mount-melick, and thereabout.
Some of them came to my house, and were very rude, taking me by the hair of my head,
and haling me about the yard among their horses feet, without the least provocation;
some of them with clubs, and others with cocked pistols, swearing they would kill me;
which my wife hearing, came out sorely amazed and affrighted,
desiring them to take all we had, and save my life.
Then they left me, and turned after her, swearing and calling bad names;
and shot several times at my mastiff-dog that was chained, and so rode away like mad men,
abusing and beating all the English they met with; and some they almost killed.
In Mount-melick there was a great scuffle, and like to have been worse than it was,
between them and some English, whom they abused.
News went there that I was killed, so they concluded a massacre was intended,
believing I would give them no occasion.
This alarmed and affrighted the Protestants in our parts,
and some ran into woods and bogs, to hide themselves.

The next morning I went to Mount-melick,
where several English Protestants expressed their gladness to see me alive.
The chief men of the English there, who were not fled, were Justice Warnford,
Hopton Harris, etc.
I went to them, they were glad to see me,
but concluded this was a fore-runner of a massacre.
I told them I was of another mind; for it rather appeared to be a contrivance,
to alarm and affright all the English, to make them run for England,
that they might have the country, and all we had to themselves.
I believed they intended no massacre; for if they had,
they would not have given us this alarm.
And if they would manage this matter well, it might make full proof,
for all the English in Ireland to know, whether they intended a massacre or not.
I advised to take full examinations of the abuses, and send some men to Dublin with them,
and petition the government; and by this we should all know what they intended to do.
They assented thereto and liked it well; but said that at this time,
unless I would go and undertake it, none else dared.
I considered the matter,
and understood well that the undertaking was at the hazard of a man`'s life;
yet perceiving it might be the saving of many, I took courage,
and my life was not much to me for the good of my countrymen.
I told them, if Hopton Harris and George Wheatly would go with me, I would undertake it.
They were two noted men in the town, who had been abused by that party;
they considered the matter, and were willing to go.
Then the justice took examinations of the abuses done,
and the next day we took our journey to Dublin, but not the usual road,
lest we should have been way-laid.

When we came to Dublin, I went to the Lord Chief Justice Nugent, who was still my friend,
and acquainted him with the whole matter.
He seemed to take little notice of any abuses but what they had done to me,
and promised to be at the castle such an hour,
and he would assist me in getting to speak to the Duke of Tyrconnel.
So I and the other two went to the castle, where Judge Nugent came, as he promised,
and presently I was called into the duke`'s closet,
but the other two were not permitted to go in.
I told the duke of the abuses done to me, and what troop they belonged to;
he looked with a sour countenance, and said little to it.
Then I spoke of the gross abuses done to my neighbours,
and particularly to those two men that came with me, who were standing without;
but I was stopped, and bid to speak to my own business, and then dismissed.
I went out to my two neighbours,
and told them I well perceived they intended no massacre,
but to affright the rest of the Protestants out of Ireland; however,
I would prosecute this matter to the end, perceiving that they would not hear them;
yet I desired their company, and they were willing to be with me.

We went then to Colonel Russel,
who was colonel of the regiment to which those troopers belonged,
and told him of the abuses, and how the English were affrighted.
He seemed to be much concerned, and said if such were not made an example,
it was time for everyone to look to himself, but he would go to the duke,
and lay it home to him.
This Colonel Russel went soon after for England.
We went to the lord Granard, who was then lieutenant-general,
and acquainted him with the affright the country was in upon this occasion.
He was much concerned and dejected in his mind, and said he was general, and no general;
but he would go to the duke and lay it close to him.
We were also with the lord Mountjoy,
and several other persons of note among the Protestants.

The noise thereof spread, and the duke sent that evening,
and said we had made a great noise in the city,
and he would know if we had witnesses ready.
I said we could have a hundred, and more if need were.
He ordered us to be at the lord Chief Justice Nugent`'s next morning at eight o`'clock;
also the captain and troopers were ordered to be there, to have the matter examined.
We came at the hour appointed; the captain,
Sir Maurice Eustace and the troopers were there, and examined, but all denied the fact;
then Judge Nugent asked me, if I knew any of those who abused me.
I challenged one, and he confessed; then the officer, who was with the party,
was put to discover the rest, which he did: so they were disarmed,
and sent to the jail at Maryborough.
The two neighbours who were with me speaking of the abuses done to them,
the judge checked them for making some small
resistance in their own defence at Mount-melick.
Having seen what they aimed at, we went home.

The troopers who were committed, came soon after to Mount-melick,
by the sheriff and jailer`'s leave; one of them came to my house, to ask me forgiveness,
and said they would make me what satisfaction I pleased.
Then I went to Mount-melick where the rest were, both the abusers and abused,
and discoursed privately with justice Warnford,
showing him that we had got all we were likely to have; for we saw how things wrought,
and it was best to forgive them, otherwise we should get nothing but their hatred,
and perhaps a worse mischief than we had gotten already.
Some were against it, but I went out to the soldiers,
and told them I hoped this would be a warning to them, to be civil for the future;
and so forgave them what they had done to me,
wishing them to satisfy the rest whom they had abused.
They begged me to write by them to the lord Chief Justice Nugent,
to give them their horses and arms, for they bought them; which I did,
and they were very thankful,
and promised to be kind to my Friends wherever they met with them.
They had their horses and arms restored.
Soon after this same troop came into our quarter,
to take horses and arms from the Protestants, the captain alighted at my house,
and was very courteous, promising to do what kindness in him lay for any of my Friends;
notwithstanding which they generally took Friends`' horses, as well as others.

Trials and great exercises increased daily,
most of the eminent leading men of the English Protestants were gone,
and those who stayed were discouraged from appealing to
the government for the preservation of the country.
Things looked with a face of ruin and destruction; through a sight and sense of which,
a concern came upon me to appeal to the government in behalf of the Protestants,
and in particular for Friends.
I was often at Dublin, and used what interest I had with the government,
for the public good.
The Irish army were marching to the north against the Protestants there in arms,
and I was much concerned with some Friends in Dublin,
to use all our interest with the chief officers,
to spare and be kind to our Friends in the north, for they were not in arms;
and many of them promised they would, and performed their promises.

1689+++.+++ Calamity increased; the raparees on one hand,
plundered and spoiled many of the English,
and on the other hand the army marching and quartering, took what they pleased from us;
and our families were their servants, to make what we had ready for them;
and it looked like a sudden famine, there was such great destruction.
I considered the way to prolong time,
that the English might eat part of their own substance,
was to get a guard of Irish soldiers in that quarter, which lay open to all mischief.
So I went to Dublin, and got an order from the Duke of Tyrconnel,
for one captain Francis Dunn and his company to stay
with us and protect that quarter against thieves,
raparees, and other violences.
This put a little stop to plundering in our quarter,
which sorely vexed the plunderers and thieves.
Then some evil-minded officers got this captain Dunn removed,
and he marched nearly forty miles; but King James being then come into the nation,
another Friend and I procured his order to bring him back again;
yet they were not quiet until he was again removed,
and then the Protestants went fast to wreck in their substance.

In those times I was much at Dublin, applying to the government in behalf of the country,
for the Lord had given Friends favour with the government,
and they would hear my complaint,
and gave forth several orders to magistrates and officers of the army,
to suppress raparees and restrain their abuses, and they stood a little in awe of me,
for they knew I had an interest with the government.
I was sometimes with King James,
and told him of the calamity the Protestants were under in the country,
and he would hear me quietly, for the Lord made way in their hearts for us,
against such a time of great exercise and trial,
and I had a concern upon me to make use of it for the public good,
the chief of the English Protestants being gone,
who might have applied to the government for the safety of the country.
