== Section XX.

In 1701 he visits the north of England; in about two months time returns,
and writes to R. T. an excellent dissuasive letter
against the too eager pursuit after the gain,
pleasure, and great things of this life.

Finding myself stronger and better in health, through the Lord`'s power which healed me,
I laid my intention of going for England before the elders and brethren,
who gave their free consent.
George Rooke, Thomas Pearce and Jacob Fuller accompanied me for England,
intending to go to London to the Yearly Meeting.
We took shipping at Dublin, on the 16th day of the month aforesaid,
and many Friends accompanied us to the water-side,
where we parted in a sweet tender frame, and in the comfort of God`'s love.
We had an easy smooth passage, and in about thirty-two hours landed at Nesson;
then rode to Chester, and at Friends`' meeting there, I felt something of opposition,
which after the meeting, appeared in the high floating spirit of one,
who could not bear reproof,
and who afterwards was disowned by Friends for disorderly conduct.

We rode to John Merrick`'s, and it being a very wet day, I got a great cold;
we went however, to Middlewich in Cheshire, to Friends`' meeting,
it being the first-day of the week and 18th of the third month.
In the latter part of the meeting I was seized with great illness, and pain over my body,
and was forced to stay at the house of our Friend, William Hancock, five days,
where they were very kind and tender to me.
Here by mutual consent,
George Rooke and Jacob Fuller went on their journey towards London,
to the Yearly Meeting, and Thomas Pearce stayed.
I was not able to travel with them,
and besides was stopped in my spirit from going to London.

When I was able I went northwards, as the way most clearly opened to me,
accompanied by Thomas Pearce.
We came to Penketh in Lancashire, and were at Friends`' meeting on first-day,
where the Lord enabled me to open many mysteries of Christ`'s kingdom and government,
in the demonstration of the spirit and power of God,
who gave me strength over my weakness, and we were well refreshed in the Lord.
Many Friends came to see me, and we were glad of each other.

From there we went to John Haydock`'s, and stayed there two nights,
where unexpectedly we met with John Bousted, Robert Atkinson,
Peter Fearon and several others going to the Yearly Meeting at London.
We were glad and comforted to see one another;
but they seemed to be much concerned and troubled,
that they could not have my company to London.
Thomas Pearce and I rode to Lancaster, and stayed there one night,
and had a meeting with Friends; also visited Friends who were in prison in the castle,
for not paying tithes to the priests.
Next day we rode to Swarthmore to see Margaret Fox, who was then weak in body.

We abode there three nights, and were at their meeting on first-day,
and the Lord`'s power was with us to our great comfort; then rode to Kendal,
several Friends of Swarthmore going with us.
The next day we got to Camsgill, and stayed at Thomas Cam`'s three nights,
and were with them at their meeting.
From there we went to Kendal, to the Monthly Meeting of men and women,
for church affairs, and many things were largely opened to them on that account,
which seemed to afford great satisfaction and comfort to many.

Then we rode home with John Bleakling, and next morning into Ravenstonedale,
accompanied by many Friends, where we had a large meeting out of doors, many came to it,
both Friends and others from several places, being on a first-day of the week,
and the Lord strengthened me to declare the word of life, which reached many hearts.
We rode back to Sedberg General Meeting, where many Friends came, both of Yorkshire,
Lancashire and Westmoreland, and a powerful heavenly meeting it was;
many hearts were tendered, and weighty things in the Lord`'s power were opened,
relating both to doctrine and Gospel order;
the Lord having strengthened and healed me of my illness.
From there we went to Kirby-Stephen, where I met with Lancelot Lancaster,
my old acquaintance of Little-Musgrove, the place where I was born.

I had a desire to have a meeting there,
and asked him if he could accommodate us with a place to meet in;
who cheerfully replied he would do it.
I rode in company with Thomas Pearce to Little-Musgrove,
where the people showed their gladness to see me;
and I gave them notice of having a meeting there on the first-day following,
none having been held there by the people called Quakers.
They seemed very willing and ready to further our views; so we rode on to Appleby,
and lodged that night at the jailer`'s, who kept an inn,
two Friends being prisoners there for some priest`'s demands.
The next day we rode to Strickland-head, and had a meeting there with Friends;
here Anthony Robinson came to us, he being newly arrived from Ireland.

Next day we came to Little-Musgrove, where my old neighbour, Lancelot Lancaster,
his wife and children, received us with great expression of love and kindness.
We lodged there that night, and the next day had a great meeting in a large barn.
Many came to it from several towns and places thereabout,
and the doctrine of Christ`'s kingdom was largely and powerfully declared;
the people seemed to be well satisfied,
and expressed the same after the meeting with words of great kindness.
Their hearts were open for more meetings,
but that evening we rode to Blue-grass on Stain-moor, and lodged at a kinswoman`'s house,
who was glad to see me, and desirous to have a meeting at her house.

The next day I rode to Cudderston in Yorkshire,
accompanied by Thomas Pearce and Anthony Robinson,
and on the day following was at Friends`' meeting at Lartinton,
where things were opened in the testimony of truth for Friends`' benefit,
and we parted in a sense of the great love of God.
After the meeting we rode to Raby, where I lodged at Jane Vickridge`'s house,
and stayed a meeting with Friends, to which several who belonged to other meetings came,
and we were well refreshed in the Lord and one in another.
Next morning we parted in a sweet sense of the love of God, and that day rode to Durham,
and lodged at an inn.

The day following went to Newcastle, and next day being the first of the week,
we were at two meetings there;
the testimony of truth in the Lord`'s power was delivered
suitable to the states and conditions of the people.
On the day following rode to Sunderland and stayed one meeting with Friends;
after which we rode to John Hall`'s, and next day he went with us to Stockton,
and on the day following we had a fresh comfortable meeting there.
Next day we rode to Darlington, and on the day following being first-day,
we had two meetings with Friends to our mutual comfort.

The next morning early we took our journey towards York, and Robert Trueman,
at whose house we lodged in Darlington, went with us and stayed to the Quarterly Meeting.
We arrived there in two days, and on the next morning the Quarterly Meeting began,
being the 2nd day of the fifth month, 1701.
It was very large, and held two days.
Here we met with George Rooke and Jacob Fuller, our fellow travellers out of Ireland,
and were glad to see one another.
When the service of this meeting was over, George Rooke, Thomas Pearce and I,
in company of many Friends rode to Knaresborough,
and had a meeting in the tollbooth or market-house,
and many of the town`'s people came to it;
the doctrine of Christ`'s kingdom and the mystery of faith were largely opened,
and the meeting ended well: so we parted in peace.

After this we went to Friends`' meeting at Massam, which was full,
it being on a first-day of the week.
We then went to a meeting we had appointed before, at Kirby-Stephen,
which we held in a large barn belonging to the inn; many people came,
and the testimony of truth was over all--several seemed to be reached,
and we were well satisfied in our labour of love.

Next morning we rode to Crosby-Garret, and that day had a satisfactory meeting there,
with sober people, in a barn belonging to an ale-house;
and they seemed to be affected and well satisfied with what was declared.
After the meeting we rode to Brough, under Stainmoor; and lodging that night at an inn,
had a meeting there next day in a barn--several people came who heard the Word declared,
and were quiet; but seemed to be a harder people than they at Crosby the day before.

We rode to Blue-grass on Stainmoor, and had a very thronged meeting,
it being on a first-day of the week; and the doctrine of Christ`'s kingdom,
the mystery of faith and way of salvation were largely opened to them;
and many seemed to be affected with what was declared, and were tender,
friendly and loving.
After this meeting we parted in peace and love, and rode to Great-Musgrove,
having appointed a meeting there that afternoon-- one
Thomas Waller having promised me his barn to meet in;
but the priest hearing of it, sent his wardens to charge him,
that he should not let us meet there.
So we had the meeting on a green in the middle of the town; the people came to it,
and were very sober and solid, parting lovingly like friends.
Being clear of that quarter, we took leave of Friends and rode to Warcop,
and lodged at an inn: here Thomas Pearce was taken ill,
and we stayed part of the next day; but he being willing to remove from there,
we took horse and rode to Strickland-head, and the next day to George Bewley`'s.

The day following we went to Friends`' meeting near William Greenup`'s;
and the next day we were at Friends`' meeting at Pardsey-crag;
and on the day following at Broughton.
Friends had appointed a meeting for us at Boulton on the first-day following,
George Rooke having gone before to see his relations,
and to give notice of the said meeting, which was large and full; many came to it,
both Friends and others, and it was a glorious meeting.

The next day we went to Broughton again,
where Friends had appointed a meeting for as many
Friends in the county as were willing to come,
and had a concern for church discipline and Gospel order, both men and women,
they being desirous to have an opportunity with us before we left the nation.
Notice was given through the county, and many concerned Friends came, both men and women,
and the Lord`'s ancient goodness was with us in that meeting,
where many things relating to church discipline and Gospel order were closely spoken to;
and we were comforted together, and parted in the love of God and tenderness of spirit.

After the meeting we rode to Whitehaven, in order to take shipping for Ireland,
several Friends going with us; and near the middle of the day we went aboard,
and put to sea; but the wind being contrary, were near four days and three nights at sea;
but arrived safe at Dublin on the 26th day of the fifth month, 1701,
it being the seventh-day of the week.
Next day I stayed at Dublin two meetings, and that evening several Friends,
who heard of our landing, came to Dublin from Wicklow,
where they had been at the Province Meeting.

The next morning I left Dublin and came home, and found things well;
blessed be the Lord for his mercies and goodness.
Soon after, in company with my wife, I went to see our relations at Ballynolert,
in the county of Kildare, and stayed one meeting with them, and so returned home;
then went to a meeting at Ballyboy, to which many pious, sober people came,
and the Lord`'s power was with us, in which the Gospel was preached,
and the people seemed to be well satisfied.
From there we went to Birr, and had a meeting; and then rode home.
I wrote a letter in the openings of truth, directed to Robert Trueman at Darlington,
in Bishoprick, as an admonition to him and others, as follows:

My Friend, R. T.

The remembrance of you and your tender wife, in true love, causes these few lines,
chiefly to renew your memory, to perform the contents of your own letter,
written to me some time ago,
to give me an account of the ease and peace you found in your practice,
relating to the lawful things of this world;
and you know what my friendly admonition in the love of truth was,
when I parted with you in York, that you might perform in deeds,
what you had said in words.
And now, dear Robert, I know that the eagerness after the lawful things of this world,
at this time hinders the growth of many Friends in the precious truth,
and their service to it,
though otherwise of great abilities to do much service for truth on many accounts,
as instruments in the hand of God.
But we cannot serve God as we ought to do, and as the day requires,
neither please the Captain of our spiritual warfare, as good soldiers,
if we involve and load ourselves with the things of this world.
This is the great failure and stumbling-block at this day,
and too many of our Society are hurt thereby, who have in measure escaped the unclean,
unjust and unlawful things of this world,
and washed their garments from the spots thereof; and bear the name of virgins,
and now sit down in the dust, in the lawful things of this world,
without a due regard to the right use and service of them in the creation,
and to the bounds and limits of truth in getting and using them,
in their places and services.
Thus as the foolish virgins,
they lack the oil that would make their lamps burn with a holy fragrant smell,
according to divine knowledge,
for the promotion of the Lord`'s blessed truth on all accounts;
and would make their lights shine, in which the service of the day would be clearly seen,
and the glory of the Lord arise more and more,
to discover all things that are offensive and must be cast out.
On this account great danger does appear, that many, like the foolish virgins,
will be shut out of the Bridegroom`'s chamber, when those that are ready,
who have shaken themselves from the dust, and put on the beautiful garments,
who have oil in their lamps, and rise in the brightness of this glorious day of the Lord,
having their affections set on things that are above, where Christ is,
and not on things that be upon the earth,
will enter with Christ into the wedding chamber.
Now, my friend, I would not burden you with words,
but my heart is open in true love to you and yours;
and I certainly know the enemy of mankind is working in a mysterious way,
to overthrow many who have had their faces Zionwards, now to look back to the gain,
profit and pleasure in those things that are soon gone,
and of which a little will serve in their right use with a contented mind.
I can do no less but give notice of it, that you and others may escape his snares,
and cast off those burdens in this easy Gospel sabbath-day,
and cheerfully run the race in the service of God and their generation,
according to the ability and gift received in their station and place.

I could say much on this subject, but shall cut short, and leave the issue to the Lord,
who is raising his holy Seed,
that will bruise the head of the serpent in this evil purpose,
as well as in other things, that he has made head in,
to hinder the Lord`'s people in their progress towards his holy rest,
that God has prepared for them that love him.
Many have fallen short of that rest in such times of temptation; and it is to be feared,
some of the stars of this day, may fall in this temptation,
and presentation of the glorious things of this world that perish.
I conclude, with bowels of true love to you, and your well-meaning tender wife.
After our parting from York, we had service in that county, and in Westmoreland,
and in Cumberland, both with Friends and others in several places,
which I hope will not always lie buried, or return empty,
without some fruits to the praise of God, and profit of men.
When we were clear of that service, we shipped at Whitehaven for Ireland,
and after four days at sea, landed safe and well at Dublin; and, in the main,
things are well with Friends in this nation,
and a right concern on many for truth`'s prosperity in
its holy comely order and discipline;
which the Lord makes to prosper in the hands of his faithful servants,
to the great satisfaction and comfort of many;
and there is great openness in many places, and little or no opposition.
The remembrance of my love is to honest Friends at Rayby,
who are concerned for good order in the church of Christ; to Jane Vickers, and the rest,
and to her Friends at Stockton, where I lodged, and to John Hall,
and to all such as afore-mentioned, as if I named them.
I know there are a few names in that county who have a true regard to God`'s honour,
and would have things well in his house; but see that many things need reforming,
which is their trouble; and with such my spirit travails.
When you see William Ellis, tell him that his ancient friend in the love of truth,
advises him to take heed that the topping spirit after the things aforementioned,
do not hurt him unaware; which is my best love to him.

William Edmundson
