== Chapter XXI

[.chapter-synopsis]
* Visits Ulster, and several places in Connaught, where none of our meetings had been
* Obstructed at Abby-boyle by the burgomaster

Our next Quarterly Provincial Meeting being at Catherlough, I went there:
the service of that meeting held part of three days, for the worship of God,
and ordering affairs in the church of Christ.
When it was over I went home, and that week took my journey to the Province of Ulster,
and so into Connaught in the service of truth,
accompanied by Joshua Beale and Richard Guy.
On the first-day of the week, we had a full and satisfactory meeting at Abbylary,
where no meeting of our Society had been; many goodly people came to it,
and the Lord`'s power was with us, in which the mysteries of his kingdom were preached,
and the way of life and salvation opened.
The people were very attentive and tender.

After the meeting we rode to Cavan, and the next day beyond Ballyhayes,
and had a meeting with Friends there.
Several people came to it, and many weighty Gospel truths were delivered,
suitable to the people`'s condition, and the service of the day;
next day we rode to Ballyhagan, in the county of Armagh,
and had a comfortable meeting with Friends;
after which we rode to Richard Boyes`'s in the county of Antrim,
where the Quarterly Meeting for Ulster was held,
part of three days for the worship of God and discipline of his church:
the mighty power of God was with his testimony, which broke through all,
and wrought into a tender submission thereto.

We went back to Lurgan, and had a large meeting of Friends and others,
where many precious things relating to Christ`'s kingdom
and government were opened in the power of truth,
suitable to the states and conditions of the people.
The next day we went to Grange, and on the day following had a meeting with Friends,
and were refreshed together in the Lord.
The following day to Donclaudy, and had a meeting;
and next morning we rode through the mountains to Dungivin,
and had a meeting there that day.

The day following we came to Colerain, and on first-day had a full meeting,
where the word of truth was powerfully preached,
and God`'s witness reached in many consciences, so that many were comforted and refreshed.
After this we rode to Castlefin, in the county of Donnegal,
and had a meeting where none had been before: the people were attentive and sober.

At Newtonstewart we had a thronged meeting;
and on the day following travelled through the mountains, over a rough bad road,
and lodged at Petticoe, in the county of Farmannagh, expecting to get a meeting there,
but were disappointed, and had poor entertainment.
Next day we rode to Balleek,
and it being a very stormy day with exceedingly high wind and hail in our faces,
and a bad road, both we and our horses were sorely foiled, and I got a cold;
yet in the evening we had a satisfactory meeting which helped us,
and repaired our hard day`'s work.
Several, both Protestants and Papists, were there; also a Papist priest,
and truth`'s testimony was over them all, without opposition,
to our comfort and satisfaction.
The next day we rode to Ballyshannon, in the county of Donnegal,
and on the first-day of the week, had two meetings,
the people of the town were very attentive and sober,
although in these two places last mentioned,
no meetings of our Society had been held before.
Then we went to Sligo, and lodged two nights, and had a full meeting there.
From there to Abbyboyle, in the county of Roscommon, and would have had a meeting there,
but the burgomaster would not allow us, and hindered the people.
I told him that we were servants of the living God,
and came to call the people to repentance; and inasmuch as he obstructed our service,
I charged the sins of the people upon him; whereat he trembled: so I left him.

We rode to Carrickdrumroosk,
where some of our company sought for a convenient place to have a meeting,
and the steward to sir George St. George, granted us the session house to meet in;
but afterwards the priest of the town, with two more, dissuaded him from it:
so that when we went there, and many people had gathered to have a meeting,
the steward told Friends he could not let us have it.
Returning to the inn where we lodged, the sober people went along with us,
and the woman of the inn willingly granted us a large dining-room to meet in,
and we had a sweet comfortable meeting;
the mysteries of Christ`'s kingdom were freely declared,
and the way of life and salvation largely and plainly opened,
and the hearts of the people were open and tender.
The next morning we rose early, and travelling hard,
got to Jacob Fuller`'s about two hours within night; I was very weary,
but rested there the next day.

On the following first-day, we had a meeting at Kinagh, where none had been before;
so came back again that night to Jacob Fuller`'s,
and on third-day had a meeting with Friends, on fourth-day one at the Moat,
on fifth-day one at Lismoiney, and on the sixth-day went again to the Moat,
where I met my wife and several Friends, who came to the Province Meeting,
which began there the next day.
When it was over, I went home with my wife, and kept to meetings as they came in course.
