== Section XXII.

Goes to the Half-yearns Meeting at Dublin; is nominated to go over to London;
but being weakly, and unable to perform that journey, he writes an epistle to Friends.

On the 8th day of the ninth month following, our National Meeting began at Dublin,
as usual; where was a large appearance of Friends from several parts of the nation,
and great numbers of others thronged to our meeting for the worship of God,
and much service there was.
It lasted part of four days, and was carried on in peace and concord,
in the wisdom of God, which was with brethren and elders,
in managing the affairs of truth, both for doctrine and church discipline,
and ended in great peace, to the praise of God and comfort of Friends.

When this great meeting was over, I returned home.
Winter being come, and my old age not able to endure much cold or hard travel,
I attended the service of meetings near home,
and in the tenth month our Province Six-week`'s Meeting
being at Lamb`'s Town in the county of Wexford,
I had some drawings upon my spirit there, to which I went,
and had good service on several accounts, the Lord`'s goodness being with us,
which crowned our service with success and great comfort.

Not long after this, there came a letter from one of our correspondents at London,
signifying that Friends there were soliciting the parliament
to get an amendment of the act of the Solemn Affirmation,
so called,
and that some Friends of Ireland were desired to go over to assist in that service,
according to agreement formerly made at the Yearly Meeting at London;
and I being one nominated to go on that service, rode to Dublin, where, in a few days,
most of the Friends from Ulster and Munster, appointed for that service, came up.

We had several sweet comfortable meetings in that city,
both for the worship of God and conference in matters relating to faith and principle;
in which meetings, things were opened to edification and comfort.
My going there was of good service, and acceptable to Friends,
we being sweetly comforted together;
but my ancient decaying body not being able to
perform that journey by sea and land to London,
in cold wet winter weather, I wrote an epistle to Friends of London,
and enclosed it in a letter to our correspondents there.

When I had done what service I could in the afore-mentioned business,
I parted with Friends in the overflowings of the love of God, which filled our hearts,
in which we supplicated his holy name in great tenderness and brokenness of spirit.
After which I returned home, and kept to our usual meetings,
observing the time and service of our Monthly and Provincial Meetings,
as they came in course.
