== Chapter XXVI.

[.chapter-synopsis]
* In 1705, he visits the province of Ulster, accompanied by George Rooke
* In 1706, visits several places, where people were desirous to hear the testimony of truth
* Meets with abuse at Roscrea
* Visits Leinster Province Meeting, and the county of Tipperary, in company with Thomas Wilson

Some time after I left Dublin, and returned home,
it pleased the Lord to heal me so that I was very healthy,
only weak of body by reason of old age and hardships, that I had endured in my travels.
I kept to meetings near us, and was at Dublin at the National Meeting in the third month,
1705.
From there I went to the Province Meeting at Wicklow, for Leinster,
and returned to Dublin again, where I stayed one meeting,
after which I rode to James Ashton`'s, about eight miles.
He was lying sick, and we had a comfortable meeting there,
the Lord`'s power and spirit being with us;
several Friends from Dublin were at that meeting, and we were well refreshed in the Lord;
from there I went home.

In the sixth month following I had drawings in my spirit
to visit Friends`' meetings in the north of Ireland;
so in faith, that the Lord would give me strength to perform it, I took my journey,
and George Rooke from Dublin met me at John Barcroft`'s.
We travelled together in the service of truth,
and went to the Province Meeting for Ulster, in the county of Armagh,
which held part of three days in the worship of God and church discipline,
and had good service for the Lord and his people.
We visited Friends`' meetings through that province to Colerain,
and had large and good meetings, and many heavenly mysteries,
in the life and power of the Gospel of Christ Jesus,
were opened to Friends and others who came to meetings,
to hear the way of truth declaimed.

I was made strong in the Lord`'s power to perform that service;
elders and brethren were glad of the visit, and Friends well comforted.
When we had performed that service, we returned homeward, and came to Navan,
where we lodged at an inn,
and purposed the next morning to have parted in the love of God,
in which we travelled together in the Lord`'s service;
but being taken very ill that night,
my companion would not leave me until I was something easier.

Then we rode together about two miles on my way homewards,
where we met with John Barcroft and Eleazer Sheldon coming to meet us,
they having heard of our returning that way.
When we came to a road that turned to Dublin, we took leave of George Rooke,
who went home, and I, with the other Friends, rode to John Barcroft`'s,
and lodged there that night, and the next day to my son-in-law Eleazer Sheldon`'s,
and on the day following came to my own house,
the Lord having enabled me by his mighty power, which was with us,
to perform this journey of about three hundred miles in old age;
everlasting praise to his great name.
Amen.

I frequented meetings near home, weekly and monthly, as they fell in course;
and Leinster Province Quarterly Meeting being at Castledermot, I went to it,
and had good service for the blessed truth,
in the openings of the spirit of life in Christ Jesus and the power of God.
That meeting held part of three days, as usual; and when it was over I went home,
and soon after to Dublin, to our National Half-year`'s Meeting,
where were Friends from several parts of the nation,
and accounts were given to the meeting of the prosperity of truth,
and preservation of Friends therein;
and matters relating to Gospel order in the church of Christ
were closely discoursed in several needful points.
I was brought under great exercise of spirit, by reason of opposers;
but the Lord`'s power went over all opposition, in which I was comforted,
and praised God, who is blessed forever.
When the service of that meeting was over, I returned home.

Winter coming on,
and my old decayed body not being able to endure cold and hardship in travel,
I kept to meetings near home, until the following spring;
then Leinster Province Meeting being at Catherlough, I went there,
and six weeks after was at our Quarterly Meeting for Leinster, at Castledermot,
in the second month, 1706.
There was a great appearance of Friends from several parts of the province,
and accounts were given of the care of elders and concerned Friends,
in every Monthly Meeting in the province,
that all who frequented our religious assemblies, and professed the truth,
might walk orderly in all respects, as becomes true Christians;
also accounts were given of great openness and desires in many people to have meetings,
to hear truth`'s testimony declared in several places, where our Friends had no meetings;
therefore Friends and brethren, who had public testimonies in the ministry of the Gospel,
were encouraged to visit such places,
that those good desires in people might be answered.

When the service of that meeting was over,
I returned home in the company of George Rooke,
we having determined to go and visit a quarter,
where people were desirous to hear the testimony of truth declared;
and after staying one meeting with Friends at Mountmellick, we went to Mountrath,
and had a meeting there with Friends, and from there to Knockballymagher,
and had one there.
We then proceeded on our journey from among Friends, and came to Roscrea,
where the people were willing and ready to let us have a convenient place to meet in,
and many came to the meeting; but Dominick Mead, an arch-deacon, so called,
and justice of the peace, was enraged against us and very abusive,
not only with his tongue, but also with his hands;
yet Friends`' patience and wise conduct in the authority of the blessed truth,
prevailed over him; so that we got two meetings,
for publishing the Gospel of our Lord and Saviour Jesus Christ,
which were to our satisfaction.

Next day being the first-day of the week, we had a meeting some miles from there,
where a noted man was willing to let us meet in his house,
and a great gathering of goodly people came to hear truth declared.
On the day following we had another meeting some miles distant from there,
and several sober people came to it, who were attentive to hear the free Gospel preached,
and seemed to be well satisfied with what they heard declared.
From there we went to Birr, and stayed a meeting with Friends,
and afterwards came to my house.
In all these meetings the Lord`'s good spirit and power
strengthened and gave us wisdom to divide the Gospel,
and open the mysteries of the kingdom of Christ, to the understandings of the people.

The next day being our meeting at Mountmellick, George Rooke stayed with us,
and then we parted in the love of God.
Our National Half-year`'s Meeting beginning at Dublin
the 8th day of the third month following,
I took my journey there, with my wife and several others,
where was a great appearance of Friends from several parts of the nation,
and good accounts brought of Friends`' godly care
for the preservation one of another in Gospel order.
The Lord`'s mighty power was with us to our great comfort and refreshment,
whose good spirit gave us wisdom and utterance, both in doctrine and discipline.
The service of this meeting held three days in the
public worship of God and church affairs;
and when it was over I returned home.

Our Province Six-weeks`' Meeting being at the Moat, I found a concern to go there,
where was a large number of Friends and others,
and the Lord`'s refreshing goodness was with us,
to our great comfort and encouragement in this religious duty.
The meeting held part of two days in public worship and discipline;
when it was over I went home, and kept to meetings as usual,
and soon after went to Knockballymagher in the county of Tipperary,
and was at the burial of a daughter of James Hutchinson;
and many Friends and others being there,
I had good service among them in the testimony of
the Gospel of the kingdom of Jesus Christ;
so returned home in the company of my wife and other Friends.

Some time after, our Province Meeting for Leinster being held by appointment at Athy,
I went there, and when it was over returned homeward with my wife,
and soon after I visited Friends at the Moat and thereaway,
and had four comfortable meetings.
From there I rode to Thomas Wilson`'s, and stayed two nights,
and had a large meeting at Edenderry, the Lord`'s blessed power being with us,
and enlarging our hearts in the mystery of the doctrine of his kingdom to our comfort.
From there I went to Ballynolert, and had a meeting with Friends there,
and then returned to my own house.

Soon after this I went to our Quarterly Province Meeting at Castledermot,
which held part of three days; and when it was over,
I took a journey to the counties of Wicklow and Wexford,
and had a meeting at Ballynaclash, and another at Wicklow.
From there I went to William Eves`'s, where George Rooke came to me;
and the next day being the first-day of the week,
we were with Friends at their Monthly Meeting at Ballycane,
and the Lord`'s presence was with us to Friends`' comfort and refreshment.

From there we went to Clones, and next day to Israel Webster`'s;
and the day following to Thomas Stephens`'s, and had a meeting in each place;
from there to Enniscorthy, and lodged at Jacob Lary`'s, and the next day to Lamb`'s-town,
where we had a full meeting; after which we returned to Enniscorthy,
and the next day went to John Fred`'s and had a large meeting in a barn,
it being the first-day of the week.

That evening we went to Robert Lackey`'s, where we had a powerful meeting,
the high sheriff of the county and several others being there,
who afterwards expressed their satisfaction concerning the truth of the doctrine declared,
in the demonstration of the spirit and power of our Lord and Saviour Jesus Christ.
From there we went to Athy and had a meeting the next day; after which we parted,
the Lord having enabled me to perform this travel and service,
by the assistance of his customary goodness, in the eightieth year of my age;
praises to his great name forever and ever.
Amen.

The time of our National Meeting at Dublin being at hand, I went there,
where the Lord`'s power was plentifully manifested in our meetings,
both for the public worship of God and those for discipline,
and keeping up good order in the church of Christ.
Many heavenly mysteries of faith were opened in the
spirit and power of the Lord Jesus Christ;
also the affairs of truth were managed with peace and concord,
in the sense and guidance of the holy Spirit of truth,
and Friends and brethren were sweetly comforted and edified in the love of God:
so parting therein we returned to our several habitations; praises to the Lord forever,
who enabled me to hold out in this journey and service,
and is a present help to them that fear him.

1707+++.+++ Winter coming on, and my decaying body not being able to endure much hardship,
I kept to our usual meetings at Mountmellick, weekly and monthly; and in the first month,
the season being temperate, I rode to Dunlavin, and had a large meeting there,
to which many sober people came.
From there I went to Castledermot, to our Quarterly Meeting for Leinster province,
where many Friends met, and were well refreshed in the Lord Jesus Christ.
That meeting held part of three days,
and the week following Thomas Wilson met me at Birr by appointment;
we stayed one meeting there with Friends, and then went to the county of Tipperary,
where several sober people were desirous to hear truth declared,
and willing to let us meet at their houses; we had two meetings with them,
and then came to James Hutchinson`'s, where we had a large meeting on a first-day.
From there we went to Mountrath, and stayed a meeting there, and so returned home.
