== Chapter XXVII.

[.chapter-synopsis]
* Friends`' care over William Edmundson`'s wife in her sickness
* He and G. Rooke visit most of the three provinces of Ulster, Leinster and Munster

Our National Half-year`'s Meeting at Dublin drawing near, I went there with my wife.
There was a great assemblage of Friends from several parts of the nation,
and accounts were given of truth`'s prosperity, and of Friends`' care in every province,
for the welfare of the churches; the Lord`'s ancient goodness was with us,
and his holy Spirit gave ability in his service, both in doctrine and discipline;
but my spirit was deeply affected with sorrow,
in that most of our elders were taken away from us,
who used to attend the service of such meetings.
This meeting held part of four days; when it was over we returned home,
I being much disabled in body by a great cold and old age,
also my tender wife was taken sick on the road; yet the Lord enabled us to get home;
everlasting praises to his great name for all his manifold mercies!

When I had rested two or three days, I was pretty well again;
but my wife`'s illness increased upon her, so that she took her bed,
and lay very sick nearly three months, being so weak and worn away,
that she could not turn or help herself, but as she was assisted.
Many Friends came to visit her from various places,
and several women Friends of Mountmellick were very kind and careful of her,
two of them at a time attending her day and night for the most part, when,
according to appearance, there was little likelihood of her recovery.
Yet I often prayed earnestly and fervently to the Lord,
that he would be pleased to heal and restore her to me, as a helpmate in my old age;
and he was graciously pleased to answer my petition,
as he had at many other times in great straits, and raised her from her illness;
blessed be his worthy name forevermore!
When she was a little recovered, I went to the Moat,
and visited Friends`' meetings thereaway; so returned home,
and found my wife much recovered.

Soon after, Leinster Quarterly Meeting being at Castledermot, I went there,
and some Friends were there from each Monthly Meeting in the province,
who brought accounts of the state of each meeting,
and how the testimony of truth was kept up.
When the meeting was over I went with my fellow-labourer, George Rooke,
to John Watson`'s, and the next day to Waterford,
and on the day following had a meeting there with Friends and others,
and had good service for truth.

Next day we rode to Clonmel, and on the day following had a meeting in their meetinghouse.
After this we went to Knockgraffen, and lodged at Peter Cook`'s house,
and next morning to Tipperary, and had a meeting that day,
to which several sober people came, and were very attentive to what was declared,
in the spirit and power of our Lord Jesus Christ, and went away well satisfied;
also Friends were well refreshed in the Lord.

The next day we went to Limerick, and on the day following, being first-day of the week,
had two meetings in Friends`' meetinghouse there;
and on third-day we had a meeting at Six-miles-bridge, in the county of Clare,
which was large: many men of account came to it--three justices of the peace,
one of them was the priest of that parish,
and all were very sober and attentive to hear truth declared;
the Gospel was preached to them in the demonstration of the spirit and power of God,
and many deep mysteries of the kingdom of Christ Jesus were opened,
which seemed to make an impression on many of them.

After the meeting was over, we went to the inn where we had left our horses,
and the aforesaid priest, who was a justice of the peace, came there to us,
and very courteously offered his kindness in what he could do.
From there we came back to Limerick,
and that evening had a meeting with Friends at Thomas Pearce`'s house,
and from there to Birr, and on the day following were at Friends`' meeting there;
and the next day came to my own house, where I parted with George Rooke,
who went to his house and family in Dublin.

I kept to meetings about home,
and in a short time it was on my mind to visit Friends in the province of Ulster,
and to get meetings at some places where no Friends dwelt.
Leinster Province Meeting being at the Moat, I went there,
and stayed the service of that meeting, and then took my journey to the north,
with my aforesaid companion George Rooke and several other Friends.
We rode that day to Finagh, in the county of Cavan,
and had a meeting in the evening at the inn where we lodged,
there not having been a meeting of our Society in that town before;
several people came to it, where truth was declared to them, and they were sober.
Next morning we went to Cavan,
and visited some Friends who were prisoners there for their testimony against tithes.

The day following we were with Friends at their meeting beyond Ballyhayes,
and then went to Coot-hill, having sent some Friends before to Clownes,
to get a place for a meeting, which they did.
We had a meeting with Friends at Coot-hill, and the next day went to Clownes,
where we had a full meeting, and the Gospel of Christ was preached to them,
all being quiet.
We then rode to Monaghan,
and that evening had a meeting in a large dining room at the inn where we lodged.

The father and uncle of the priest, who had cast those Friends into prison at Cavan,
living near our road, we went there the next day and discoursed with them,
endeavouring to obtain our Friends`' liberty, but got little entrance.
We came that night to Ballyhagan,
where we had a large and full meeting on the first-day of the week,
and the Lord`'s power and comfortable presence were with us to great satisfaction.

Next day we were at a full and comfortable meeting beyond Charlemount,
and then went to Toberhead, in the county of Londonderry, and had a meeting,
to which Friends came from other meetings,
and were well refreshed in the Lord Jesus Christ.
We then went to Grange, in the county of Antrim, and stayed a meeting with Friends,
and from there to the town of Antrim, and had one there.

The Province Meeting for Ulster began there on the next day,
and held part of two days in worship and discipline; from there we went to Lurgan,
and so to Monallen, and had a meeting, where most of the ancient Friends came,
and were well refreshed in the Lord, and one in another.
After this meeting we went to see Archibald Bell, he being very old and feeble,
and having walked in the truth many years;
and the next day went to the meeting at Richard Boyes`', and so to Lisburn;
we were with Friends at their meeting there, and then to a meeting at Hilsborough.
In all of them the testimony of truth was largely declared,
and many deep mysteries in the doctrine of Christ`'s kingdom were opened,
in the demonstration of the spirit and power of our Lord and Saviour Jesus Christ.

After this meeting we went to Tobias Courtney`'s, and lodged there one night,
and on the next day to Lurgan,
where we had a very large and full meeting of Friends and other people.
On the day following, being the first-day of the week,
the Lord`'s power was mightily with us,
and many heavenly mysteries were opened in the doctrine
of the everlasting Gospel of Christ Jesus,
to the tendering and refreshing of many hearts,
and to the breaking down of the strongholds of the man of sin.
When this great meeting was over,
we had gone through our intended service in the province of Ulster,
except visiting one small meeting, which lay some miles remote; and I being much spent,
and having also got cold, was willing to rest one day,
before I took my journey to Dublin.
My companion, George Rooke, answered the service of that meeting,
and by appointment I met him at Newry, where we had the company of many honest,
tender Friends, who were going to Dublin to our National Half-year`'s Meeting,
which was then at hand.

The next day we all went to Garland`'s town to lodge that night,
and had a meeting there in the evening,
the innkeeper being very courteous and willing to let us have room to meet in.
We then went to Drogheda; several Friends from Dublin met us, and we had a meeting there;
the testimony of truth was set over the unfaithfulness of some inhabitants in that town,
who professed the blessed spotless truth.
