== Chapter XXVIII

[.chapter-synopsis]
* In several meetings, both National and Provincial, he was earnest to have marriage, which is God`'s ordinance, both begun and accomplished in God`'s counsel

We all went to Dublin, and on the day following, being the seventh-day of the week,
and 8th day of the ninth month, 1707, our National Half-year`'s Meeting began,
and many Friends were there from several parts of the nation;
also accounts were given of the affairs of truth,
and concern of Friends for its prosperity.
The meeting held part of four days,
in the public worship of God and meetings for church discipline.
When it was over I returned home;
and the Quarterly Meeting for Leinster province being shortly after at Mount-melick,
accounts were brought from the several Monthly Meetings in the province,
how church discipline was kept up, and a holy and zealous concern was on Friends,
that marriage, which is God`'s holy ordinance,
might be proceeded in and performed according to his holy will,
that therein his joining might be known, so that those who give and take in marriage,
may do it in God`'s fear and counsel, and not for riches and worldly ends,
for this is contrary to the ordinance of God in marriage, which is honourable in itself,
being uncorrupted; and truth must and will regulate the violation thereof.

Some time after this,
the aforesaid concern of marriage was closely spoken to in our
Monthly Meeting for church affairs at Mountmelick.
Our Six-weeks`' Meeting for Leinster province being appointed to be at Athy,
it was upon my spirit to be there, and to visit some meetings of Friends thereaway;
and though it was cold winter, the days short, foul weather, the ways very deep,
and my body aged,
yet I doubted not the Lord`'s assistance to give ability to perform this service,
as he had at many other times done for me in great difficulties and dangers.
So in the faith of Jesus I went there,
where was a pretty large gathering of weighty Friends and elders;
and after some time spent in worshipping God, we went to our service in church affairs,
men and women apart, in the sense of the Lord`'s goodness.

Several matters relating to Gospel order and discipline
in the church of Jesus Christ were closely discoursed,
and several couples presenting themselves at that meeting,
declaring their intentions of rnarriage with each other,
it gave occasion for a large discourse on that great ordinance of marriage,
as it was instituted by God; and a weighty concern was upon my spirit,
to press all Friends concerned in giving or taking in marriage,
to do it in the Lord`'s way, as he instituted it in the beginning, when he created man,
and then woman to be a help-mate, and brought her to him,
and joined them together as man and wife.
That so all Friends concerned in that matter,
should be careful to act therein in the counsel of God,
from the beginning to the accomplishment thereof, and marry in the Lord;
which marriage is honourable.

When the service of this meeting was over, I went in truth`'s service,
as it opened on my spirit, in a sense of the Lord`'s drawings,
and had a meeting at John Watson`'s, and another at New Garden,
and the Lord`'s goodness was greatly with me,
who mightily strengthened both in the inner and outward man;
so that the testimony of the blessed truth was held forth,
and the doctrine of the Gospel divided,
in the wisdom and authority of the spirit and power of the Lord Jesus Christ,
to the great comfort of true-hearted Friends.
When this service was over,
I went to my own dwelling in peace and satisfaction in the Lord.
I attended meetings near home until our next Provincial Quarterly Meeting,
which was at Castledermot; and the Lord drawing my spirit to that service,
I went there in the faith of Jesus Christ,
that he would strengthen both my outward and inward man,
to perform the journey and service which he required,
as he had often done to my great encouragement, through many difficulties and weakness.
Accordingly the Lord strengthened me with his power and good spirit,
to stand in his testimony over all that was contrary to
the government of Christ in his church.
The service of that meeting was carried on in the
authority of the Lord`'s power and ancient goodness.
When the meeting was over, I returned home, attending meetings as usual.

Our next Six-weeks`' Meeting for Leinster province being appointed at Catherlough,
I went to it, where many Friends of the province met to worship God,
and perform service in the Church of Christ,
and still I found that the Lord renewed my strength and
ability beyond the ordinary course of nature;
everlasting praise to his great name!

The next Quarterly Meeting for the province of Leinster was at Mount-melick,
where the Lord`'s power did eminently appear,
for maintaining the testimony of his blessed truth, both in doctrine and discipline.

After this meeting, I went to our National Half-year`'s Meeting at Dublin,
which was then at hand, being in the third month, 1708, and,
through the Lord`'s great goodness and mercy to me,
was enabled to hold out through the service of that great meeting,
which held from the 8th to the 12th day of the month.

Our next Six-weeks`' Meeting being appointed at Ballycane in the county of Wicklow,
I had some drawings on my spirit to be there; and trusting in the Lord for ability,
took my journey to New Garden, in the county of Catherlough,
and was with Friends at their meeting.
After which I went to Dunlavin, where I had appointed a meeting;
George Rooke from Dublin met me there,
and we had a full and satisfactory meeting of Friends and sober people.
We then went to Thomas Ducket`'s, and next day to Ballycane in the county of Wicklow,
where the Province Meeting began the day following,
and there was a great appearance of Friends and sober people.
