== Epistles and Papers of William Edmundson

[.letter-heading]
An epistle to Friends, written in Jamaica.

[.salutation]
Dear Friends,

As you have received and believed in the precious truth, so live in it to God`'s glory,
and walk upright in the freedom and liberty of the truth and Gospel of peace,
in which you will have peace with God.
Go not back into the liberty of the world, for that will bring you into bondage,
and the old leaven will steal in by little and little,
which leavens into the love of the world, draws from the love of God,
hinders the incomes of his love in your souls,
and draws the mind into great incumbrances, and sets the affections on things below,
to mind earthly things more than heavenly.
This becomes a yoke of bondage, and will make you look down into the earth,
and keep you from looking up to the Lord, who says.
Look unto me.
All stand fast and firm, therefore, in the freedom and liberty of the blessed truth.
Let none lose the heavenly image,
lest the earth and earthly image steal in and come over again;
and like the grave swallow up, or like the thorns choke all that is good,
and so stain and spoil the beauty and comeliness,
which you have in the everlasting truth.

Friends, in the name of the Lord Jesus, shake yourselves from the dust,
and from the earth, being quickened and raised from the grave, and from the earth,
by the spirit and power of the Lord.
Sow not among thorns, but plough up the fallow-ground,
and keep a diligent hand at the plough, that as the axe has cut down the branches,
so the plough may tear up the roots, that the roots of corruption,
earthly-mindedness and covetousness, which is the root of all evil,
and the root of bitterness be not left unrooted out through neglect;
and so those old roots spring up again, and choke the good,
and make the garden unfruitful to God.
Must not his people be as a fruitful field,
and as a pleasant garden to bring forth much fruit,
to be a sweet smell and a sweet savour?
And so, all Friends, see that the fields and gardens of your hearts be kept clean,
and the roots hacked up as well as the branches;
that you may flourish in the new covenant, as the field of the Lord, and as his garden,
give a sweet smell and savour of life unto life, and of death unto death;
and as his fruitful plantation, bring forth much fruit to his praise and glory,
who is the chief Planter and Workman, that he may delight to dwell in his plantation,
and to walk in his garden, and to water it in due season,
and not have cause to reject or cast out any, as a withered and unfruitful branch,
through unworthiness.

Let all walk worthy of God`'s love, visitation and mercies,
and take heed of turning again unto such things, as truth judged, led out of,
and caused us to deny at the first, in trading or otherwise; for truth changes not.
Therefore keep the first love and principles,
spotless and blameless in the sight of God and man, and remember the children of Israel,
whom God took by the hand to bring from the bondage of Egypt,
and to give them the Land of Promise, how many of the first generation fell,
and came short by looking back through unbelief,
and tempting and grieving the Lord in the time of their trial.
Also Lot`'s wife, who looked back, was set for an example.
And are not we a kind of first fruits, and a generation whom God has visited,
and taken by the hand to redeem from the earth, and from the world,
after a long night of apostasy and falling away?
Let all take heed and be circumspect;
for there is much upon my spirit concerning these things, hard to be uttered,
and harder to be borne by some.
See that none leave either hoof or horn in Egypt, for then the mind will be towards it.

Therefore all arise, and come forth with the Seed royal,
that all we have may be in the hand of the Lord, as an offering and sacrifice to him,
which is but a reasonable service.
We are but stewards of what we have, and must give an account to God;
therefore take heed of being married to your shops, and trades or merchandise,
whereby you are encumbered and hindered from coming to meeting,
serving the Lord and doing his work, as though your work and business must be done first,
and the Lord`'s last.
Would not you blame and be angry with your servants,
who would prefer and do their own work and business before yours,
and be so encumbered and busy therein, that your business is neglected?
Therefore be careful that the Lord`'s business is first done,
and his truth and the concerns thereof preferred before all,
that you may receive an answer from the Lord of "`Well done,
good and faithful servants.`"
For if any be linked and married to the world, and to the earth, their shops,
merchandise or trading, and have their delights there,
how are they God`'s freemen and Christ`'s spouse, married to him?
Must not they, who are married to Christ,
be free from the world through the cross of Christ, the power of God,
and walk as freemen, having the earth under them, and not over them?

Therefore be good merchant-men; prize the precious truth, the precious pearl,
and the preferment of it above all, that the love of the world enter not,
and work as the old leaven,
by which the streams of God`'s free love in your hearts may be stopped.
Prize the love of God and walk worthy of it;
for as a tender Father He gave his Son for us, even the Son of his love,
whom he has made heir of all things,
that we through him may be heirs of an everlasting inheritance,
and not go after other lovers, or have the heart carried away with them,
who will not stand instead, nor can they save in the needful time.

[.signed-section-signature]
William Edmundson

[.signed-section-context-close]
Jamaica, the 24th of the Twelfth month, 1671.

=== Part of a Letter to His Wife.

I have had several meetings here with Friends; the Lord`'s heavenly presence was with us,
and many were well refreshed.
I desire that all may be careful of God`'s honour, and the fame of his blessed truth,
which is more than all, that occasion be not given whereby truth may be evilly spoken of.
My love is to all our children with you; and my desire and charge to them is,
to fear God, love his truth and people, and love one another;
live in peace and walk soberly to all; for the fear of God will keep their hearts clean,
and by it they will learn wisdom towards God and men,
which will adorn and commend them before men,
and in the end produce both peace and comfort.
My dear love is to you, as a true and faithful husband, which you may assure yourself of,
wherever I am, or however I may be disposed of;
and my tender love is to all honest-hearted Friends, as if I named them, and rest

[.signed-section-signature]
Your loving husband

[.blurb]
=== A letter of examination to all who have assumed the place of shepherds, and overseers of the flocks of people of all sorts in Christendom, to see if your accounts he ready, and what order the flocks are in: with a few lines of good news to the several flocks.

Woe to the shepherds of Israel who feed themselves!
Should not the shepherds feed the flocks?
You eat the fat and clothe yourselves with the wool;
you slaughter the fatlings, but you do not feed the flock.
The weak you have not strengthened, nor have you healed those who were sick,
nor bound up the broken, nor brought back what was driven away, nor sought what was lost;
but with force and cruelty you have ruled them.
So they were scattered because there was no shepherd;
and they became food for all the beasts of the field
when they were scattered.--Ezek. 34:2-5.

Behold, I am against the shepherds, and I will require My flock at their hand;
I will cause them to cease feeding the sheep,
and the shepherds shall feed themselves no more;
for I will deliver My flock from their mouths,
that they may no longer be food for them.--Ezek. 34:10.

Come all you who have assumed the title of shepherds,
and overseers of the flocks of people of all sorts in Christendom:
you have had the oversight, and ordering of the people for a long time;
and the Lord has been as a man in a far country,
but now he is coming to call you to account, and will require the flocks at your hands;
the time is near when you must give account of your charge,
and receive a recompense of reward from him according to your deeds.

This is a warning to you all, to have your accounts ready,
and see that the flocks are in good order, and that nothing is wanting;
for you will not permit any to meddle with the flocks but yourselves,
therefore at you hands the Lord will require them.

Have you kept a diligent watch night and day, with carefulness for their souls?
Have your locks been wet with the dew, and the hairs of your heads with the frosts,
to preserve their feet in the way of peace, from the devourer,
and out of all filthy unclean ways?
Have you been good examples before your several flocks in all things,
walking before them as good patterns?

Have you led them to the pastures of life, and fed them in due season?
Or have you not played the careless idle shepherds, sitting in your fat places,
and lying at ease upon your soft pillows, feeding with the fat,
and sporting yourselves in your day and time,
while the poor flocks go astray in the by-paths,
and are scattered in the barren wilderness, as sheep wanting a shepherd,
and as a people without their guide,
where their souls are starved for lack of the bread of life?
Have you led the flocks to the fountain of living mercies and well-spring of life,
where they might drink freely, without money, and thereby be refreshed,
and all become fruitful; or are they not dried up for lack of the springs of life,
and so unfruitful in anything that is good?

Have you not also in this condition led and driven them, by your example and persuasion,
to the dirty puddles of sin and uncleanness?
Have you not persuaded the flocks, that this is what they must drink,
while on this side the grave?
Are not your flocks, as you call them, by that means, fallen into gross diseases,
as rottenness of heart, unsoundness of mind, blindness and deafness,
from seeing their salvation, and hearing the voice of the Lord Jesus?
Are they not fallen into lameness of feet and hands?
So that they cannot walk upright in the just man`'s path, which is a shining light,
but stumble at it; nor can they handle the sword of the spirit, which is the word of God;
by which they should war against the man of sin, and break down his strong holds.

And by drinking iniquity, sin and uncleanness,
are not the flocks fallen into gross diseases; that there is no health in them,
and become weak in the faith, wherein they should resist the devil and overcome him:
and have lost their taste, smell and savour in the things of God;
so that everything that is seasoned with his spirit and power,
becomes loathsome to their taste, by reason of disease, wanting salt in themselves,
by which they should be the savour of a sweet smelling sacrifice to God,
and be able to season the earth?
And through lack of it, is not the earth corrupt, and the creation burdened?
Does it not groan, and wait to be delivered from that bondage?

What have you in your flocks to offer to the Lord, that may find acceptance with him?
Will he accept of the unclean, the sick, lame or blind?
Must not the church, that is presented to God, be without spot, or wrinkle,
or any such thing?
Nothing that is unclean can enter into his kingdom.
Have you looked carefully to your several flocks,
to keep them from the spots of the world?
Or are they not run over with a scab, as with a leprosy?
And have you not played the lazy shepherds, to look no better to the flocks?
Or the empirics who have said, you have the care and cure of souls,
and are the physicians;
and yet let your flocks fall into such gross diseases and uncleanness?
Are not you the careless shepherds, and physicians of no value?
Would not you blame and be angry with the herdsmen of your flocks,
and require your flocks at their hands,
or throw them into prison till they made satisfaction, if they dealt so badly with you,
concerning your flocks and herds?
And will not the Lord do so by you?
Is it not just and equal, that he require the flocks at your hands?
For you have been well paid for looking to them, as you very well know,
and the nations can witness.

Have you kept one certain voice, as the good Shepherd does, that the sheep might hear,
his voice and come together, and not stray and fall into pits?
Or have not your voices been variable as the wind, giving an uncertain sound?
And your flocks not finding a certain voice among you,
are scattered into sects and parties, pushing one another into the pit and mire,
instead of helping out of it.

Again, have you been careful to count the flocks morning and evening,
as shepherds ought to do, that none be wanting?
Or have you neglected this duty also, save at fleecing times; like the hireling,
who cares not for the flocks, but for the fleece?
Have you endeavoured to keep the flocks, over which you pretend to be overseers,
marked with the Lamb`'s mark in their foreheads, that they may be known to be his?
For if they be not, but marked with another mark, will he not say, "`Depart,
I know you not?`"
Have you acquainted the flocks with the fold of peace and safety,
and with the way to come into it gently, and to rest in meekness and quietness?
Or have you not been negligent, and let them grow wild,
as the wild goats upon the mountains, and as bullocks unaccustomed to the yoke,
or as heifers snuffing up the wind?

Have you not left the office of a shepherd, and are not many of you turned hunters,
who hunt the Lord`'s little flock, which he has gathered by his power into his spirit,
and put under the hand of the true Shepherd, who feeds them in due season?
Do you not hunt them as a partridge,
and make it your game and sport to spoil and destroy them, as the flock of your prey,
and prepare your tongues like bows, and your words like arrows,
to destroy and cut them off, whom you know by the Shepherd`'s mark,
from all the flocks in Christendom, so called?

Do you not sound the horn of envy and persecution,
to awaken and stir up all of like mind with you,
to hunt and spoil the Lord`'s little flock,
as though they were not worthy to feed and live upon the earth,
with the rest of the flocks; or as if the earth were yours, and not the Lord`'s;
and that he might not have a flock upon earth, as well as you,
or as though he had no right, but all were yours?
Think you that the Lord sees not this, and will it not kindle his wrath,
and hasten him to call you to an account, and reward you according to your works?

May not he justly hunt you, who have been the chief hunters of his flock,
and prepare his bow and arrows against you, and mark you out, and make you a hissing,
and a by-word to the nations?
Is it not just for him to take the flocks from you, who have been careless,
and neglected your service and duty; and now will not let his flock be quiet,
but rend and tear them?
Is it not justice and equity for him to rend the flocks from you,
who will not allow them to receive the law at his mouth,
whom he has ordained a priest forever, and whose lips preserve knowledge?

Will not the just principle in you answer to his justice,
when it comes upon you to take the flocks, and lay you aside,
and put them under the hand of his Son, Christ Jesus, the good Shepherd;
who will bring them to the fresh pastures of life, and feed them in due season,
and cause them to hear his voice, and to know it,
and to come to his fold and lie down in it in quietness, meekness and patience,
where none shall make them afraid, preserving from the storm and from the heat.

He will bring them to the well of clean water and fountain of living mercies,
and cause them to wash and be clean, and to drink and be refreshed,
that they may no longer be barren in fruits of holiness, but bring forth to God`'s glory;
and anoint their eyes with eye-salve, and open their blind eyes.
Then they will see you to be blind guides, and bless the Lord who redeems them from you.
He also will give them precious ointment, even the virtue that goes out of Him,
the good Physician, that will cure their spots and leprosy,
which ran over them while under your hands, and will purge their corruptions,
and cure the diseases of sin, by which death has had dominion.
He will give them saving health, heal their backslidings,
and open the mysteries of his kingdom to them; circumcising their hearts and ears,
and causing them to understand those secrets
which are hidden from the wisdom of this world,
and bring them out of the many ways, into the one way, Christ Jesus the way to God;
and out of the many sects, divisions and parties, which they are fallen into,
and have been entangled with, in the cloudy and dark day that has been over them,
while under your hands.
He will set His name and his Father`'s name upon them,
and give them the seal of the new covenant,
that they may know and be known that they are his,
whom he has purchased with his precious blood, and redeemed, searched and sought out;
and as a good Shepherd, who neither sleeps nor slumbers.
He will bring them to the mountain of the house of the God of Jacob,
and teach them of his ways, and watch over them.

He will work a reformation in the nations, and bring them to the one true church,
which is in God.
founded and built upon the sure foundation that
God has laid as by the hand of a wise workman,
into the fellowship of the one body, whereof Christ Jesus is the head;
who supplies the whole body with all things needful to
build them up in their most precious faith,
which gives them victory over the man of sin, and renews into the true worship of God,
in spirit and in truth, and a true conformity thereto,
by his law of the spirit written in the heart.

There Christ is Priest according to the appointment of the Father,
Minister and Bishop of the soul, who ministers life, peace and comfort unto them,
and renews his holy and heavenly ordinances in the church,
baptizing into one spirit and into the one faith,
that works by love and purifies the heart, giving a white stone, and in it a new name,
and feeding them with the sincere milk of the word.
He fills the priest`'s office in the church of the Firstborn,
preparing the altar and spreading the table with fine white linen,
which is his righteousness; and prepares the bread for his church,
and fills their cup with the new wine, that they may all drink of the cup of blessings,
which is the communion of his blood; and may all eat of the one bread,
which is the communion of his body, and his body is bread indeed,
and his blood is drink indeed.
This is that which gives life; and without it they cannot have life;
and this is free without money, wherewith the Lord`'s table is furnished,
and he is inviting the people and gathering the nations to it, from your costly tables;
for you have sold them bread, wine and water at a dear rate.
But he will freely feed them with all things necessary, as a household of one faith,
and as one family.
Christ Jesus, who is greater than Solomon, their Lord and Master, shall govern them,
setting up and renewing family duties among them, to stand on their watch,
to resist every appearance of evil,
and to pray with the spirit and with the understanding,
and to sing with the spirit and with the understanding also.
And he shall rule, whose right it is, and the government is upon his shoulder,
whose kingdom is everlasting, and of his government there shall be no end.
The Lord will do this, to reform the nations,
and bring them to uniformity and true conformity in his dear Son.

[.signed-section-signature]
William Edmundson

[.signed-section-context-close]
Jamaica, the 24th of the Twelfth month, 1672.

=== Part of a Letter written by William Edmundson, at Barbados, to Friends in Ireland; dated the 8th of the First month, 1675.

My love is to all dear Friends.

It is not distance or length of time, tribulations or peril by sea or land, though many,
that can make me unmindful of you;
for you are sealed in my heart in an everlasting remembrance of true and unfeigned love,
in the holy Spirit and covenant of the Father`'s love,
where our unity stands with the Father and his dear Son, and one with another.
My earnest desires are to the Lord,
that in it you may all be kept faithful to the Lord in all things,
without spot or blemish; and that truth may be loved and preferred before all,
in you all, and by you all in all things.
Though it be my lot to be as one separated from that,
which may be as dear and near to me as other men,
and as one cast out from the enjoyment of wife, children,
or other benefits and comforts in this life, as the off-scouring and forsaken,
liable to good report or evil report, to be received or rejected, in plenty or in need,
liberty or bonds, safety or perils by sea and land, life or death, to take my lot,
as it may fall by night or day, in house or wilderness, among friends or enemies,
I must be content for the Gospel`'s sake; a dispensation of it being given to me,
and a necessity laid upon me to preach it; for which sake my life is not dear to me,
so that I may finish the work committed to my trust, with joy,
and in the end stand in my lot among the justified.

Now my Friends, will not the consideration of what you enjoy,
provoke you to love and good works, to be diligent in the Lord`'s business,
and prefer it before all your own?
For you are partakers with me of the same riches of God`'s love,
which is to constrain us all to love him.
Consider the benefits you enjoy, and let them be as obligations upon you,
to serve the Lord and his truth in faithfulness in your places,
and one another with fervent and unfeigned love,
and not to slight matters where truth is concerned; but keep all things sweet and clean,
appertaining to your pure religion, which in itself is unspotted.
For you know that truth is pure, innocent and peaceable,
and holiness becomes the house of God, who loves holiness,
but hates uncleanness and will not dwell with the unclean.
So dwell in the love of God, and in the peace of our Prince of Peace,
and be at peace one with another, that the love of God in Christ may dwell in you,
and abound among you.

By this all my dear Friends may know,
that I am very well and have had good service for the Lord in this island,
and the Lord is with his testimony, and blesses and prospers his work;
many are convinced,
and meetings so full that the meeting-houses cannot contain the people.
Many of the blacks are convinced, and several of them confess to truth,
and things here are peaceable, and in as good order as can well be expected at present.
James Fletcher and companion came here about a month after me,
and this day took shipping for the Leeward Islands, and intend to go to Bermudas,
and so to New England.
I am ready to leave this island the first opportunity for Rhode Island or New York,
which I expect may be about two weeks hence.

John Haydock landed here two days ago from New England, and is well,
and that country is much distressed by the Indian wars.
They had a sharp fight this winter, in which, they say,
the English were beaten and lost above three hundred men, six or seven captains slain,
and many officers.
They of Boston have sent out fresh men, and it is supposed have fought again by this time.
Great fears surprise the people, and their hearts fail them,
that they lack courage when they should look their enemies in the face.
The guilt of the blood of the innocent shed by them lies on them,
and the Lord has given them blood to drink.
It is said,
that several of their priests in Boston colony had a meeting to inquire of the Lord,
what the reason is that he is departed from them, and goes not forth with their armies;
and their return is for many causes, but this the chief, namely:
Allowing the Quakers`' meetings among them.
Thus persecution makes men blind, that they run headlong to their own destruction;
but many of the people are dissatisfied,
and believe it is the killing and persecuting of the Quakers,
that is the cause of their distress;
and they are distracted and confused among themselves, with fears on every side,
and great jealousies,
that all the Indians in those parts of America will be in arms this next summer.

It is likely to be troublesome and perilous travelling,
but the Lord can preserve and deliver out of all, unto whose will I am given up,
whether it be to suffer for his name, or to live or die for his truth, his will be done;
and I hope my life will not be dear to me to part with, if he see it good;
and I do not doubt but he will give me strength, in the inward man,
to bear what the outward man may suffer for his glorious Gospel.
These tidings do not affright or amaze me,
for the glory of the recompense of reward to the faithful is before me,
and does out-balance all fears.
Your prayers to the Lord on my behalf may help me in my various trials and exercises,
who desire to be in your daily remembrance, even as you are in mine,
never to be forgotten, for my spirit is with you,
and the overflowing of the love of Christ in my heart dearly salutes you all;
and as we live in this, we shall never die, but shall meet again, if not in this life,
yet in the life to come.

Finally, dear Friends, I cannot but put you all in mind, to walk as freemen in the truth,
and in the liberty of the Gospel, and be not too careful, or too busy,
or encumbered with the things of this life; but be ready for sufferings,
which may attend that nation before many be aware, that we may all be ready,
as Christ`'s freemen, to drink that cup which the Lord is pleased to put into our hands,
for the trial of our faith, which is more precious than gold.
My dear and true love is with you all, in the power of an endless life,
wherein I am,

[.signed-section-closing]
Your friend and brother,

[.signed-section-signature]
William Edmundson

=== Some Letters to His Wife

[.salutation]
My dear Wife,

This is to let you know, in part, of my fare in this my travel.
I landed in Barbados in eight weeks and four days after I left Ireland,
and abode there about six weeks, where I had much service for the Lord,
which was well accepted by Friends.
Sailing from there to Antigua, we were in danger of shipwreck,
our ship having twice struck on rocks and afterwards run upon a shoal,
our master and company not being acquainted with that coast;
yet through the Lord`'s mercy and help we got safe off, and landed well.
I was very sickly and weak in body, while I was in that island,
and my spirit oppressed with wrong things there,
so that I was bowed down in body and mind, yet I kept meetings.
After nine days abode there I sailed to this island, and have had several meetings,
and several people of account resort to them, and are very tender and loving.
I am now very well, blessed be the Lord, and intend, if the Lord will,
when clear in this island, to sail to Antigua,
and so as opportunity presents to Barbados, and when clear there,
I know nothing at present but I may return to you in Ireland, if the Lord permit,
which I know will be welcome news to you.
My tender and true love is to all Friends, as if I named them, and to our children,
and my prayers to the Lord are for them day and night, and for you all,
that you may be preserved, and walk blameless in the Lord`'s truth,
to his honour and our mutual comfort.
My true and faithful love is with you, and I desire you,
be tender of God`'s honour and truth`'s fame: So rest.

[.signed-section-closing]
Your faithful husband,

[.signed-section-signature]
William Edmundson

[.signed-section-context-close]
Charles-town, in Nevis, the 10th of the Second month, 1684

[.salutation]
My dear Wife,

The true and tender love which in duty I owe you,
is an engagement upon me to write to you by every opportunity that presents,
that you may partly know of my fare in my travels through many and deep exercises.
I have been at Nevis and Mountserrat, and being now returned to this island,
am very well, blessed be the Lord,
who gives me strength and ability to perform his service committed to my charge,
even beyond expectation.
I purpose in the will of God to take the first opportunity for Barbados,
and when clear there, I find nothing at present but I may return for Ireland,
but must abide in the will of God, to which I still hope you will submit,
whether in returning or travelling further, life or death.
My true desires and prayers to the Lord night and day, are for you and yours,
that you may be preserved blameless in his blessed truth,
to God`'s honour and our mutual comfort.

[.signed-section-closing]
Your faithful and loving husband,

[.signed-section-signature]
William Edmundson

[.signed-section-context-close]
Antigua, the 3rd of the Third month, 1684

[.salutation]
Dear Wife,

My dear, tender and true love is to you,
which you may assure yourself is true and faithful in all places,
and neither time nor distance, prosperity nor affliction can wear out;
for my heart is with you in sincere love as it ought to be,
and my desires to the Lord day and night are for you,
that you may be preserved blameless in his blessed truth, which in measure you know,
the increase whereof I much desire,
and to find which at my return would be great joy and comfort to me.
I hope you do, and wilt strive with all godly endeavours,
to live and walk in the course of your conduct, blameless in the sight of God and men,
as becomes the blessed truth and Gospel of the dear Son of God, which we profess,
and for which in measure I am set in defence, through good report and evil report.
Therefore fulfil my desire, and it will greatly add to my comfort,
and increase my joy in the Lord Jesus, which is desired before all visible things,
by me your faithful husband.
I have been some considerable time at the Leeward Islands, namely: Antigua,
Nevis and Mountserrat, and being clear there, am now returned to this island,
and my coming to these parts was in a needful and acceptable time, and not in vain,
as many can bear witness.
The Lord`'s goodness is with me in his blessed service, for which not only I,
but many others bless and praise the Lord, whose care is over his people.
I find the longer I stay, the more is the service,
and truly the Lord gives me ability of body beyond expectation.
Everlasting praise to his name forever.

My tender fatherly love is to our children,
with continual care and fervent desires for
their preservation out of the evil of the world,
the snares of the devil and lusts of the flesh, which drown ungodly men in perdition.
If they turn aside into these, it will wound my heart,
and heap loads of sorrow and affliction upon my head.
But if they fear God, and love truth with all their hearts,
and the bent of their inclinations be to virtue, justice and righteousness,
as good examples, which become children of a careful and religious father,
then they will make glad my heart, more than the increase of all the riches of the world.
This is according to the truth of my heart, as the Lord knows, who searches all hearts.

My dear love is to all Friends, as if I named them,
desiring they may be preserved blameless in the blessed truth; which,
through the mercies and love of God, they have received and believed in;
and that the propagation of it may be preferred
before all in their hearts and affections,
is the real desire and breathing to God on their behalf,
of their ancient and true Friend, who cannot forget them when before the Lord.
Once more my love is mentioned to you, and I hope yet, in the Lord`'s time,
to see you again to our comfort, and remain, Your true and faithful husband,

[.signed-section-signature]
William Edmundson

[.signed-section-context-close]
Barbados, the 4th day of the Fourth month, 1684

[.salutation]
Dear Wife,

In my last, I gave you some encouragement to expect my return to you from this Island;
but finding a concern to go to Jamaica,
I cannot be clear to return in peace without performing,
and I hope you are willing to give me up to the will of God, whatever it be,
in life or death.
I think it fit, and true love leads me thereto,
to give you an account of how I spend my time.
I abode in this island about five weeks, then sailed to the Leeward Islands, Antigua,
Nevis and Mountserrat, and laboured in truth`'s service about ten weeks,
and returned here, having had good service for the Lord and his people,
which was well accepted, and I hope will not prove fruitless;
the Lord`'s blessed presence and power are with me,
to mine and many others great satisfaction and refreshment.
Everlasting praises to his name forever.

Through the tender mercies and endless love of God,
I am able in body to labour beyond expectation;
the Lord is worthy to be served with the abilities he gives.
I purpose in the will of God to go for Jamaica, by the first opportunity of a passage.
I earnestly beg and desire above all earthly things,
that you and our children may be preserved from the corruptions and evils of the world,
in a blameless conduct, as becomes the truth, which you know in part.
And as your whole inclinations, fervent desires,
ardent affection and reverence are to virtue, abhorring every vice,
no doubt the Lord will increase your knowledge and faith in his Son,
and multiply his grace and truth in you, and put his good spirit upon you,
by which you will be made a good savour in your places, both to God and men,
and cut off occasion from such as watch with an evil eye for your halting,
to make it a cloak for their unjustifiable doings, and to reproach me upon occasion.
My earnest desires and prayers to God, through the spirit of his Son,
are day and night for your preservation from all the evils of the world,
and corruptions of the flesh, with the lusts thereof;
and that you may be enriched with the increase of God,
through the blessed spirit of his Son,
to his honour and your comfort both here and hereafter.
This will be more joy and gladness to me, than the
increase of all the riches in the world.
The God and Father of our Lord Jesus Christ, preserve you blameless,
and cause his face to shine upon you,
that-in his light you may shine to his glory and honour, to whom all is due forever,
Amen.
My dear and true love is with you, and to our children, and to all dear Friends,
as if I named them.

[.signed-section-signature]
William Edmundson

[.signed-section-context-close]
Barbados, the 12th day of the Fifth month, 1684

=== For all Friends who know the heavenly gift of Christ Jesus, from the apostles to the hindermost of the flock of Christ, that they neglect not the service of their day, according to the abilities and gifts received, and more especially those gifted for doctrine and government.

Christ Jesus, the promised Seed, who bruises the serpent`'s head,
of whom the law and prophets gave testimony, according to the promise of the Father,
came in due time, in that prepared body, to do the will of God for man`'s redemption;
which when he had finished, and tasted death for us, he ascended up on high,
and gave gifts to men, and peculiar gifts to believers.
To some apostles, to some prophets, and to some evangelists, pastors and teachers,
discerners of spirits, and help-mates in government.
Several other gifts gave he also to his gathered flock that believed in him,
for edifying and building them up in the precious faith, of which he is the author,
that they may come to the perfect knowledge of God and Christ,
in the measure and stature of the fulness in him,
and be established in him the head and foundation,
and grow up in him in all virtue and godliness, in Gospel order.

Everyone thus gifted by Christ Jesus, is to wait on his gift,
and attend to his service in the ministration thereof,
according to the proportion of grace and faith given.
Whether it be prophesying, ministering, teaching or exhorting,
all are to wait on their service; and he that rules to be diligent,
and speakers are to perform it as the oracles of God;
and thus to administer one to another as good stewards of the manifold grace of God,
and to keep in the bounds and line of their own measure and gift of Christ,
not going beyond it into another man`'s line.
They are to be sound in faith and doctrine,
and not to be entangled or cumbered with the affairs of this life,
nor choked nor surfeited with the riches of this world, nor laden as with thick clay,
to hinder their following Christ the Captain,
who has called and gifted them for his work and service in his vineyard,
to labour in the Gospel and leave all for it,
that it might be performed and finished according to the will of God,
under the daily cross and self-denial.
Such must not be at ease in the flesh, world or will,
or in their own time and place in trading, dealing,
and getting riches but diligently attend to their service and gift,
and keep the body in subjection, lest while preaching to others, they become cast-aways;
and take heed to themselves and to the flock of Christ,
of which the holy Ghost made them overseers, and be examples before them,
and feed them in due season.

Christ Jesus, when he ascended into glory, established his church in government,
as well in discipline, as in faith and doctrine;
and committed the care and trust to gifted men for every service,
to keep the whole body in order,
according to the rule and holy rites of the new covenant.
And the apostles, elders and brethren met together,
as well in relation to matters of Church government, as for the worship of God;
and discoursed of matters committed to their charge and trust,
as stewards and overseers of Christ`'s vineyard, husbandry and heritage.

Those preachers who went from Jerusalem to Antioch,
and would mix the law of the first covenant with the doctrine of Christ`'s kingdom,
were reprehended and the churches advised of their error;
others also in those stations of apostles, prophets and preachers,
who kept not to the gift of Christ,
but went beyond their line and rule into confusion and disorder,
which tended to destruction and not to edification, were admonished and reproved.
Disorderly, unruly women were not permitted to teach or preach in the church;
and those qualified men, through the gift of Christ,
who had the concern of church affairs,
with the assistance and approbation of the holy Ghost,
wrote epistles and decrees to the churches, and appointed elders, as overseers,
in every meeting--faithful men, to whom was committed the care,
to see those decrees truly and duly performed,
that the church of Christ might shine in comely order and discipline,
as lights in the world, to the glory of God.

Thus the churches were established,
and those who ruled well were worthy of double honour;
and such who kept to the heavenly gift, discovered false teachers, false apostles,
false brethren and antichrists, that were among the believers, as wells without water,
clouds without rain, fruitless trees that cumbered the ground, and wandering stars,
for whom the blackness of darkness was reserved forever;
and such as loved their bellies and pleasures more than God,
yet would be talking and preaching, not knowing whereof they affirmed,
being gone from the rule and line of the heavenly gift of Christ.
So the Lord`'s care was over his gathered flock,
for their preservation in faith and fellowship with himself, and one with another;
as members of one body,
taking due care one of another for their preservation from all uncleanness, disorder,
snares and entanglements that are in the world;
and that all should be kept in the holy order
and discipline of the Gospel of Christ Jesus.
Husbands to love their wives, and wives to love and reverence their husbands;
children to honour their parents, and servants their masters; and widows to be chaste;
also young men and maids to be sober-minded, and not to marry with unbelievers;
and all to labour, for he that will not work,
must not eat--and rich men to be rich in good works.

Thus the church of Christ, both male and female,
were established in their heavenly order and degrees;
wherein all were to keep their ranks in the discipline
and ministry established by Christ in his church,
under the new covenant; and to prefer his public service before private interest.

The church that Christ espoused to himself, was adorned with her jewels,
and beautiful through his comeliness; but when the apostasy and falling-away came,
spoken of by Christ and his apostles, as seers of the times,
the generality of Christians went from the heavenly gift, saving a small remnant,
who kept to the gift of the holy Spirit,
who were forced to lie obscure under the arm of God`'s providence,
sighing and mourning because of confusion, disorder,
and the abominations which came into the churches.
Christ the man-child departed from them, and the witnesses were slain--yet unburied.
Then the whole building went to ruin, rents and breaches, and all in confusion,
both in doctrine and government; everyone sought their own wealth,
preferment and ease in the world, the flesh and will; and the cross of Christ was lost.
Ministers went to the letter, having gone from the heavenly gift of Christ`'s holy Spirit,
and got into easy places; everyone seeking their own gain and advantage,
and cared for themselves, not for the flock,
for which Christ had shed his precious blood.
Self-interest prevailed, and the public spirit that stands for and seeks the public good,
was lost; the churches were filled with confusion and errors,
their overseers being blinded with the world and by the god of it,
the faith of Christ and Christianity was marred, the beauty and comeliness gone,
the temple and tabernacle of God ruined, and his divine service and worship lost,
as it was instituted by Christ.

Thus it lay till the time of reformation and restoration,
according to the appointment of the Father;
which in mercy is largely manifested in our age,
wherein Christ Jesus is returned in the brightness and glory of his Father,
to bring up the church out of the wilderness.
He is bringing back and gathering his scattered flock,
to the faith once delivered to his saints, of which he is Author;
and causing his divine light to shine in their hearts,
to give them the knowledge of the glory of the Father;
and raising the ruin of his temple and tabernacle,
that he may dwell and tabernacle in us,
and bring us into fellowship with the Father and himself, and one with another;
and to worship the Father in Spirit and in Truth,
and be partakers of his holy ordinance of baptism, baptizing by one spirit into one body,
of which he is Head.
He is renewing the heavenly gifts of his holy Spirit, both in doctrine and government.
The everlasting Gospel is preached again, and order and discipline settled in the church,
according to his former institution,
for the preservation and growth of all his gathered flock, in the increase of God.

The care of the flock of Christ is committed to gifted men,
whom the holy Ghost has made overseers, and who are to take heed to themselves,
and to the flock, that all the house of God, which is his people, may be kept in order,
with respect to all things divine and human, according to Gospel rule.
All are to attend on their ministry and service,
and fulfil it according to their ability and gift;
that the house of God may be settled on her own mountain,
which is above all mountains and hills, and many shall flow to it,
and see the ancient beauty and comeliness which the Lord is restoring to his church,
in decking her with her former ornaments of Gospel rights and privileges.
All concerned in this great work of restoration,
who have received a gift from Christ to officiate therein,
are to attend to their office and service for the public good,
and not to choose their own time, or ease in the flesh,
or their will in the things of this world, which loads them as with clay,
and hinders their service for the public,
and is no example of self-denial to the flock of Christ;
but savours of that spirit of apostasy, which is to be purged out, as the old leaven,
that so it may be seen we are in the footsteps of those who were given up in strength,
understanding, time and substance,
to spend and be spent in the service of the Lord and his people.

[.signed-section-signature]
William Edmundson.

=== Concerning Offerings to God, in Prayer and Supplication.

The offerings that are acceptable to God, must be offered in righteousness,
and with clean hearts and lips.
For the Lord is pure and holy, and will be sanctified of all that come near him,
and his worship is in Spirit and in truth.
Prayer, supplication and addresses to God, being a special part of his worship,
must be performed in Spirit and in Truth, with a right understanding,
seasoned with grace and with the word of God;
even as the sacrifices under the old covenant
were to be brought and offered in clean vessels,
seasoned with salt and with fire.
So all, now under the new covenant,
who approach so nigh to God as to offer an offering in prayer,
must have their hearts sprinkled from an evil conscience,
and their bodies washed in clean water, and sanctified with the word of God,
and their senses seasoned with his grace and spirit in divine understanding,
and must offer that which is sound and pertinent,
which the spirit makes known to be needful; whose intercession is acceptable,
as a sweet smelling sacrifice to God, and a savour of life unto life,
and of death unto death, though in sighs, groans, or few words, being sound,
pithy and fervent.
For the Lord knows the mind of the spirit, that makes intercession to him,
who hears and graciously answers.

All are to be careful, both what and how they offer to God,
who will be sanctified of all that come near him, and is a consuming fire,
who consumed Nadab and Abihu, who offered strange fire,
though they were of the high priest`'s line.
And there may be now offerings in prayer and supplication,
in long repetitions of many words, in the openings of some divine illumination,
with a mixture of heat and passion of the mind, and a zeal beyond knowledge;
and in this heat, passion and forward zeal, such run into many needless words,
and long repetitions; and sometimes out of supplication into declaration,
as though the Lord wanted information.
These lack the divine understanding,
and go from the bounds and limits of the spirit and will of God,
like that forced offering of king Saul, which Samuel called foolish,
and the strange fire and forced offering.
These offer what comes to hand and lavish all out,
that may open and present to view at times, for their own benefit;
as if there was no treasury to hold the Lord`'s treasures; so such in the end,
coming to poverty and need, sit down in the dry and barren ground.
Therefore all are to know their treasury, and treasure up the Lord`'s openings,
and try the spirit by which they offer, that they may know the Lord`'s tried gold,
and not mix it with dross or tin; and know his stamp, heavenly image and superscription,
and not counterfeit, waste, or lavish it out, but mind the Lord`'s directions,
who will call all to an account, and give to everyone according to their deeds;
and all the churches shall know that he searches the heart and tries the reins.

As under the old covenant there was the Lord`'s fire,
that was to burn continually on the altar, which received the acceptable offerings;
so there was strange fire, which was rejected as well as the offering that was offered.
And now in the new covenant there is a true fervency, heat and zeal,
according to the true knowledge of God in the spirit and word of life, that dies not out,
in which God receives the acceptable offerings: so there is also a wrong heat of spirit,
and zeal without true knowledge, that with violence, through the passion of the mind,
and forwardness of desire, runs into a multitude of needless words and long repetitions,
thinking to be heard for much speaking, but is rejected, and is a grief,
burden and trouble to sensible weighty Friends,
who sit in a divine sense of the teachings and movings of the Lord`'s good spirit,
in which they have salt to savour withal; though the affectionate part in some,
who are not so settled in that divine sense, as to distinguish between spirit and spirit,
is raised with the flashes of this wrong heat and long repetitions,
which augment the trouble of the faithful and sensible,
who are concerned for the good and preservation of all.

We read that the priests of Baal in their offerings, were earnest, hot and fierce,
and cut themselves, making long repetitions from morning until evening,
so kept the people in expectation to little purpose.
But Elijah having repaired the Lord`'s altar, and prepared his offering,
in a few sensible words, pertinent to the matter and service of the day,
prayed thus in the spirit and power of God: "`Lord God of Abraham, Isaac, and of Israel,
let it be known this day, that you are God in Israel, and that I am your servant,
and that I have done all these things at your word.
Hear me, O Lord! hear me, that this people may know, that you are the Lord God,
and that you hast turned their hearts back again.`"
Which the Lord heard and answered.
So here a few sensible words, with a good understanding, pertinent to the matter,
without needless repetitions, were prevalent with God.

Our Saviour, Christ Jesus, when he taught his disciples to pray,
bade them not be like the hypocrites, or heathen, who used many repetitions,
and thought to be heard for their much speaking.
"`Therefore,`" says he, "`be not like unto them,
for your Father knows what things you have need of before you ask him.`"
The prayer which he taught, is full of matter to the purpose,
though comprehended in few words; and all his disciples and apostles are to learn of him,
and observe his directions, and not the manner or customs of the heathen and hypocrites,
in this weighty matter of approaching nigh unto God with offerings,
in prayer and supplication.

Our Saviour also left us a good example, written for our learning.
When he was under the sense of drinking that cup
of sufferings for the sins of all mankind,
and of offering to God that great offering for their ransom, he prayed in these words,
"`Father, if you be willing, remove this cup from me, nevertheless not my will,
but yours be done.`"
And in giving thanks in these words, "`I thank you, O Father!
Lord of heaven and earth, because you hast hid these things from the wise and prudent,
and hast revealed them unto babes, even so Father, for so it seemed good in your sight.`"
And there are many more examples in the Scriptures, full and pertinent to the matter,
comprehended in few words, and not like the heathen, in tedious repetitions,
who think to be heard for their much speaking.
Therefore all who approach God with their offerings, are to be watchful and careful,
both what and how they offer under this administration of the spirit,
and dispensation of the new covenant.

I have travelled under a deep sense and concern in this matter for some time.

[.signed-section-signature]
William Edmundson

[.signed-section-context-close]
The 12th of the First month, 1695.

[.letter-heading]
=== To His Son

[.salutation]
Son Tryal,

I received yours at Liverpool, with one by order from the Monthly Meeting,
and am heartily glad to hear that things are well with you,
and I pray God continue them so, with the increase of his goodness.
For no worldly things would be so pleasing to me,
as your preservation from the corruptions that are in the world, which the fear of God,
and love to his blessed truth, preserve out of.
If you and the rest take good heed unto this, it will add to my comfort;
and if it should be otherwise it will add to my trouble, and heap sorrow upon my head.
Therefore I desire that you may all be careful, in your conduct and conversation,
for God`'s glory, your own good and credit, and my comfort.
I am very well, considering my old age, and my travels and labours in the Lord`'s service,
which hitherto the Lord has given me strength and ability to perform,
I hope to his honour and the good of many.

There is some service before me in three or four counties in these northern parts,
which I am now entering upon, resigned to the will of God, whether to live or die.
George Rooke, my companion, who has hitherto been very serviceable and helpful,
is now leaving me and coming to Ireland, with Amos Strettle; so that I am left alone,
but hope the Lord will not leave me, who has been with me hitherto,
and blessed and prospered his work and service,
giving strength and ability beyond the ordinary course of nature;
blessed be his name forever.

And now, my son, it will be gladness to me, that you show yourself a man for truth,
in all your concerns; and if you truly fear God, you will learn wisdom,
which will give you credit and favour with the Lord and his people.

Remember my tender fatherly love to your brothers and sisters, and to my grandchildren,
desiring they may all do well, and so walk,
that no occasion may be given by any of them against the Lord`'s blessed truth,
or for defamation of themselves.
For in everything, wherein any sin against God and dishonour him,
they discredit and dishonour themselves: but all that honour the Lord in their conduct,
he honours, and will honour with many favours.
This is what offers at present from a tender careful father.

[.signed-section-signature]
William Edmundson

[.signed-section-context-close]
West Chester, the 12th of the Fifth month, 1697.

[.letter-heading]
=== To His Son

[.signed-section-context-open]
York, the 7th of the Sixth month, 1697.

[.salutation]
Son Tryal,

This may let you and the rest know, who desire to hear of my welfare,
that through the mercies of the Lord I am well,
and sensible of his renewing my strength every way,
to perform his service required of me,
which I hope will be to his praise and the good of many when I am gone.
My chief care is, that I may do my day`'s work in time, according to his will;
first in general, and secondly in particular for my children and offspring of my family.
To be clear of all men`'s blood in the day of account,
my service is more than ordinary in several things,
and strength and ability given accordingly.
The Lord is great, and greatly to be reverenced and feared; his wisdom is infinite,
and the ways of his judgments unsearchable.
My soul and spirit, in the sense of his wonders, in the depths of exercise,
admires his infinite goodness, and praises his holy name.

As I wrote in my last to you,
my children`'s folly is as a weapon in the hand of evil doers,
against the Lord`'s work in my hands; but the Lord,
who knows my heart`'s integrity and innocency,
out-balances all opposition with his irresistible power,
and crowns his testimony with dominion over all gainsayers; blessed be his name.
Yet it is a grief and sore trouble to be wounded
with an arrow that sprung from my own loins,
prepared through my children`'s folly for lack of the fear of God,
and reverence to such a father, whom the Lord has endued with many favours.
It ought to seize all your hearts and break them in a deep sense of bitter sorrow,
and be a warning to all of you, who are innocent,
to be watchful over your own ways in godly fear,
that you fall not into the like temptations, which dishonour God,
and are a blot and stain to their name, who fall into them,
not easily to be done away out of the memory of God and men.
A good name deservedly lost, is hard to regain: therefore you my son,
with the rest that are innocent, fear the Lord, love his truth,
take advice of approved elders,
which may be for your preservation in credit with God and good men; and experience shows,
that they who honour the Lord, he does honour them.
I was at Liverpool and Chester, thinking to come over with George Rooke,
but was not clear of this service which I am upon, and must not leave it until performed.

I earnestly desire you wilt be careful on your part, in the fear and wisdom of God,
to perform what you hast written, that I may have comfort of you:
for nothing in the world is so pleasant to me, as to see my children doing well,
walking in the blessed truth.
I have had many large and full meetings since George Rooke left me, in Cheshire,
Lancashire and thus far in Yorkshire; many Friends came far to meetings,
and the Lord`'s power answered their expectation,
and many honest hearts are thankful and glad of this labour of love.
I came this day to this city, and intend to stay their meeting tomorrow,
being first-day, and then as the Lord enables, to go towards Burlington,
Scarborough and Whitby; and when clear there,
through Bishoprick and Westmoreland into Cumberland, and if the Lord lengthen my time,
then to see you again.

I know not yet whether to ship at Liverpool, or go by land to Port-Patrick in Scotland.
I hope in the Lord`'s strength to be in Cumberland in three weeks from this date.
Remember my dear love to elders and honest Friends of our Monthly Meeting,
as if I named them one by one; and I charge you to give them a true copy of this,
and let them read it in the men`'s meeting, and it shall be a witness for me,
if I should not see your faces again.

And now my son, my prayers are for you, and my care is for your well-doing,
that your behaviour in all things may give you credit, and me comfort.
Show yourself a man in all concerns, and act in all things as in the sight of God,
who orders all things for the best, for them that fear him,
and cast themselves upon his ordering providential power, that rules all things.
It is safe to keep there out of all self-will and haste.

[.signed-section-signature]
William Edmundson

=== A Postscript to an Epistle from Leinster Province Meeting.

When the Lord first called and gathered us to be a people,
and opened the eyes of our understandings, we saw the exceeding sinfulness of sin,
and the wickedness that was in the world;
and a perfect abhorrence was fixed in our hearts against all the wicked, unjust, vain,
ungodly, unlawful part of the world in all respects.
We saw that the goodly and most lawful things of the world were abused and misused;
and that many snares and temptations lay in them,
with troubles and dangers of several kinds, which we felt the load of,
and that we could not carry them, and run the race the Lord had set before us,
so cheerfully as to win the prize of our salvation.
Therefore our care was to cast off this great load and burden, namely,
great and gainful ways of getting riches, and to lessen our concerns therein,
that we might be ready to answer Christ Jesus our Captain,
who had called us to follow him in a spiritual warfare,
under the discipline of his daily cross and self-denial.
Then the things of this world were of small value with us, so that we might win Christ;
and the goodliest things thereof were not near us, so that we might be near the Lord;
for the Lord`'s truth out-balanced all the world, even the most glorious part of it.

Then great trading was a burden, and great concerns a great trouble; all needless things,
fine houses, rich furniture and gaudy apparel, was an eye-sore.
Our eye being single to the Lord, and to the inshining of his light in our hearts,
this gave us the sight of the knowledge of the glory of God, which so affected our minds,
that it stained the glory of all earthly things; and they bore no mastery with us,
either in dwelling, eating, drinking, buying, selling, marrying, or giving in marriage.

The Lord was the object of our eye, and we were all humble and low before him,
self being of small repute.
Ministers and elders in all such cases, walked as good examples,
that the flock might follow their footsteps, as they followed Christ,
in the daily cross and self-denial, in their dwellings, callings, eating, drinking,
buying, selling, marrying and giving in marriage.
And this answered the Lord and his witness in all consciences,
and gave us great credit among men.

But as our number increased, it happened that such a spirit came in among us,
as was among the Jews, when they came up out of Egypt.
This began to look back into the world,
and traded with the credit which was not of its own purchasing,
striving to be great in the riches and possessions of this world.
Then great fair buildings, in city and country, fine and fashionable furniture,
and apparel suitable, dainty and voluptuous provision, rich matches in marriage,
and excessive, customary, uncomely smoking of tobacco came into practice,
under colour of being lawful and serviceable,
far wide from the footsteps of the ministers and elders whom the Lord raised up,
and sent forth into his work and service at the beginning;
and contrary to the example that our Lord and Master Christ Jesus left us,
when he was tempted in the wilderness with the kingdoms of the world,
and the glory of them, which he despised.

And of Moses, who refused the crown of Egypt,
and to be called the son of Pharaoh`'s daughter;
rather choosing affliction with the Lord`'s people--
having a regard to the recompense of reward.
And the holy apostle writes to the church of Christ, both fathers,
young men and children, advising against the love of the world, and the fashions thereof,
which are working as the old leaven at this very time, to corrupt the heritage of God,
and to fill it with briars, thorns, thistles, tares and wild grapes,
to make the Lord reject it and lay it waste.
But the Lord of all our mercies, whose eye has been over us for good,
since he gathered us to be a people, and entered into covenant with us;
according to his ancient promise, is lifting up his spirit,
as a standard against the invasion of this enemy,
and raising up his living word and testimony in the hearts of many,
to stand in and fence up the gap, which this floating, high, worldly,
libertine spirit has made, that leads from the footsteps of those that follow Christ,
and know him to limit them with his bounds, and dare not in their own will and time,
lay hold on presentations and opportunities to get riches, which many have had,
and refused for truth`'s sake, and the Lord has accepted thereof as an offering,
and rewarded them with great comfort, to the praise of his great name.

[.signed-section-signature]
William Edmundson

=== An Epistle to Friends in Barbados.

[.salutation]
My dear Friends,

You are in my memory in the ancient love of God, in which I visited you,
and laboured in your island, and those parts of the world,
to gather into the blessed unchangeable truth, and to settle and confirm you in it,
according to the ability and gift of God given to me,
and ministered to you in the demonstration of the spirit and power of Christ.
In this, the mysteries of faith and the discipline of the Gospel were unfolded to you,
for your settlement under Christ`'s government in the new covenant,
and to know the bounds and liberty of it, that you might walk in it in all things,
to the praise and honour of God, who called and gathered you to be a people;
and not turn to the elements of the world, nor be entangled,
neither carried away after the lust of the eye, the lust of the flesh, or pride of life;
but walk in the liberty of the new covenant, as lights in the world.
God has set limits for his people in his new covenant,
as he set bounds for the Jews in the old covenant, which they were to observe and do,
yet did not; but took liberty beyond the bounds of that covenant, and were cut off,
though they were the natural branches.

And now all inward Jews, who are circumcised with the spirit of Christ,
are to know the liberty of the Gospel of Christ, and the bounds of the new covenant,
and observe them in all things, that their doings may be to the praise and honour of God;
whether in eating, drinking, buying, selling, marrying or giving in marriage.
They are not to take liberty to themselves in their unsubjected wills,
to satisfy their carnal minds, in vanities and pleasures;
and so break God`'s new covenant, as the natural Jews did the old covenant.
Such fruitless branches will wither, and be cut off from God`'s people,
and be ranked with Adam in the fall, who broke God`'s covenant,
by going beyond the bounds that God set him, and was driven out of the garden of God.
So all that go into fleshly liberty, out of the cross of Christ and self-denial,
go into the earth, and into the pleasures and delights of it,
and are dead while they live.

Walk in the blessed and comely order,
established in the church of Christ by his spirit and power,
in his heavenly counsel and divine wisdom,
that all may be preserved from the evils and vanities that are in the world,
and grow up together in the faith of Jesus, and grace of God,
from one degree of strength and knowledge of Christ Jesus to another;
that through the exercise of your senses, in the law of the spirit of life in Christ,
you may be skillful in the word of righteousness,
to act for God in the unity of his holy Spirit, and fellowship of his light,
as co-workers together in his vineyard.
Thus all things may be kept clean and sweet,
and every weed and seed that God has not sown,
may be plucked up and rooted out of his garden,
which is to bring forth good and pleasant fruit to his honour,
that he may take pleasure to walk, and dwell in you, to sup and make his abode with you,
and in you, to your comfort.
And if it should be my lot in my old age to see you again,
I might be comforted in your faithfulness and growth in the blessed truth,
and a godly concern fixed in your minds, for the promotion of the government of it,
both in doctrine and discipline.

In this nation we are very peaceable, and truth prospers; Friends are in good esteem,
and a godly concern comes upon many,
to be devoted with their whole abilities to serve the Lord,
who gives them wisdom and understanding in the management of truth`'s affairs,
for the good of all.
And the Lord blesses their endeavours; so that in his spirit and power,
which is strong and mighty with us,
the authority of truth in church government is over all gainsayers;
and the close order of the Gospel is over all
loose libertine spirits and earthly worldlings;
and truth prevails to the great satisfaction of all the sincerely concerned,
and to the praise and honour of God.
Amen.

The parliament is now sitting in Dublin, where I, with several Friends attend,
and they are very loving and kind to us--ready to do us good,
and to ease us in what they reasonably can, and have a regard to us in acts that pass.
The Lord is to be admired in the care he takes of his people who trust in him,
and cast their care upon him, and seek his honour before all private interest;
such the Lord is honouring; everlasting praises to his name.

My sincere love, in the unchangeable truth, is to you all, and my prayers to God for you.

[.signed-section-signature]
William Edmundson

=== Concerning Men`'s and Women`'s Meetings.

[.salutation]
Dear Friends, Brethren and Sisters;

Let us seriously consider the great and weighty
service of our men`'s and women`'s meetings,
to order and manage matters relating to Gospel order in the church of Christ,
to the honour of God and his blessed unchangeable truth, made manifest to us,
that we may be preserved faithful therein,
and our lights may shine in the comely order thereof,
by the good fruits brought forth among us, the Lord`'s peculiar people in this generation,
as good examples to others, and as lights in the world.
Men`'s and women`'s meetings had need to have a special godly care,
to see that all their members keep within the bounds of truth in the way of the Lord,
to do justice and judgment, as the children and household of Abraham,
that the promise of God`'s blessings to Abraham and his seed may rest upon us.

My Friends, it is no small charge,
that the Lord commits to the care of the aforesaid meetings, the care of his flocks,
the preservation of the testimony of truth, and the honour of his great and worthy name:
so that it is of absolute necessity for all the members, both male and female,
to know their election, and in what it stands,
and in what authority they sit in those meetings;
for the service thereof must be performed in the
wisdom and counsel of the Lord Jesus Christ,
and in the authority of his blessed spirit and power.
For the things of God knows no man; but the spirit of God, in which the election stands,
and this is that which fits for the Lord`'s service in his church,
as he has appointed everyone to his service and office.
We know that our men`'s and women`'s meetings for the Lord`'s service in his church,
were ordained of God,
and settled among us in the authority and by the
assistance of his blessed spirit and power,
and committed to the trust and care of faithful men and faithful women,
to keep them up in the spirit and power of.
God, in which they were set up:
testimonies whereof may be seen in many comfortable
epistles written to men`'s and women`'s meetings,
for all the members to keep their possession in
the spirit and power of the Lord Jesus Christ.

This is,
and was the Lord`'s way in the settling of his church and people under his government.
For when the Lord`'s ancient people came out of Egypt by a high hand,
the Lord gave them laws and statutes to keep and do, and appointed elders,
as judges and overseers, to see that they kept the Lord`'s way, which he prescribed,
and to do justice and judgment, as Abraham commanded his household after him.
And those elders and overseers were of God`'s appointing,
and known by the people to be men qualified for the service;
such unto whom the Lord gave of his good spirit,
which opened their understandings to make a true
inspection into matters that came before them,
to do justice and judgment, according to the law of God.
And when such elders or overseers ruled, as were thus rightly elected,
and walked by the rule of the Lord`'s good spirit, they were a blessing to the people,
and the Lord was with them: but when others came to sit in the assemblies, as elders,
overseers and judges, not appointed of the Lord, neither guided by his spirit,
what calamity then came upon Abraham`'s household.

Likewise in the primitive times, when many in various places, both of Jews and Gentiles,
were gathered to the faith in Christ Jesus, and churches or meetings were established;
then faithful men who were qualified for that service,
were appointed as elders or overseers by the approbation of the holy Ghost,
to take the oversight of the flock of Christ,
to see that all who professed faith in Christ, should walk in his doctrine,
as it was first delivered by Christ and his holy apostles;
and to see that the testimony of Jesus was kept in all its branches,
that the comely order of the Gospel might be shown forth in them to unbelievers,
as lights in the world; that if any could not be won by the word and doctrine,
the witness of God in them might be reached by the just
and good examples of the churches of Christ.

And those qualified elders and pastors,
whom the holy Ghost made overseers in the churches, were to feed them in due season,
not of constraint, but of a willing mind; neither for selfish gain, but for truth`'s sake;
neither as lords over God`'s heritage, but examples to the flock,
and to do justice and judgment without partiality; being faithful men,
sanctified with truth, seasoned with the grace of God,
and gifted with a good understanding in church affairs, relating to Gospel discipline;
having their senses well exercised in the law of God, to know what was for truth,
and what was against truth;
and accordingly to permit nothing to be ushered
into the church of Christ that was against truth;
but as doorkeepers in the Lord`'s house,
to stand in and for truth`'s testimony against
everything that would lessen the credit thereof.

But when the faith of Jesus was departed from, and self-interest got into the churches,
then this godly care and holy discipline went to decay, and earthly wisdom,
carnal reasoning, worldly policy, riches,
greatness and literal learning swayed the counsels in church affairs.
And now the Lord is raising up those ruins, and putting his church in its ancient order,
settling those meetings of faithful members,
to be kept up in the authority of his spirit and power,
wherein neither riches nor policy must rule;
but in all such meetings about the Lord`'s business, the Lord must be chairman,
ruler and judge,
whose good spirit of heavenly wisdom and divine
counsel must rule in the hearts of his people,
who sit with him in that weighty service of church government;
for it is in the gift of the Lord`'s good spirit,
that the ability stands to perform that service as well as doctrine.
If any undertake it otherwise, they miss their way, mar the work,
and instead of being helpmeets in government, do many times cause trouble in the church.

[.signed-section-closing]
This from Your ancient friend and brother,

[.signed-section-signature]
William Edmundson
