== Chapter VIII

[.chapter-synopsis]
* His various travels, perils and exercises, both by sea and land in America, where he went in the service of the Gospel, in 1671
* The vision he had in his return, concerning an approaching scarcity for two years; though then a time of plenty

In the year 1671, I had movings upon my spirit to travel to the West Indies,
which thing had remained with me for some time.
I went to the Half-year`'s Meeting at Dublin in the third month,
where I acquainted Friends with my intended journey, who had unity therewith,
and the Lord`'s presence and power appeared mightily among us, to our great comfort,
confirmation and satisfaction.
When the service of the meeting was over,
I parted there with my wife and Friends in much tenderness,
under a heavenly sense of the Lord`'s presence; took shipping, and landed near Liverpool.
From there I traveled to London, and came there on the first day of the Yearly Meeting,
and abode until the meeting was over.
I also stayed some weeks visiting Friends in their meetings.

Several Friends in the ministry were there,
ready to go to the West Indies in truth`'s service, namely: George Fox, Thomas Briggs,
John Stubbs, James Lancaster, Robert Widders and others.
We went together in one vessel, bound for Jamaica, but intended to touch at Barbados.
We had many precious comfortable meetings aboard the ship,
but in our voyage were chased by a pirate, a Salleeman,
which in a moonlight night came up with us, and was ready to board us,
but immediately a cloud covered us,
and a fresh gale of wind out of the cloud carried us clear away.
Thus the Lord eminently saved us out of their hands,
and we were afterwards certainly informed who he was.

Several of us landed in Barbados, in the eighth month, 1671, and James Lancaster,
John Cartwright and George Pattison went in the ship to Jamaica.
At Barbados we had great service for the Lord and the good of the people;
many were convinced and turned to the Lord, and brought into the way of life and peace.

After we had laboured there some time in the service of truth, Thomas Briggs,
my fellow traveller, and I were moved of the Lord to visit the Leeward Islands,
and Colonel Morris of Barbados would go with us.
So we took shipping, and in four days landed in Antigua, where we had great meetings,
and many were convinced and turned to the Lord.
Several justices of the peace, officers and chief men came to the meetings,
and confessed to the truth which we declared in the power of God.
This soon went abroad and alarmed the other islands.

When we were clear to leave Antigua,
we found our spirits drawn to visit the island of Nevis.
Colonel Winthrop, who had been governor of Antigua, being convinced,
he and his family received the truth,
and we had several large heavenly meetings in his house.
He would go with us to Nevis, and having a vessel of his own, shipped us in it,
with himself, Colonel Morris, their waiting-men and seamen.
We set sail from Antigua, and in the way we touched at a little island called Barbada,
where we made a short stay, and had some service for truth.

Then we sailed to Nevis,
and when we came near the island I was under great exercise of spirit,
for I found something working against us and the testimony we had to bear for God.
I told the two colonels, that there was something working against us,
and desired them as soon as we dropped anchor, immediately to go ashore in their boat,
and not to stay dressing and trimming themselves, as they and such persons use to do,
so would they only be taken notice of, being great persons:
and perhaps we might come privately after them,
and get some service for truth among the people in the island,
before we were taken much notice of;
but they thought their great name would have gone over all opposition.

When they came to anchor, they went to trim and dress themselves as usual;
which took up some time.
I was under a weight of trouble; and when they were ready to go on shore,
a marshal came aboard, with orders from the governor, that none should come ashore,
until he knew from where the vessel came, and who were in her.
Then we were all kept aboard the vessel, and a messenger sent to the governor,
who presently sent an officer and soldiers aboard,
with strict command that none of us should go ashore,
or any come from shore to speak with us, upon penalty of a great fine;
but the officer and soldiers were very kind,
and allowed several Friends to come aboard to visit us.
There were several honest tender Friends in that island,
who were joyful at our coming to visit them;
they ventured their fines and came aboard to us,
and we were refreshed together in the Lord Jesus.

The governor sent for the master of the vessel, who was no Friend,
and bound him in a bond of one thousand pounds sterling, to carry us back to Antigua.
There came on board, one Colonel Stapleton, who was governor of Mountserrat,
and several men of account with him.
I told them, it was very hard usage, that we being English men,
and coming so far as we had done to visit our countrymen,
could not be admitted to go on shore, to refresh ourselves,
within King Charles`' dominions, after such a long voyage.
Colonel Stapleton said it was true, but, said he,
we hear that since your coming to the Caribbean Islands,
there are seven hundred of our militia turned Quakers; and the Quakers will not fight,
and we have need of men to fight, being surrounded by enemies,
and that is the very reason why Governor Wheeler will not allow you to come ashore.

By the order of the governor we were carried back to Antigua,
where we were received with gladness and had great service,
many of all sorts flocked to meetings, and generally confessed to the truth.
When our spirits were clear of the service in that island, we returned to Barbados.

My companion, Thomas Briggs, being taken very sick.
Colonel Winthrop took us to Barbados in his own vessel, and went along with us,
he having received the truth in the love of it.
When we came to Barbados, Friends were glad,
and George Fox was there in the Lord`'s service.
We had many large precious meetings,
the Lord`'s power and presence accompanied his testimony and work committed to us;
and many were brought into the way of life and peace with God.

When we were clear in our service, we took shipping for Jamaica, namely: George Fox,
Robert Widders, Solomon Eccles, Elizabeth Hooton and I,
and after being about ten days at sea, we landed at Port Royal in Jamaica.
We traveled much in that island,
and had good service in gathering people to the Lord Jesus Christ,
and settling meetings among them.
James Lancaster and I traveled over an eminence called Mount Diabolo,
to the north side of the island,
where the people received us gladly and came to meetings,
several were convinced and received the truth;
and we settled a meeting there for the worship of God.

After some time of labour in the Gospel of Christ,
having finished our service in that island, we committed them to the Lord`'s keeping,
and took shipping for Maryland; but Elizabeth Hooton died in Jamaica,
being an ancient woman.
We left Solomon Eccles there in truth`'s service,
and the rest of us shipped with George Fox for Maryland.
We had great exercise and perils in this voyage, in the Gulf of Florida,
being sorely distressed with contrary wind and tempestuous weather,
which lay heavy upon us several days and nights.
We were also much bruised and tired; but the Lord had mercy upon us,
who commands the winds and lofty waves of the sea to be still, and they obey him.
By the Lord`'s providential hand we also escaped
an imminent danger of being taken by a privateer.
At length we got within the Cape of Virginia, and up the great Bay of Chesapeake,
to the mouth of the Patuxent river in Maryland, where we anchored;
but a violent storm arising we could not get ashore for some days,
though our provisions and water were spent.
When the storm ceased, Friends hearing of us, came in a boat and fetched us ashore.

Here we met with John Burnyeat ready to take shipping for England.
We had several large heavenly meetings, and the Lord`'s power and presence were with us,
to our great comfort.
Then we traveled severally in our services, as the Lord ordered us.
George Fox, John Burnyeat, and several other Friends accompanying them,
traveled to New England.
I took boat and went to Virginia, where things were much out of order;
but the Lord`'s power and testimony went over all.
When I had got several powerful meetings among them and their minds a little settled,
so that truth had got some hold,
I appointed a men`'s meeting for settling them in the way of truth`'s discipline.

Afterwards, it being upon me, I traveled to Carolina, and two Friends accompanied me,
it being all wilderness and no English inhabitants or path-ways,
but some marked trees to guide people.
The first day`'s journey we did pretty well, and lay that night in the woods,
as we often used to do in those parts.
The next day being wet weather we were sorely foiled in swamps and rivers,
and one of the two who were with me for a guide,
was at a stand to know which way the place lay we were to go to.
I perceiving he was at a loss, turned my mind to the Lord, and as he led me,
I led the way.
So we traveled in many difficulties until about sunset; then they told me,
they could travel no farther; for they both fainted, being weak-spirited men.
I bid them stay there, and kindle a fire, and I would ride a little farther,
for I saw a bright horizon appear through the woods,
which travellers take as a mark of some plantation.
I rode on to it, and found it was only tall timber trees without underwood.
But I perceived a small path, which I followed until it was very dark,
and rained violently; then I alighted and set my back to a tree, until the rain abated.
It being dark, and the woods thick, I walked all night between two trees;
and though very weary, I dared not lie down on the ground,
for my clothes were wet to my skin.
I had eaten little or nothing that day, neither had I anything to refresh me but the Lord.
In the morning I returned to seek my two companions,
and found them lying by a great fire of wood.
I told them how I had fared; and he that should have been the guide,
would have persuaded me that we were gone past the place where we intended;
but my mind drew to the path which I had found the night before.
So I led the way, and that path brought us to the place where we intended, namely:
Henry Phillip`'s house by Albemarle river.

He and his wife had been convinced of the truth in New England, and came here to live;
and not having seen a Friend for seven years before, they wept for joy to see us.
It being on a first-day morning when we got there, although I was weary and faint,
and my clothes wet,
I desired them to send to the people thereaway
to come to a meeting about the middle of the day,
and I would lie down upon a bed, and if I slept too long, that they should awake me.
Now about the hour appointed many people came, but they had little or no religion,
for they came and sat down in the meeting smoking their pipes.
In a little time the Lord`'s testimony arose in the authority of his power,
and their hearts being reached by it,
several of them were tendered and received the testimony.
After meeting they desired me to stay with them, and let them have more meetings.

One Tems, a justice of the peace, and his wife were at the meeting,
who received the truth with gladness,
and desired to have the next meeting at their house, about three miles off,
on the other side of the water; so we had a meeting there the next day,
and a blessed time it was; for several were tendered with a sense of the power of God,
received the truth and abode in it.

1672+++.+++ I could stay no longer with them at that time,
for I had appointed a men`'s meeting in Virginia, to be on the fifth-day of that week,
things being much out of order among them.
I therefore took my leave of them in the love of God,
and began my journey on third-day morning, with my two fellow travellers.
I had ridden but a few miles before I was seized with grievous pain,
and a weakness in my bowels,
occasioned by the great cold I got with those hardships in coming there.
I rode in great pain that day, and at night lay in the wilderness.
Soon after we alighted off our horses, my two fellow travellers,
who should have helped me, fell sick and fainted.
So I was forced to rise, kindle a fire and fodder the horses.
After some time they recovered from their fainting fit.
The Lord was merciful, and bore up my spirit that night,
and the next day we got to Virginia to the men`'s meeting,
and the Lord`'s power was with us,
and Friends received truth`'s discipline in the love of it,
as formerly they had received the doctrine of truth,
for which they were great sufferers in the spoiling of their goods,
the governor being a very peevish man, and much set against truth and Friends.

Friends desired to have another men`'s meeting before I left those parts;
so we appointed another, the time and place being mentioned.
In the mean time I traveled to several places in that country,
and had comfortable meetings with Friends, and traveled thirty miles above Jamestown,
to a place called Green-springs, where were several convinced people.
A meeting had been settled there, but was lost,
the people being stumbled in their minds and scattered
by the evil example of one Thomas Newhouse,
who had been a preacher among them,
and went from truth into the uncleanness of the world.
I got them together and settled a meeting; they were glad thereof and much comforted,
as sheep that had been astray, and returned again to the Shepherd, Christ Jesus.
So I left them tender and loving.

As I returned, it was laid upon me to visit the governor.
Sir William Barclay, and to speak with him about Friends`' sufferings.
I went about six miles out of my way to speak with him, accompanied by William Garret,
an honest ancient Friend.
I told the governor, that I came from Ireland, where his brother was lord lieutenant,
who was kind to our Friends; and if he had any service for me to his brother,
I would willingly do it; and as his brother was kind to our Friends in Ireland,
I hoped he would be so to our Friends in Virginia.
He was very peevish and brittle,
and I could fasten nothing upon him with all the soft arguments I could use;
so when I had done my endeavours and was clear, I left him.

I came that night to Justice Taverner`'s house, his wife was a Friend,
and he loving to Friends.
The next day was the men`'s meeting at William Wright`'s house,
the justice and his wife went to the meeting, about eight or nine miles,
and several other persons of note came to the meeting, particularly Richard Bennet,
alias Major General Bennet, and Colonel Teve, with others, and a great many Friends.
Some came a great way to that meeting, and a blessed heavenly season it was;
many were tendered by the Lord`'s power, and the witness of God reached,
which answered to the truth of the Lord`'s testimony,
which was declared to them in his power.
We had first a meeting for the worship of God;
then Friends drew into a large upper room to the men`'s meeting,
where I was with them in settling the affairs of the church.
Justice Taverner`'s wife came to me, and told me, that the Major General, Colonel Teve,
and others were below, staying to speak with me; so I went down to them.
They were courteous, and said they only stayed to see me,
and acknowledged what I had spoken in the meeting was truth.
I told them the reason of our Friends`' drawing apart from them was,
to lay down a method to provide for our poor widows and fatherless children;
to take care that no disorders were committed in our Society; and that all lived orderly,
according to what they professed.
I also informed them, that in England and other places,
we had such meetings settled for that service.
The Major General replied, he was glad to hear there was such care and order among us;
and wished it had been so with others.
He further said he was a man of great estate, and many of our Friends were poor men,
therefore he desired to contribute with them.
He likewise asked me how I was treated by the governor,
having heard that I was with him.
I told him that he was brittle and peevish, and I could get nothing fastened on him.
He asked me if the governor called me dog, rogue, etc. I said, no, he did not call me so.
Then said he, you took him in his best humour,
those being his usual terms when he is angry,
for he is an enemy to every appearance of good.
They were tender and loving, and we parted so,
the Major General desiring to see me at his house, which I was willing to do,
and accordingly went.
He was a solid, wise man, received the truth and died in the same,
leaving two Friends his executors.

When I had been some time with Friends in Virginia,
and had many sweet serviceable meetings among them, and things somewhat settled,
I found my spirit clear of that service, and took boat and went back to Maryland,
where I stayed several meetings, the Lord`'s power and presence accompanying,
which made hard things easy.
When I was clear there, I took passage by sea,
and about ten days after landed safe at New York, where no Friends lived.
John Evans, of Jamaica, being in my company at that time,
we lodged at a Dutch woman`'s house, who kept an inn.
I was moved of the Lord to get a meeting in that town,
for there had not been one there before;
so I spoke to the woman of the house to let us have a meeting, who was very willing,
and let us have a large dining room, furnished with seats.
We gave notice thereof, and had a large and good meeting, some of the chief officers,
magistrates and leading men of the town being at it, who were very attentive,
the Lord`'s power being over them all.
Several of them appeared very loving after the meeting.
The woman of the house and her daughter being widows, both wept when we went away.

From there I went to Long Island, where were many honest tender Friends;
and having several meetings with them,
we were well refreshed and comforted together in the Lord.
From there I went to Shelter Island, where I met with George Fox again,
and several Friends with him, coming from New England and going to Virginia.
I told him of my travels and service for the Lord, at the hearing of which he was glad,
and we praised the Lord for his goodness.
I told him that I was much pressed in spirit to hasten for Ireland;
he said that Friends in New England had heard of me, and expected I would visit them,
and besides, the passage of ships from those parts was stopped,
by reason of war between Holland and England.
I told him, I believed I should not wait long for a passage,
for the Lord pressed me for Ireland, and I believed there was need of my service there.
After being two or three days together at Shelter Island, we took leave one of another,
and parted in the sweet love of God.

After some day`'s travel by Narraganset, and those parts, I came to Rhode Island,
where I met with John Burnyeat, John Stubbs and John Cartwright.
Roger Williams, a priest and an enemy to truth, had put forth fourteen propositions,
as he called them,
which he would maintain against any of the Quakers who came from Old England,
and challenged a dispute on seven of them at Newport in Rhode Island,
and on the other seven at Providence.

I joined with Friends in answering this challenge at
the time and place appointed for the dispute,
which was to be in Friends`' meetinghouse at Newport;
where a great concourse of people of all sorts gathered.
When those propositions, as he called them, came to be discoursed of,
they were all mere slanders and accusations against the Quakers;
the bitter old man could make nothing out,
but on the contrary they were turned back upon himself.
He was baffled, and the people saw his weakness, folly,
and envy against the truth and Friends.

There were many prejudiced Baptists,
who would eagerly have helped the priest against Friends;
but they dared not undertake his charge against us, for they saw it was false.
The testimony of truth in the power of God, was set over all his false charges,
to the great satisfaction of the people.

When this meeting was ended, which lasted three days,
John Stubbs and I went to Providence, accompanied by many Friends,
to hear the other seven propositions, which lasted one day,
John Burnyeat and John Cartwright going another way in truth`'s service.
At Providence there was a very great gathering of people, Presbyterians,
Baptists and Ranters.
Roger Williams being there, I stood up and told him in public,
we had spent many days at Newport,
where he could make nothing out agreeable to his challenge;
but on the contrary manifested his clamour, rash and false accusations,
which he could not prove against us;
and that I was not willing to spend much time
now in hearing his clamour and false accusations,
having other service for the Lord, therefore would only spend that day.
So he went on, as he had done at Newport, in Rhode Island.
We answered to all his charges against Friends, and disproved them.

The prejudiced man was silenced; and then the professors desired to know our belief,
what the soul of man was made of.
I told them, I believed what the Scriptures said, that when God made man,
he breathed into him the breath of life, and he became a living soul;
and that it was sufficient for me to know Christ Jesus who redeemed my soul.
But if any of them, who were great professors and old disputants,
would undertake to show, of what God made the soul of man, he might.
One who was an ancient leading man among them said, he would not meddle with it,
and this ended the dispute.
We had a seasonable opportunity to open many things to the people,
appertaining to the kingdom of God and way of eternal life and salvation.
The meeting concluded in prayer to Almighty God
and the people went away satisfied and loving.
Next day we had a meeting at Warwick, not many miles from there;
to which most of those people came,
and the Lord`'s power and presence were largely manifested;
and after the meeting the people were very loving, like Friends.

From there John Stubbs went to Narraganset to meet John Burnyeat,
and I went to Rhode Island by boat, and stayed some meetings there with Friends,
and was well refreshed together with them in the Lord.
From there to Sandwich, and had a good meeting with Friends, and another at Scituate;
so to Boston, and had one meeting there, where was a ship ready to sail for Ireland;
and being pressed in spirit to hasten over, I went aboard, and that day we set sail.
The master of the ship was kind, and when I wished to have a meeting,
if I told him of it, he would go upon the deck, and call all the people,
and stay until I ended the meeting: his name was Thomas Edwards, a New England man.

In three weeks time we made land in Ireland, a readier passage being seldom known;
when we came up with the land of Ireland, the wind turned north east,
and a great storm arose, which cleared our way from pirates,
there being then three Dutch privateers, watching the harbours of Cork,
Kinsale and Youghal.
This storm took them from the shore to the southward;
so the next day we got into Youghal, before they returned to their post.
There being two guns on board our ship, when we came into the harbour,
the seamen would have fired them, as their custom is;
but the master would not allow them, saying, they were blind who could not see,
that it was not guns that delivered them from their enemies;
and he believed in his conscience, it was for my sake they were preserved;
and if I would go back with him to New England, he would give me my passage free.
I told him there was a fine of a hundred pounds,
on any master of a ship that should bring a Quaker to New England;
he said he would venture that, if I would go with him.
He was really convinced of the truth,
and made sensible that the Lord`'s power was with me; for after I landed,
and the ship was unladen, as they were going to take in fresh loading,
the privateer came again, and took it between Cork and Youghal,
for which he paid a ransom of two hundred pounds.

While I was at sea in that voyage, as I lay retired in my cabin,
a heavenly vision came over my senses,
and in it appeared two very poor ill-favoured cows, which arose under my plough-beam,
as I was holding my plough.
Whereupon I sat up in my cabin, and considered the matter.
Then the word of the Lord came to me, and said, the two cows are two years,
for there shall be two very dear years;
and inasmuch as the cows arose under the plough-beam, they shall fall on corn and cattle.
This came to pass in a very little while: in the time of great plenty,
contrary to men`'s reason, cattle died abundantly,
and the price of corn rose to an extraordinary height,
so that many were famished for lack of bread;
and several families who had lived plentifully, were forced to go a begging,
their corn being spent and cattle dead.
Several families who were ashamed to beg,
shipped themselves for servants to the West Indies, to get food;
and many in this nation would gladly have worked for food and could not get employment.

When I landed, I went to Cork to the Province Meeting, which was at hand;
and presently found there was cause for my spirit to be pressed,
to hasten over for the preservation of the church`'s peace,
some being gone into the loose foolish imaginations of Muggleton and others,
both in England and of this nation, into looseness,
and the liberty of their wills and carnal affections, from the cross of Christ,
and self-denial, which caused great trouble and difference among Friends, both at Cork,
Dublin, and several other places.
We had much exercise before we got things brought into order, and settled;
but the Lord`'s power was with us, and went over all,
and He still gave an understanding to place judgment in the right line;
praises to his name forever.
Honest tender Friends, who kept their habitation in the truth,
were very glad of my coming in such a time of need.
So I laboured with them in this nation, both in the ministry and church government,
according to the ability and gift that Christ gave me.
