== Preface

[.salutation]
Friendly Reader,

It hath pleased Almighty God, in the riches of his love and mercy,
from the time transgression first entered,
whereby man lost his primitive state of felicity with his Creator in paradise,
to give some manifestation of his good spirit, and revelation of the promised Seed;
in order to man`'s restoration from death to life,
whereby the serpent`'s head hath been bruised in some, through faith therein,
as by holy record doth appear; of which number, in early time, righteous Abel was one,
whose offering and person the Lord accepted, and had respect unto.
There were also some others, in the succeeding generations before the flood, as Enoch,
who walked with God in well-pleasing; and Noah, a preacher of righteousness;
although the ungodly world in general rebelled against it,
to their destruction and overthrow.

After the deluge, the holy patriarchs, Abraham, Isaac, Jacob, Joseph and others,
by faith in this holy Seed, were sanctified, obtained a good report,
and wrought righteousness in their generations,
before the law was given from mount Sinai.
And even in the time of the law, righteous men and prophets had faith therein,
being inspired thereby; yet many of the Jews, who had the law,
and were zealous in the outward performances thereof,
not having a due regard to the Seed or Word nigh in their hearts, recommended by Moses,
which would have sanctified them, and made their hearts contrite before the Lord,
rebelled against him who gave them of his good spirit to instruct them;
and though zealous for the ceremonies, yet rejecting their immediate Monitor,
they neglected the weightier matters of the law, and leaned upon outward observations;
wherefore their offerings, sacrifices, sabbaths, set feasts and solemn assemblies,
although required and appointed in that dispensation,
became loathsome and an abomination to the Lord;
but such who in uprightness of heart observed the law, were accepted of God,
yet looked for a more glorious dispensation to come.

The visible dispensations of God to men have been various, as by angels,
the law from mount Sinai, the ministry of the prophets and John the Baptist,
sent in the spirit and power of Elias, to prepare the way of the Lord.
All which dispensations had a glory in them for their time,
though but preparative to one more glorious yet to be revealed.
Then, in the fulness of time, Christ Jesus, the Seed of the woman,
the Messiah and hope of Israel, was manifested in the flesh,
whose day many prophets and righteous men desired to see, and could not,
only by faith at a distance, by reason of death.

Now was salvation brought nigh, the kingdom of heaven at hand,
and the glad tidings of the Gospel preached to the seed of Abraham;
the glory of former dispensations began to wax dim, to such as beheld his glory,
which excelled, even the glory of the only begotten of the Father,
full of grace and truth; yet many of the Jews could not see it so,
nor understand his voice, preaching the kingdom of God in parables,
and uttering things that had been kept secret from the foundation of the world;
or believe on Him, concerning whom, Moses in the law and the prophets did write;
but despised and rejected Him, although the mighty works,
and great miracles which he wrought among them, by the power of his Father,
declared him to be the Son of God.

Howbeit, the most glorious Gospel-day was not yet fully revealed,
at least with respect to the Gentiles, whilst our Saviour was in the prepared body,
sent only to the house of Israel, in the form of a servant,
to fulfil the law and prophets, and things that were written concerning him;
but after he had done that work, which the Father had given him to do, in that holy body,
and finished the same, by the offering up of himself unto God, as a lamb without spot,
a propitiation for the sins of the whole world, he rose again from the dead,
appeared to confirm his disciples, and ascended into glory,
at the right hand of his Father.
Then an open door was set before both Jews and Gentiles, by Jesus Christ,
who had consecrated a new and living way through the veil, that is to say, his flesh,
and abolished the old covenant, sacrifices, ceremonies, and hand-writing of ordinances,
taking it out of the way, and nailing it to his cross,
and openly triumphed over principalities and powers.

Now the old covenant was to pass away, and the new covenant to be established,
and the priesthood changed, by the great High Priest without sin,
and higher than the heavens; made not after the law of a carnal commandment,
but by the power of an endless life, a priest for ever, after the order of Melchisedec.
The law was now to go forth of Sion, from the great Law-giver, and written in the heart,
even the law of the spirit of life in Christ Jesus,
that sets free from the law of sin and death.
Now was the spirit poured forth from on high,
in a more plentiful manner upon mankind than in former dispensations,
and eminently on believers; whereby many were qualified and anointed,
both of Jews and Gentiles, as priests and ministers of the Lord,
to attend at his holy altar, in his temple not made with hands,
and to offer up spiritual sacrifices, acceptable to God by Jesus Christ.
And the holy apostles, commissioned and endued with power from on high,
were to teach all nations, baptizing them into the name of the Father, and of the Son,
and of the holy Ghost, having assurance from Christ,
of his being with them to the end of time.
By their ministry, and others whom the Lord sent forth, many were converted to God,
and added to the church, both of Jews, Greeks, and other nations;
being all baptized by one spirit into one body, or church,
which was glorious in that day, as a woman clothed with the sun,
having the moon under her feet, and upon her head a crown of twelve stars:
and she brought forth a man-child, who was to rule all nations;
but he was caught up unto God, and to his throne, from the great red dragon,
that sought to devour him as soon as he was born.

Then the woman, or true church, left, her visible glory, and fled into the wilderness,
or obscure place, from the face of the serpent, into a place prepared of God,
where she was nourished for a time, times, and half a time,
or a thousand two hundred and threescore days, which, in a prophetic sense,
is taken to be so many years.
And though the dragon sought to drown the woman,
by casting waters out of his mouth as a flood after her, yet the earth helped her,
and swallowed them up.
But a third part of the stars of heaven, or such as had shined as stars in the church,
were drawn to the earth by the dragon`'s tail.
There was a great falling-away from the faith of Jesus,
as had been foreseen and prophesied of by the holy apostles of the Lamb;
the light of Sion was eclipsed and much veiled, or withdrawn for a season;
and a general apostacy came over professed Christians.
The smoke of the bottomless pit arose, which darkened sun and air;
and out of the smoke came locusts upon the earth, which tormented men.
And the dragon was wroth with the woman, and made war with the remnant of her seed,
that kept the commandments of God, and had the testimony of Jesus Christ.
And he gave unto the monstrous beast, that arose out of the sea, or raging heathen world,
his power and his seat, and great authority,
who opened his mouth in blasphemy against God, his tabernacle,
and them that dwell in heaven; and those that dwelt on the earth worshipped him,
whose names were not written in the Lamb`'s book of life.

Next arose out of the earth, a place more settled than the sea,
a beast with two horns like a lamb, but spake as a dragon,
and exercised the power of the first beast, causing an image to be made for him,
unto which he had power to give life, so as to speak,
and cause as many as would not worship the image, to be killed: and both small and great,
rich and poor, free and bond, to receive a mark in their right hand,
or in their foreheads; and that no man might buy or sell, save he that had the mark,
or the name of the beast, or the number of his name.

This beast appears in show somewhat Christian,
and under pretence of the Lamb`'s authority, though acted by the dragon`'s power,
derived from the first beast,
compelleth men to comply with such traditions and ceremonies, for Christian duties,
as resemble the customs of the heathen, in their idolatrous worship and superstition;
for denying which, and testifying against the same,
many faithful followers of Jesus suffered martyrdom,
as their predecessors had done before, under the heathen power, or first beast.

Now mystery Babylon, the great, the mother of harlots, and abominations of the earth,
was exalted and sat on the beast with ten horns, as queen and bride,
pretending to be the true church, and spouse of Christ, decked with gold,
precious stones, and pearls, having in her hand a golden cup full of abominations,
and filthiness of her fornications,
being drunk with the blood of the saints and martyrs of Jesus.
And all nations drank of the wine of her fornication,
and the kings of the earth committed fornication with her;
and the merchants of the earth waxed rich through the abundance of her delicacies.
But she shall fall, and become an habitation of devils,
and the hold of every foul spirit, and cage of every unclean and hateful bird.
The Lord is calling his people out of her, that they be not partakers of her sins,
and that they receive not of her plagues, which shall come in one day, death,
and mourning, and famine; and she shall be utterly burnt with fire;
for strong is the Lord God who judgeth her.
And her merchants shall stand afar off, for the fear of her torment, weeping and wailing.
And as a millstone cast into the sea,
so with violence shall that great city Babylon be thrown down.

And now the man-child, the Lord from heaven, is again revealed in many of his saints;
who by the breath of his mouth, and brightness of his coming,
shall destroy the man of sin,
that hath wrought with all deceivableness of unrighteousness,
by signs and lying wonders in them that perish.
And the true church is returning out of the wilderness, leaning on her beloved;
and shall again appear in her comeliness and beauty, as a bride adorned for her husband.
To her light shall the Gentiles come, and kings to the brightness of her rising,
for the glory of the Lord shall arise upon her, and his light shine therein for ever.
The glorious prophecies of the holy prophets, and servants of the Lord,
concerning the latter days must be fulfilled.
The knowledge of the Lord shall fill the earth, as the waters cover the sea.
The abundance of the sea, or multitudes of people, shall be converted to Sion,
the nations shall flow together to the goodness of the Lord,
and be gathered to Jerusalem, that is from above, to worship the great King,
the Lord of hosts, upon his holy mountain,
that shall be established on the top of the mountains, and exalted above the hills,
and no hurt or destruction shall be there.
The Lamb shall lead his people, and feed them in the pastures of life,
and bring them to living fountains of water.
The Heir of all things shall inherit his right, and possess the gates of his enemies,
who in due time shall all be put under his feet.
He shall judge among the nations, and rebuke many people.
They shall beat their swords into plow-shares, and spears into pruning-hooks,
and come under the peaceable government of the Lamb.
For he is King of kings, and Lord of lords,
and of the increase of his government and peace there shall be no end.
And blessed be the Lord,
many in this day have in measure witnessed the fulfilling of many of these prophecies,
as they relate to particulars, and do know, that the Son of God is come,
who hath given them an understanding, whereby they know him that is true,
and that they are in him that is true, even Jesus Christ, the true God and eternal life;
in whom all the promises of God are and shall be fulfilled in their season.

And now the glorious Gospel is again preached, in and to them that dwell upon the earth,
that all may fear God, and give glory to his name;
and worship him who made heaven and earth, the seas and fountains of water;
and no longer worship the beast, or his image, or receive his mark,
lest they be cast into the lake that burns with fire for ever.
For the hour of God`'s judgments is come, both upon the beast, and all that worship him;
and his wrath is revealed from heaven,
against all unrighteousness and ungodliness of men, who hold a profession of the truth,
or Christian religion, in an unrighteous conversation.
For the night of apostacy is far spent, in these northern Islands especially,
and the day of the Lord at hand; the gross darkness,
which hath covered the hearts of many, is in a great measure dispelled,
and the true light again shineth,
that makes manifest and discovers whatsoever is
reprovable in religious matters and conversation,
in which light all the nations of them that are saved must walk.

And the Lord hath endued many with power from on high, and sent them forth,
as he did his messengers formerly,
to direct and turn people`'s minds from darkness to light, and from Satan`'s power to God,
that they may receive forgiveness of sins,
and an inheritance among them that are sanctified by faith in Christ Jesus.
Many have received the glad tidings of peace and salvation,
freely preached to them by the Lord`'s ministers,
in the authority of the Spirit and power of God,
in this mighty day of the Lord which is again revealed,
wherein he is come nigh to judgment,
that the prince of this world may be cast out of the temple,
in which he had exalted himself, and been worshipped as God.
The kingdom of God is come, and coming more and more;
and the power of his Christ exalting, in the hearts of many, whose right it is to reign;
and though the devil and his angels war against him,
and for a season be suffered to prevail in dark places of the earth,
so as to destroy the bodies of some of the followers of Christ;
yet the Lamb and his followers shall have the victory,
and the devil and his angels must be cast into the lake that burns for ever.

The Lamb`'s warfare is not for the destruction of men`'s lives, but of sin,
the works of the devil in men, and the weapons of his followers are not carnal,
but mighty through God, to the pulling down of strong holds, casting down imaginations,
and every high thing that exalteth itself against the knowledge of God,
and bringing into captivity every thought to the obedience of Christ.
Howbeit the Lamb, who is also the Lion of the tribe of Judah,
hath power to rule the nations with a rod of iron;
therefore blessed are they that abide with and follow the Lamb through tribulations,
in faith and patience,
until they overcome and have their garments washed and made white in his blood;
for they shall reign with him for ever.

Of this number, we have cause to believe, this worthy servant of the Lord,
William Edmundson, author of the ensuing journal, was one.
He was early visited with the inshinings of the
glorious light of this Gospel-day in his own heart,
whereby his state was often opened to him,
though for a time he did not understand what it was that so enlightened him.
He was left an orphan when young and thereby exposed to hardship;
and after he grew up went into the army,
and continued a soldier some time under the parliament,
in the late civil wars in England and Scotland.
Being religiously inclined, he grew weary of that manner of life;
and delivered up his charge, returning towards his native place in England.

Having been before contracted to a young woman in Derbyshire, he married her,
and soon after came into the nation of Ireland, with an intention to settle and trade,
but was under inward affliction upon his soul`'s account.
In a little time he went again to England to buy more goods,
and being in the northern part among his relations, having an inclination in his mind,
he went with two of them to a meeting of the people called Quakers, where,
by the ministry of some of the said people,
both he and his two relatives were convinced of the way of life.
His understanding being opened by the truth,
he then perceived that it was the Lord by his holy Spirit,
who had been at work in his heart from his youth up.
Wherefore he gave up to its manifestations, and loved the Lord`'s judgments,
because of sin, until he was purified, and prepared thereby to be a partaker of mercy,
and a chosen vessel for the Lord`'s service.
Returning again to Ireland, and being made willing to bear the cross of Christ,
he soon met with various trials for the truth`'s sake, and had the greater exercise,
because there was not then any of the people called
Quakers in that nation to have conversation with.
His behaviour and deportment so reached both his wife and brother,
that they were soon convinced of the truth,
and willing to meet with him in his own house, to worship God in spirit,
though in outward silence,
having refreshing seasons together in the presence of the Lord;
and in a little time four more joined with him.
About this time John Tiffin, a servant of the Lord, came over from England,
who was a strength and comfort to Friends;
several were convinced and added to their number.

The Lord was pleased to open the mouth of our said Friend, William Edmundson,
in the testimony of Jesus; and being faithful, his gift for the ministry was enlarged,
so that he became an able minister of Christ Jesus,
skilful in dividing the word of righteousness, plain and powerful in preaching,
sound in doctrine, and profound in the mysteries of God,
which were largely communicated to him.
As a faithful steward and good scribe instructed into the kingdom, he,
by direction of his Lord and Master, brought out of his treasury, things new and old,
suitable to the service required of him, for the glory of God and good of souls;
being willing to spend and be spent in doing the will of him that called him,
not counting his life dear to himself,
that he might finish the service and charge committed to his trust with joy,
but being sensible of the Lord`'s call thereunto,
gave up cheerfully to follow the Lamb through many tribulations,
which attended for his testimony`'s sake.

He preached the Gospel of Christ freely in this nation,
in which he lived and suffered persecution, being often imprisoned in divers places;
once about fourteen weeks in a close nasty dungeon, among felons and malefactors,
where he was almost stifled; frequently stocked, reviled, abused,
and his goods made havoc of by covetous men.
He also went many times into England,
labouring in the work of the Gospel in divers parts, and three times into the Islands,
or English plantations in America, going the warfare at his own cost,
that the Gospel might not be chargeable.
He endured hardship as a good soldier of the Lamb,
approving himself a faithful minister of Christ, in much patience in afflictions,
in necessities, in distresses for the Gospel`'s sake, in watchings, in fastings,
in weariness and painfulness; by pureness, by knowledge,
and by the power of God in his ministry,
of which he had many seals in this nation and England, and in the Islands of America,
whom he had been instrumental in converting to God.

He was in journeyings often, in perils by sea and land, and in the wilderness,
both by wild beasts and bloody men, in the time of the Indian wars in America,
and by robbers, or rapparees in this nation, in the time of the late calamity,
who burnt his house, and carried him away with his two sons,
almost naked in the winter season, to kill them;
but after much hard usage for several days, they were all three,
by the good providence of God, delivered out of their hands.

This our ancient Friend had also exercise and grief by false brethren,
that opposed the testimony given him of the Lord, to bear for his name,
and was not without affliction from some of his own offspring;
yet out of all the Lord delivered and preserved him faithful to a good old age,
through good report and evil report;
so that near the conclusion of his time he could say,
The Lord was his song and his strength.
He was strong and courageous in the Lord`'s work and service,
even after a decay came upon the outward man, by reason of age and infirmities,
being sound and clear in his understanding to the last.

As he had an excellent gift for the ministry,
he was also endued with a large understanding and gift for
government and religious discipline in the church of Christ;
and having a discerning spirit,
stood firm in his zeal against those things that opposed the
good order into which the Lord had gathered his people,
and such as under fair pretence would open a gap for false liberty.
The care of the churches was upon him, especially in this nation,
where he lived and laboured many years, both in doctrine and discipline;
and as an elder that ruled well, was esteemed highly by the faithful for his work`'s sake.
Temperate he was in eating and drinking; decent and plain in apparel;
in discourse weighty, being mostly concerning the things of God,
tending to instruction and edification.
His countenance and deportment were manly and grave,
expressing a noble and religious disposition of mind; he was a loving husband;
a careful and tender father; a firm friend and kind neighbour; given to hospitality;
and though it was often his lot to be separated
from his wife and children for the Gospel`'s sake,
yet he ordered his affairs with discretion, that there might be no want in his family,
either of commendable employment or necessaries.
But his greater concern and labour was for the public good of the churches,
and promoting the government of Christ Jesus therein,
for which he was zealous to the end,
as appears by divers expressions from him a little before his departure,
some of which follow as a supplement to the ensuing journal.
And when upon due consideration with reflection on past time,
he was persuaded that his day`'s work was done, he humbly desired,
in submission to the will of God, to be dissolved and be with Christ,
to rest from his labour and affliction of body that attended;
which in the Lord`'s time was granted him.

To conclude concerning this our well-beloved friend and elder,
who by faith hath obtained a good report,
and whose memorial is and shall be blessed among the righteous,
I refer the reader to a serious perusal of his following journal,
and those testimonies given forth by faithful Friends and brethren concerning him,
with sincere desire, that the blessing of God may so attend thy reading,
as to excite thee to a faithful improvement of thy time and
the gift of grace bestowed on thee through Christ Jesus,
that thy latter end may be peace, and thy future state eternal happiness.
So in Christian love remain thy well-wishing friend,

[.signed-section-signature]
John Stoddart

[.signed-section-context-close]
Dublin, the 26th of the Eighth month, 1714.
