== Section VI.

Of several ministering Friends from England--His imprisonment at
Londonderry--His deep exercise on account of some loose professors of
truth--Of the general persecution then raging against Friends;
and how instrumental he was in allaying that storm.

About this time several Friends in the ministry came from England,
labouring in the Gospel of Christ Jesus, viz. Thomas Loe, John Burnyeat,
Robert Lodge and some others, and many were turned to the Lord,
and to the knowledge of his way of life and peace.
I often travelled into the north in the service of tinith, to Cavan, Belturbet, Newtown,
Omagh, Strabane, Londonderry and those parts,
and went through many hardships and dangers, being often in prison;
yet the Lord`'s powerful arm preserved me, and carried me through them all;
praised be his name.
At Strabane, where I had been often and imprisoned,
several were convinced and a meeting was settled;
also at Londonderry several were convinced of the truth.

At one time I travelled from Strabane into the county of Donnegal,
which is mostly inhabited by Scotch people, being Presbyterians.
I was moved to ride from house to house and ask if there were any that feared God?
They looked strangely at me,
and wondered I should ask such a question of such religious people.
I came to one house and called, and the master of the house came out:
I asked him if there were any who feared God there?
he said, he hoped so.
I told him I was seeking a people that feared God.
He said it was a good errand; and asked where I dwelt, and my name?
I told him: he said, he was an Edmundson; and bid me alight and come into his house.
I asked him if he would let me have a meeting in his house,
and tell his neighbours and friends of it?
He said he perceived I was a Quaker, and he durst not do it,
for their minister was much set against the Quakers,
and himself was an elder of their church.
After some discourse of religion, we parted lovingly; I travelled on,
and that night lay at an ale-house.

The next day I came to Londonderry; it was market-day,
and there were stage-players and rope-dancers in the market-place,
and abundance of people gathered.
The Lord`'s spirit filled my heart, his power struck at them, and his word was sharp.
So I stood in the market-place and proclaimed the day of the Lord among them,
and warned them all to repent.
The dread of the Almighty came over them, and they were as people amazed.
When I found my spirit a little eased, I walked along the street,
and the people flocked about me, and I found my spirit drawn forth towards them.
I stood still and declared truth to them,
directing them to the light of Christ in their own hearts,
and they were very sober and attentive;
but the stage-players were sorely vexed that the people left them, and followed me.
They got the mayor to send two officers to take me to prison; who came and took me;
but the sober people were angry that stage-players should be suffered,
and a man who declared against wickedness and vanity, and taught the things of God,
must not be suffered, but haled to prison.
The officers made excuse, saying, they were commanded and must obey.
The jailer put me in a room that had a window facing the marketplace,
where I had a full sight of the people;
and my heart being filled with the word of life and testimony of Jesus,
I thrust my arm out at the window and waved it, till some of them seeing me, came near,
and others followed apace;
so that presently I had most of the people from the stage-players, which vexed them much.
Then they got the mayor to cause the jailer to keep me close; so he bolted me,
and locked my leg to a place where he used to fasten condemned persons.
There I sat in much peace of conscience, and sweet union with the Spirit of truth.
As I sat in a heavenly exercise, I heard the people shout and say,
the man had broken his back.
It was the man dancing on a rope, which broke or gave way,
so that he fell on the pavement, and was sorely hurt.
Many professors came into prison to see me, and I had much discourse with them,
and good service for truth.

After a few days, being set at liberty, I travelled through the north,
visiting Friends at their meetings,
where were also several other Friends in the ministry, labouring in the Gospel.
Many people were convinced and meetings increased mightily;
yet some who were convinced and professed truth in words,
did not walk answerably in their conversations, but were careless and loose,
from under the cross of Christ, both in words and deeds;
which gave occasion to our adversaries to reproach us,
and speak evil of the way of truth, and was a stumbling-block to others,
in whom were desires after the knowledge of God and the way of life.
The concern of this came weightily upon me,
and sunk my spirit into a deep exercise for truth,
which was discernable in my face and body to those who knew me;
and I was made a threshing-instrument in the hand of the Lord, to thresh sharply,
and to reprove and rebuke such as walked loosely in the liberty of their
wills and flesh and held the profession of truth in unrighteousness.
I could not get from under this burthen,
until it pleased God to send his servant George Fox,
to set up men`'s and women`'s meetings, and then I was eased; of which hereafter.

1661+++.+++ King Charles coming in, the nation was in heaps of confusion,
and people ran upon us as if they would have destroyed us at once, or swallowed us up,
breaking up our meetings, taking us up in the highways, and haling us to prison;
so that there was a general imprisonment of Friends in this nation.
I was prisoner at Maryborough, with many more Friends,
yet the Lord supported and bore up our spirits above sufferings and men`'s cruelties.
Friends were fresh and lively in the Lord`'s goodness and covenant of light and life,
contented in the will of God; for we had many heavenly blessed meetings in prison,
and the Lord`'s presence was with us, to our great comfort and consolation in Him,
who wrought liberty for us in his own time.

After things were a little settled, and people`'s minds began to cool,
I found it upon my spirit to make application to the government for Friends`' liberty.
I got leave of absence for myself of the sheriff for about twenty
days -- went to Dublin and petitioned the lords justices,
who then were the earls of Orrery and Mountrath, and Sir Morris Eustace, chancellor,
that Friends in the nation might be set at liberty.
I was closely exercised in that service; but the Lord`'s power gave me courage,
opened my way to proceed and gave success to it;
so that I got an order for Friends`' liberty throughout the nation,
though they were full of business, and abundance of people of all sorts attending.
We got several copies of our order signed by the lords justices,
and sent them to the sheriffs of the several counties where Friends were in prison.

Soon after I visited Friends`' meetings through the nation,
and inquired if the order was obeyed by the several sheriffs,
and we were sweetly comforted in the Lord, and one in another.
In about six weeks time I performed this service,
returned and found Friends in our county kept in prison.
I went to Maryborough, where they were.
It was in the time of the quarter-sessions,
and I took an opportunity to speak to the justices and high sheriff, to know the reason,
why the government`'s order for Friends`' liberty was not obeyed.
The sheriff said, it was for fees, and they should pay their fees, or lie there and rot.
But the justices sympathized with Friends,
for our innocent sufferings had gained much on people`'s minds.
I desired the justices to give me a certificate,
what Friends were detained in prison for,
which accordingly they did and three of them signed it.

I rode straight to Dublin, and found John Burnyeat and Robert Lodge in prison,
taken at the meeting the day before.
I went early in the morning to the mayor, and got their liberty,
and then went to the earl of Mountrath`'s lodging.
When I was at Dublin before, the Lord gave me a place in his heart,
which I retained until his death; also his son after him was always kind,
and ready to do Friends good upon occasion.
When I came to the earl`'s lodging, he was in his coach going to council;
he saw me coming, and stopped his coach.
I told him my business, and gave him the justice`'s certificate.
He bid me follow him to the council chamber;
and that forenoon he got me a full order to the sheriff, to set Friends at liberty,
without paying fees to any person or persons, as they would answer the contrary.
I hastened with the order and gave it to the sheriff,
who immediately set Friends at liberty, but was very angry at me, calling me devil,
and many bad names.
Friends were much confirmed in the Lord, who wrought their liberty beyond expectation.

We were imprisoned several times, and the Lord made way for our liberty,
but sheriffs and clerks of the crown would take our goods for fees.
The sheriff, Thomas Piggott, of Dissart, took from me at one time, on that account,
four large cows, worth twelve or thirteen pounds,
and a great many cows and other goods from Friends, but it was observed,
his substance wasted after.

The bishops being now settled, the priests were very fierce on us for tithes,
their maintenance and church dues, as they called them;
and summoned us to the bishop`'s court,
and excommunicated most of the men Friends of our meeting,
and took them by a writ to prison.
I was excommunicated with the rest, but was abroad in truth`'s service,
when they were taken.
When I came home the officers met me, for I did not shun them,
but they would not take me to prison, for they said, they had too many in prison already,
who were kept from their labours and families; yet Friends were easy in their spirits,
being given up to suffer for the testimony of truth,
and in the prison every one settled to some employment.
