== Chapter XII

[.chapter-synopsis]
* His frequently exposing his own life to save his neighbours,
* and standing his ground in those perilous times, till his house was set on fire,
* himself and two sons led away to be murdered by the Irish raparees;
* yet by Divine Providence were delivered out of their hands
* About the year 1690, he, with many more, saw the fulfilling of his prophecy,
* mentioned in the last section
* //Not sure what to do with this one!!

Now wickedness was let loose, and got ahead;
so that by violence and cruelty most of our Protestant
neighbours were forced from their dwellings,
and several families came to my house, until every room was full;
also most of their cattle that were left, they brought to my land,
thinking themselves and goods safer there than elsewhere.
We were under great exercise and danger, not only of losing our goods, but our lives also.

At the Boyne fight, the Irish army being beaten, many of them fled our road,
and plundered many in our parts; they plundered my house several times over,
and we were in great jeopardy of our lives; they were wicked and bloody;
so the family were forced to go out of the way, and my wife desired me to go aside,
lest they should kill me, for she would venture her own life to save mine;
but I could not do it, though they should be permitted to kill me.
Yet the Lord`'s secret hand restrained them, and preserved our lives.
They took all our household goods they could find and liked,
and all our horses that were left.
Violence was let loose, and no government to make address to.
The English army did not come near us for some time, and, to look outwardly,
we were exposed to the wills of cruel blood thirsty men.

1690+++.+++ I sent to the chief of the Irish near to us, who stayed at home,
and they came to me;
I told them they might consider we had lived as peaceable neighbours,
and I wished we might do so still;
and though at present the English in this neighbourhood
lay open to the spoil of their countrymen,
yet they might easily apprehend it would come to their turn;
for the English army being masters in the field, would soon advance,
and then they might expect the same measure from them,
as the English now received from their countrymen.
Wherefore,
I advised that they would use their utmost endeavours to keep their
countrymen from spoiling the English of the little which they had left,
and when the English army advanced to us,
we would use our endeavours and interest to do the like for them.
They seemed to accept the proposal gladly,
and promised with many oaths to perform it to the utmost of their power; but did not:
for there were few nights passed,
but some of our English neighbours were robbed or wounded;
and when I told them of their promises, they would pretend ignorance of the matter.

The English who remained near us,
were forced to flee into the parish worship house at Rossenallis,
a little way from my house, for safety.
When the English and Scotch came into those parts, they plundered the Irish;
but King William put forth a proclamation, that the Irish and others,
who would live peaceably at home, should not be molested.
Notwithstanding which, there came two captains, with about three hundred soldiers,
and drove away about five hundred head of cattle and horses,
and also took away prisoners.
One William Dunn, who had been a captain in the former wars,
and two of his sons were of the number, one of whom they stripped of his clothes,
in order to hang him, having suspicion that he was a raparee;
then the Dunns sent for me in haste, and acquainted me therewith:
I took horse and rode after the parties as swiftly as I could,
having regard to my promise of neighbourhood;
when the Irish neighbours saw me ride after them,
many followed in expectation to get their cattle and people released.

I rode four miles before I overtook them; when I came near,
the two captains perceiving who it was, for they knew me before, made a halt and met me.
I reasoned the matter with them, and told them of the king`'s proclamation,
and that it would not be the soldiers, but they who commanded,
that must answer for the injury done;
and that it was a reflection upon the king`'s promise,
as also a great reflection on the English nation.
So with much discourse and arguments to this purpose,
the two captains seemed willing to release all, if the soldiers could be prevailed upon.
I rode with them to the head of the party, but they were very angry,
and would needs have killed the Irish who followed for their cattle.
Whereupon I quitted my horse and ventured my
life among the rude soldiers to save the Irish,
and with much ado, and the captains`' assistance, got them moderated,
on condition to give them a small part of the cattle, to release the rest.

Then I mounted my horse, and sought out the man whom they had stripped for hanging:
when I found him, I threw him my riding-coat to put on,
and desired one of the captains to assist me in finding him that had taken his clothes.
When we had found him, I reasoned the matter with the captains and soldiers,
telling them it was unmanly, and not like a soldier, to strip men in that manner;
for I had been a soldier myself, and would have scorned such a base action;
besides it might be a precedent to the Irish to strip the English.
Many such arguments I used, which at last prevailed;
so that the captain made the soldier put off the man`'s clothes,
and give them to him again.
I also got both the father and his sons released, with all their cattle,
and a great part of the others.

Frequently, when the English soldiers took away the Irish people`'s cattle,
I persuaded them to give up some of them again,
or bought them for a small matter with my own money, and gave them to the owners;
and let their horses graze on my land, to save them from the plunderers.

The English army having settled in their winter quarters,
and the raparees increased their number; most of the Irish run out,
and our quarter lay open to them.
They burned many brave houses, and some towns; also killed several Protestants,
and all the country was full of trouble; yet, through the wonderful mercies of God,
we kept our meetings constantly, and enjoyed them peaceably,
but in travelling to and fro, were many times in danger of our lives by the raparees,
yet the Lord preserved us wonderfully,
so that I do not know of above four Friends in this whole nation who were
killed by violent hands during all the time of this great calamity.

The time of our Half-year`'s National Meeting at Dublin approaching,
beginning the 8th day of the ninth month, 1690, I went to it as usual.
We had a heavenly blessed powerful meeting,
and Friends were more than ordinarily glad one of another in the Lord Jesus,
who had preserved us alive through so many dangers, to see one another`'s faces again.
In the time of the meeting tidings were brought me,
that the raparees had taken about twenty of my cows,
but that none of my family were hurt.
At which I was well satisfied, for then all were in danger of their lives,
who saved any cattle about us, and lived out of garrisons.
When the service of the meeting was over, I returned home,
and found my wife and family well; which was great satisfaction.
But spoil and cruelty increased, and imminent dangers were plain in my view;
yet I durst not remove, for I knew it would discourage Friends, and the English about us,
and perhaps cause them to flee from their habitations,
and so be exposed to want many necessaries; for they took notice of me,
and many of them thought they were safer for my staying in my place.
I also believed that one hair of my head should not fall without God`'s providence.

On the 23rd day of the ninth month, before-mentioned, I went to colonel Biarly,
then governor of Mount-melick,
and told him that if he did not use some speedy means to succour our quarter,
it would be to his great damage, for I expected every night that my house would be burnt;
and if I gave way,
all the English thereabout would flee and so the
raparees might burn and destroy all the forage there.
I urged him to take some way to succour us, informing him how he might easily do it;
yet he took little notice of it,
for that same night some hundreds of raparees beset my house,
and I with my family being asleep, they fired several shots in at the windows,
which were heard at Mount-melick, two miles off.
Whereupon several went to the governor, colonel Biarly,
and desired a party of men to relieve me, which he would not grant them;
then a certain lieutenant, as they said, went to him, and desired a party of men, saying,
I was an honest man, and he would relieve me, or lose his life.
But Biarly answered, he would hang that man that would go out of the garrison.
So the raparees set fire to my house, and I stayed therein until much of it was burnt.

When we could stay no longer for the fire, I made conditions with them,
and opened the doors, and went out: but they soon broke their conditions,
for though they had bound themselves with many oaths,
they took what plunder they could get from the fire; which being very fierce,
destroyed the greatest part.
One mare was burnt to death in the stable, and two more they got out of the fire,
sorely scorched; they took my wife`'s uppermost garment and so left her,
but me and my two sons they took away prisoners, bare-legged and bare-headed,
and not much better than naked.
One of them, at my request, lent me an old blanket of my own to lap about me;
and they took away all my cattle, leaving not one.
They took me and my two sons that night through rough places, bushes,
mire and water to the knees, in cold weather,
where our bare feet and legs were sorely hurt, and bruised with the bushes,
gravel and stones.

The next morning they took us to a wood, and held a council upon us;
who concluded to hang my two sons, and shoot me, because they said I was a stout man.
I told them many of them knew me, and my two sons also;
and I challenged them all to prove, that either I or my sons,
had wronged any of their country-folks one farthing during all these times of trouble;
but on the contrary, I had saved them what I could;
sometimes with the hazard of my life among the English soldiers.
Several of them made answer, and said they knew I was an honest man.
Then I told them, if I died they were my witnesses I was innocent,
and God would revenge my blood.
They wondered at my boldness, and indeed my life was little to me, for I desired to die,
if it were the will of God.
Then they hoodwinked my sons to hang them,
and having prepared two fire-locks to shoot me, they came to hood-wink me also;
but I told them they need not, for I could look them in the face,
and was not afraid to die.

Now came up one lieutenant William Dunn, who was well acquainted with me and my two sons;
he was son to old captain Dunn, whom I had got released,
together with his cattle from the English soldiers,
and brother to him whom they had stripped in order to be hanged,
whom I got released also, as aforesaid.
He who commanded this villainous party that burnt my house,
with several others whom I had done kindness for, were present; so this lieutenant Dunn,
expecting to get preferment for what he had done, would take us to Athlone,
twenty miles from that place.
Thus the Lord interposed, and would not suffer them to take our lives,
having a further purpose of service for me.

The said Dunn kept us three nights by the way at a cabin, cold and hungry,
so that they themselves wondered how I could endure it;
but I told them they had taken and destroyed my victuals,
and the Lord had taken away my appetite, so I was fitted for it.
As we went to Athlone, we met lieutenant Richard Dunn, and one Poor, his brother-in-law,
who railed against us; but I told him he should not rail at us, for we were prisoners,
and a right soldier would not rail at a prisoner.
They said they were going to burn Mountmelick,
as also the rest of the country then unburnt.
I told them there were many honest people there, and said God help them.
After some other discourse they left us.

As we went through Raghan, there came out of a cabin an ancient Irishman,
who looked on me with a sorrowful countenance, as though he pitied me, I looked on him,
and asked him if he could give me a piece of bread? for I knew my sons were very hungry.
The man answered, and said he would give me a piece of bread, if he bought it with gold,
for he believed I was one that did not use to beg my bread.
So he went into the cabin, and fetched as coarse a piece of bread, I thought,
as ever I saw, and said he was sorry he had nothing to give me to eat with it;
but I told him it was very acceptable, and gave it to the lads.
That night we got straw to lodge on, rested well, and the next day came to Athlone.
We were no sooner got into the great street but it was
filled with a crowd of rabble and soldiers,
and the high sheriff of that county in the midst of them, calling us traitors, rebels,
and such like names,
that it was much they did not stab us with their bayonets and skeins,
through the sheriff`'s animating and encouraging them.
But in the interim a genteel man crowded through them, and came close to me,
and calling me Master Edmundson, asked me howl did?
I answered, saying, Thou seest how I do; but I know not thee.
He answered, and said, I know you to be an honest man,
and spoke aloud to the sheriff and the rest, saying, I have known him above twenty years,
and I know him to be an honest man, say you all what you will of him.
This made them all quiet: thus the Lord provided succour for us, from their own people,
in the time of imminent danger.
They took us to the main guard where the rabble thronged in upon us;
but this man came there, and told them they did not know me so well as he did;
he also acquainted me what William Dunn, who brought me there, had informed against me.
Then I told him the whole passage, and he said if that was all,
he would not have me deny anything.
I answered him, I had done nothing that I need deny.
This man`'s name was Valentine Toole, a lieutenant.
I heard he was reproved for being so kind to me, and durst come no more to see me.

In some little time we were taken to the castle, where the governor, colonel Grace,
and the council of chief officers were met.
I came in with my old blanket lapped about me: the governor asked where I lived?
and what was my name?
I told him I was old William Edmundson: he stood up, with tears in his eyes,
and said he was sorry to see me there in that condition, for he knew me well,
having been sometimes at my house.
Then the governor asked the lieutenant who brought us there,
what he had to say against me?
And he accused me of several things falsely,
and I having free liberty to answer to every particular, did so,
that the council of officers were well satisfied,
and the governor spoke roughly to the lieutenant,
and asked him what he brought us there for?
He answered with this excuse, viz: that the raparees were about to hang us,
and he brought us there to save our lives.
The governor said if he had them there, he would hang them.
And so he committed us to the custody of captain Francis Dunn,
and soon after sent us a loaf of bread, a piece of beef, a bottle of drink,
and twenty shillings of brass money; but we could get no straw to lie upon,
but lay upon the bare floor, which was very cold and hard; we wanting clothes,
and my strength being much spent, I was not likely to continue long,
if the Lord had not provided succour for me.

John Clibborn, a Friend, lived six miles from Athlone,
though most Friends in those parts were forced away, except he and some of his family,
who hearing of me, came to Athlone; when he saw me in that mean condition, he cried out,
wringing his hands,
and told them that they had taken prisoner as honest a man as trod on the earth.
After some time, he went home to fetch us some meat,
for he had little clothes left for himself, having been sorely plundered and spoiled.
Most of the field officers and captains knew me,
I having been often at Dublin with the government, when King James was there,
and they would discourse familiarly with me.
One time I asked them what they had against me?
And what I had done, that they kept me prisoner in that sad condition,
and did not bring me to a trial?
Colonel Moore said they had nothing against me for anything I had done,
and he believed I was a very honest man; but they understood I was a witty man,
and capable to do them an injury, and that was the reason they kept me.
I told them that was poor justice, to punish a man for what he was capable of doing,
and not for what he had done.
The next day John Clibborn came again, and brought some victuals,
but we could get no straw yet to lie upon.
I was much spent, and my spirit grieved with their wicked company,
so that I desired rather to die quietly in a dungeon, than to be among them.

I sent John Clibborn to the governor, to desire that I might come upon my trial,
or be removed into the dungeon.
The governor said he was sorry for me, for I was an honest man,
and there were none mine enemies, but the Dunns, who were all rogues;
and he durst not release me, for there were many eyes over him,
because he was kind to the English; but to send me to the dungeon,
he could not find in his heart to do.
The town was so thronged with people,
that there was no room to be had in which I could be easy; he was in a strait,
and knew not what to do with me.

John Clibborn then requested him to let me go with him to his house at the Moat,
and he would engage his body, and all that he had, for my true imprisonment,
and to come when he sent for me alive or dead: so the governor was content,
and let us go with him.
Thus the Lord provided succour for me in a time of great distress.
When I was there, with much difficulty, I got a few lines written and sent to my wife,
that she might know we were alive, and where we were;
which was great satisfaction to her and Friends;
for many were under great trouble of mind,
and it was a trial on most Friends in our country.
The English fled to garrisons, and most of the Irish went to the raparees.

One of my sons, who was with me, had a tan-yard well stocked with hides and leather,
and about a week after our house was burnt, my wife went to fetch them off,
and several English neighbours, with horses and cars, went to help her;
but whilst they were loading the leather, etc., lieutenant Richard Dunn,
and his brother-in-law, +++_____+++ Poor, whom I had met in going to Athlone,
and who railed at me, as aforesaid, together with a multitude of raparees came upon them;
so that they were forced to run for their lives, and leave the horses and cars,
the leather and hides, etc., which the raparees carried away.

My wife not being able to out-run them, they took and stripped her naked,
being cold weather, in the beginning of the tenth month,
called December she being ancient, and going two miles naked, got a cold,
which continued with her until she died, being about seven months after.
The next morning a small party of English soldiers fell
upon that great company of raparees,
and killed the said lieutenart Richard Dunn, also his brother-in-law, Poor,
and a great many more of them: so were they prevented from burning Mount-melick,
as he and others had threatened to do.

While I was with John Clibborn at the Moat,
many of the Irish came daily to get what they could;
there came also colonel Bourk with about three hundred fire-locks, as a frontier guard,
to intercept the English soldiers.
He was very loving to me, and promised that when he got to Athlone,
I should have my liberty, for he believed I was an honest man.
So in a little time he and his party went thither;
and with his assistance the governor set me at liberty,
having set my two sons at liberty three or four days before,
who were gone to their mother.
Being at liberty, I got to Streams`' town, which was the next English garrison,
though it was difficult and dangerous travelling, because of the raparees,
there being now little but killing and destruction on both sides.
Here I met with my son Samuel, who,
notwithstanding he had left the profession of truth and cast off his education therein,
yet was concerned for me in this great trial; he came to that place,
being the utmost frontier garrison of the English,
to use his best endeavours for my liberty.

From Streams`' town I went to Mullingar, which was a great garrison of English,
where the officers and soldiers were very kind to me,
and expressed their great gladness for my safe coming off,
though many of them had never seen me before, but had heard of me, and of my ill usage;
for the noise of it went far, and several had sworn,
that if they had killed me and my sons,
they would have killed all the Irish they met with.
From Mullingar I came to Jane Barcroft`'s, near Edenderry,
and from thence to Mountmelick to my wife, where many were glad to see me again.
We shifted for house-room as well as we could, the town being thronged with soldiers,
and families driven from their habitations in the country;
many of whom died for want of conveniencies and necessaries,
together with grief for their losses.

The Irish preyed much abroad in the country, and destroyed it;
so that the English army marched out to drive them back over the Shannon,
and they burned much of the country that harboured them on this side.
At this time also major general Kirk, with part of the army,
came to Mount-melick with intention to settle garrisons in convenient places,
to save the country, some informed him of Rossenallis, as a fit pace for a garrison,
telling him of me, and how I had been used there by the Irish.
He sent for me, and commanded me to go with him to Rossenallis, and show him the place;
so being commanded, I went with him.

Many Irish lived there and thereabout, under the English protection,
who supposing that I had occasioned their coming to make a garrison there,
were very angry with me,
because this would hinder them from harbouring their kindred and countrymen,
who were raparees, as they had frequently done before,
therefore they got eight or nine bloody raparees,
to lie in ambush between Mount-melick and Rossenallis in order to kill me,
as hereafter may appear.
For young John MacLisln, who had betrayed my wife into an ambush before,
together with Dennis Dunn, came to Mount-melick in pretence of great friendship,
desiring me to go to Rossenallis, and speak with the officers in the garrison,
and it would be better for the dwellers there; but as the Lord would have it,
I did not go that day.
Two days after they came to me again with the same pretence, saying also,
that the soldiers were pulling down my out-houses, which were left unburnt;
and using many arguments, in show of kindness and friendship,
to persuade me to go to Rossenallis,
but I was restrained by a secret hand that knew their evil design,
and would not suffer me to fall into their snare.
Howbeit next morning, James Dobson, with his son and cousin coming that way,
they shot his son dead in the place, himself and cousin they took to the woods,
and barbarously murdered them.
That night the Irish Papist inhabitants generally ran to the raparees.
Thus the Lord preserved my life from the hands of cruel and blood-thirsty men.

As soon as the ways were opened to travel, I went into the north to visit Friends,
and some Friends accompanied me.
As we went by Dundalk where the armies had been one against the other,
there were many bones and tufts of green grass that had grown from the carcasses of men,
as if it had been from heaps of dung.
Then I told Friends who were with me, you may remember,
that I declared it in public in the word of truth many years past,
and many times in divers places,
that the Lord would dung the earth with the carcasses of men,
and would spread them as dung upon the face of the earth;
and now you see it here fulfilled.
In that journey I had many sweet comfortable meetings in the north,
Friends`' hearts were glad, and we were greatly refreshed in the Lord Jesus,
and one in another.
When clear of that service, I came to Mount-melick.
