== Section XVI.

In 1696, William Edmundson writes to Friends at London, being unable to go thither;
visits Ulster province, and deliberates about marrying again:
Also hath hard exercise by a selfish worldly spirit,
the danger whereof he describes by an apt parable.

About three weeks after was our National Half-year`'s Meeting at Dublin,
which began the 8th day of the third month, 1696,
and continued about four days for the worship of God and church affairs;
many good and needful things were there discoursed of,
and assented to in peace and unity--the Lord`'s blessed
power and presence being with us to our great comfort,
making hard things easy.

At this meeting I received letters from divers brethren in England,
earnestly desiring that I would be at the next Yearly Meeting at London;
for that the public service of truth required it.
But I was not able to answer their desire, because of weakness.
So I wrote, and sent a letter by George Rooke and Nicholas Gribble,
who intended to go over to that meeting.
When the service of this our meeting was over, I came home, accompanied by many Friends,
but was weak of body.
The first day following was our Monthly Meeting,
and the next first-day after was our Province Quarterly Meeting, both at Mount-melick,
to which many came from several parts, and heavenly good meetings we had,
both for the worship of God, and managing of Church affairs,
the Lord assisting and enduing us with wisdom; the testimony of truth was over all,
and I had ability given me from the Lord to answer what he required of me,
before which my natural strength was faint and weak.

I continued about home for a while, keeping to our usual meetings,
and when I grew well and able to travel, I went to Munster Province Meeting.
This meeting was at Clonmel, in the fifth month, 1696,
and held two days for the worship of God and managing the affairs of the church,
and there were many Friends from several parts.
In this journey I had several meetings, at Mountrath, Knockballymagher, Waterford,
Wexford, and the Monthly Meeting at Ballinaberny, which was full and large,
and the Lord`'s power and presence accompanied
and gave ability in all meetings and services;
many hearts were tendered and comforted.

I had also a meeting at Israel Webster`'s, and one at Shellaly, then came to Castledermot,
to our Province Meeting, where was a great appearance of Friends from several parts,
and many Friends in the ministry, both of England and this nation.
This meeting held part of three days for the worship of God and church discipline,
and the Lord`'s power and glorious presence were mighty among us,
strengthening our hands in his work, to our great comfort and satisfaction,
both immediately and through his servants.
When the meeting was over, we parted in the love of God,
the testimony of truth being in dominion.
I returned to my house on the 17th day of the sixth month, 1696.

Soon after this I took a journey into the province of Ulster to visit Friends,
accompanied by Joshua Northall, and some others.
We went to Dublin, and stayed two meetings on first-day,
from thence Roger Roberts and Thomas Ashton accompanied us into the north.
We had a meeting at Drogheda, and the next day came to Ballyhagan,
to the Province Meeting, which held part of three days,
and a great assembly of Friends there was,
the Lord`'s power and presence being with us to our great comfort and confirmation.
The service of this meeting being over,
the aforesaid two Friends from Dublin returned home,
and I with the rest of my company went over the river Band,
and had many heavenly comfortable meetings at several places, as at Lurgan, BaUinderry,
Lisnegarvy, Grange, etc.
In our return we had a precious meeting with Friends at Lurgan before parting,
in which we were comforted and refreshed together to our great satisfaction.

From thence we took our journey towards Leinster,
accompanied by some Friends of Ulster about forty miles,
and had a meeting with Friends near Ballyhayes;
after which the Friends who accompanied us returned home.
We travelled next day to Old Castle, and had a meeting with Friends there,
and the day following into Leinster province,
and were at Friends`' meeting at Edenderry the next day,
and on the day following at Ballycane meeting near Cashel; so returned home.
I had good service for the Lord, his truth and people,
in this journey through his assistance, who gave me strength and ability every way;
blessed be his name for ever!

On the first-day following I went to visit Friends in their meeting at Mountrath,
and returning home abode there for some time, frequenting our own meetings,
both weekly and monthly as they came in course.
I also went to our Quarterly Meetings at Castledermot, which held two days,
and the Lord`'s comfortable presence was with us,
in a sense whereof the affairs of truth were managed in peace and concord.
From thence I went to Dublin to our National Half-year`'s Meeting,
which began the 8th day of the ninth month, 1696, and held by adjournment four days;
the Lord`'s glorious presence greatly appeared both in meetings for the worship of him,
and those for managing church affairs,
which were gone through in peace and unity to our great satisfaction and comfort.

After the service of the meeting was over,
I took my leave of Friends and brethren in the overflowings of the love of God,
and went homeward.
The depth of winter coming on,
and being unable to travel and labour in truth`'s service as formerly I had done,
I stayed for some time about home, attending meetings as they fell in course,
both Six-weeks, Monthly and Weekly, for the worship of God,
and services relating to truth.
The Lord`'s work went on and truth prevailed, which is cause of great gladness of heart.

About this time it came into my mind to marry, yet I was not hasty to proceed;
but many weighty things relating to that affair came under my consideration;
and though it would often present in my understanding, yet I sought the Lord`'s counsel,
and quietly waited to know his mind therein, until I had his gracious answer,
in the clear openings of his light shining in my heart.
Then finding my way clear,
I acquainted the person towards whom my mind was drawn in that respect, viz: Mary,
the widow of Joshua Strangman, about the age of forty-nine years,
whom I had ground to believe would be a comfort to me, and helpful in my family,
being a woman of good understanding and one who feared the Lord.

After same time of consideration, she consented thereto,
provided our children and Friends were satisfied therewith.
I also acquainted her, that if the Lord gave me health and ability,
I must first go for England to perform some service for Him there,
which had been before me for some time; which she was well satisfied with,
being willing to stay the Lord`'s time.
I abode some weeks at home, being unwell, through colds contracted in my travels;
but our Quarterly Meeting for Leinster province at Castledermot, was at hand;
where the elders and friends in the ministry used to meet,
and to make inquiry whether those of our Society
walked answerably to their holy profession,
in blameless lives and conversations.
In which service the Lord`'s power and divine presence
had often been plentifully manifested among us.

I had a great desire to go to this meeting, though unwell in body;
so in faith of the Lord`'s ability I set forward, and rode to Athy, fourteen miles,
in some pain, and the next morning got to Castledermot,
to the meeting of elders and brethren in the ministry,
where an account was given from each meeting in our
province of the state of things among Friends.
My spirit was under a great exercise for truth`'s testimony,
and the labours of concerned elders who were
likely to come under a worldly selfish spirit;
wherefore I, with some elders and brethren, laboured hard against it,
and the meeting was adjourned until the next day.

I spent that night in some trouble of mind for the testimony of truth,
and besought the Lord for his assistance; early the next morning we met again,
and the Lord`'s power broke through all opposition--his testimony came over all,
and things returned into their right channel to our great comfort.
Here, according to order established among us,
I acquainted the elders with my purpose of going for Wales and England,
towards the spring, to perform some service in truth`'s testimony, which was before me,
and they seemed to be well satisfied therewith.

Things being concluded among the elders,
we all went into the public meeting for the worship of God,
where in the spirit and power of the Lord Jesus I bore a testimony,
and by a parable warned Friends of the mystery of Satan, in his working with man,
by drawing his mind into the things of this world, comparing it to the root of a tree,
that shoots downward too deep into the ground, from the very heart of the tree,
and causes the growth of much wood and high branches,
but brings forth little or no fruit.
From which was opened, in the doctrine of the kingdom,
the danger of riches and great concerns in the things of this world.
Friends`' understandings were opened, the witness of God reached,
and many tendered in their spirits.
This meeting held by adjournment three days, in which the Lord renewed my strength,
and I was glad that I was there for the service sake.
When it was over, I returned home.
This was in the end of the eleventh month, 1696.
