== Chapter XIX.

[.chapter-synopsis]
* In 1700 he visits Munster, where he was much afflicted in body
* After his recovery and return, he, G. R. and J. F., went towards Connaught
* At Ayres-court all three were put in the stocks
* At Abby-boyle, they had a good meeting in the streets, etc.
* They write to the bishop of Clougher, and return through several meetings in Ulster and Leinster

About this time I went towards Munster to visit Friends,
and was at a meeting at Mountrath, and one at Knockballymagher, and so went to Limerick,
and stayed three meetings; where we were well refreshed in the Lord.
Then rode to Charlevil, and stayed one meeting;
from thence to Cork and were with Friends at several meetings,
it being the time of their Provincial Meeting, the Lord`'s heavenly presence was with us.
Here I was taken with a great pain in my right side,
yet the Lord`'s power enabled me to answer the service of that meeting;
when it was over we parted in the sweet love of God, and comfort of his holy Spirit.

I rode in much pain that day to Clougheen twenty-two miles, where I tarried that night,
and John Pirn with me; the next morning we got to John Fennell`'s,
and had a meeting with Friends to worship God, whose goodness was with us.
Next day, accompanied by several Friends, I rode to Thurles, about fourteen miles,
in great pain, my distemper increasing;
and on the day following with much difficulty got to James Hutchinson`'s,
not being able to go any further.
There I lay under great affliction,
which increased with violent pain and grievous soreness over my body,
yet nothing to be seen outwardly.

Thomas Pearce of Limerick, who came with me from Cork, on purpose to help me,
administered what he thought was proper for my distemper, to give me ease.
My wife came and stayed with me,
also some of my children and several Friends came to see me.
In about seventeen days, finding some ease, I was desirous to go home, if possible;
and through the Lord`'s mercy rode thither in two days, being fourteen miles.
The National Half-year`'s Meeting being at hand,
and having some service before me at that meeting,
I was desirous to be there to perform it,
although the distemper and soreness remained much upon me;
yet I was willing to trust the Lord, who had often helped me through great weakness,
to perform many weighty services for his honour,
the promotion of his truth and good of his people.

I took my journey to Dublin, and in two days got thither, being thirty-four miles,
where the Lord by his power strengthened and enabled me
to perform my service in the meeting at that season.
There was a very great appearance of Friends from several parts of the nation,
and we had divers good opportunities,
the Lord`'s power through his Spirit opening deep mysteries to us,
both in doctrine and discipline, to our great benefit and comfort.
When the service of that meeting was over, I took horse at Roger Roberts`'s:
thither many Friends and brethren came, where we parted after supplication to the Lord,
whose love and life flowed in us.
In two days`' time I came home to my house, the Lord`'s name be praised forevermore.

Finding my body unable to endure long journeys,
I kept to the service of meetings near home, as they fell in course;
and about the beginning of the sixth month, 1700,
went with George Rooke to a meeting at Ayrescourt, in Connaught,
where few or none had been before, and another at Ballyboy, where many people came,
and heavenly things were largely opened in the testimony of truth,
which reached God`'s witness in the hearers,
who signified their satisfaction with what was declared,
in the demonstration of the Lord`'s spirit and power.
We likewise had a sweet comfortable meeting with Friends at Birr, and so returned home.

My ability to travel increasing,
I found some openness in my heart to go in truth`'s service again into Connaught,
and some other places, that wanted visiting by faithful labourers.
So on the 16th day of the sixth month, 1700, I took my journey,
accompanied by George Rooke and several other Friends, and had a meeting at Ballyboy,
and another at John Ashton`'s house, where none had been before;
many professors came to that meeting,
and seemed to be well satisfied with what they heard.

Then we went to Ayres-court in Connaught, where several Friends came;
and being set down to wait upon the Lord, in a barn we had obtained for the purpose,
colonel Ayres, who was owner of that place, came with a lawyer, a constable and wardens,
who in a violent manner pushed and haled us out of our peaceable meeting,
and drove us into the street, commanding the constable to put me in the stocks,
which he did.
This was a grief to the people, some of whom wept,
to see an ancient man set in the stocks for worshipping God,
having never seen the like before.
Many people being gathered about the stocks, with several Friends,
George Rooke spoke a few words by way of exhortation;
and colonel Ayres commanded the constable to set him in the stocks, which he readily did;
afterwards Jacob Fuller for the like was also set in the stocks with us,
where we sat together in sweet peace and comfort of the Lord`'s holy spirit.

After sitting there some time, the people being troubled for us,
the constable opened the stocks, and bade me take out my leg,
I told him I did not put it in; so he held the stocks open with one hand,
and took my leg out with the other.
My companions were also set at liberty, and the Lord`'s mighty power was with us,
which sprung in my heart as a fountain, wherein I published the mighty day of the Lord,
warning all to repent.
I also declared the Gospel of peace and glad tidings in the openings of life,
through the Lord`'s spirit; and we had a brave heavenly meeting,
truth`'s testimony was over the heads of our opposers, and Friends sweetly refreshed.
Parting with joy in an heavenly dominion,
I with my companions rode that night to Ballinasloe, and some went farther;
next day we came up to the rest of our company,
and rode to Carrickdrumroosk thirty-five miles,
and on the day following had a meeting at the inn, where we lodged,
to which several sober people came, and seemed to be well satisfied with what they heard.

Then we went to Abby-boyle, and lodged at the burgo-master`'s house,
who let us have his stable to meet in, at the eighth hour in the morning.
Notice thereof being given, the people generally were willing to come to the meeting,
and in order thereto were gathering; but priest Cope, being dean there,
obstructed what he could, and set a company of rude boys to make a great noise,
and a man to play the fool.
I went into the street near the dean`'s house, and Friends came after me,
where in the Lord`'s power I sounded forth the great day of the Lord`'s coming,
the dread whereof silenced the rabble, the man also who played the fool fled;
and the people gathering in the streets, and others looking out at their chamber windows,
I preached repentance, and opened the way of life and salvation to them.
The dean being within hearing of what I thus declared in the Lord`'s power,
I challenged him to come forth before the people,
to prove his practice agreeable with Christianity, and to disprove ours if he could;
but he would not appear.
When I was clear, George Rooke prayed to the Lord in the street,
and we had a good meeting, being held and concluded in truth`'s authority,
which was over all, and the people were loving.

I called for the man whom the dean had sent to play the fool, and he coming to me,
I admonished him--he seemed to be sorry for what he had done, saying,
he believed I was a good man, and if he had known as much before, as he did then,
he would not have done so.
After our service here was over, we took horse and rode that day to Sligo, twenty miles,
where the high sheriff and magistrates were very civil and kind,
and said that anything they could serve us in, should not be wanting.
They freely granted us the session-house to meet in, and let us have the key of the door.
We had three meetings there, and the Lord`'s presence and power was gloriously with us,
which crowned our service, and bowed the spirits of many;
one justice of the peace sat with us in the first meeting,
that we might have no disturbance.
We abode at that town three nights, and being clear of our service there,
rode to Balleek where several desired a meeting;
the owner of the place then living there, came to us,
and offered his assistance in anything he could serve us;
but other service being before us, hindered us from staying a meeting there at that time.

We came to Petticoe,
and found freedom in our spirits to have a meeting at the inn where we lodged,
and sent to give notice of it.
In about three hours there was a large gathering of sober deserving people:
it was a powerful meeting, and they parted friendly.
The next day we rode to Auger, twenty-five miles, being a bad road over mountains,
and also a heavy rain and storm in our faces,
so that both we and our horses were much foiled; but through the mercy of God,
we all got there well, and the next day had a meeting: the people were civil and quiet.

The bishop of the diocese lived about a mile from that place, but was not at home,
so we could not invite him to our meeting,
but sent him three little books enclosed in a letter; a copy whereof follows, viz.

[.embedded-content-document.letter]
--

[.letter-heading]
For The Bishop of Clougher

Friend, Here are a few of the true Christian church of reformed Protestants,
upon a visit to our Christian friends and people, according to Christian duty,
which our Saviour and his apostles taught and practised for our example to follow;
and because of other service on this account,
our time would not well admit to give thee a visit,
yet thou being a ruling man in church affairs, we did not forget thee,
but as a token of our friendship have sent thee here enclosed three little books,
which may be for thy profit, if rightly applied;
which is all at present from thy Christian friends,

[.signed-section-signature]
William Edmundson, George Rooke, Roger Roberts, Thomas Winsloe.

[.signed-section-context-close]
Auger, the 27th of the sixth month, 1700.

--

After this meeting we rode to John Whiteside`'s, near Charlemount, fifteen miles,
and the next day had a heavenly meeting with Friends at their meetinghouse,
and on the day following went to Toberhead twenty miles.
The next day, being the first-day of the week, we had a meeting at Thomas Gregg`'s house,
where many Friends met us from Grange and Dunclaudy;
then we went to Colerain and had a meeting,
and several Friends came out of the country to it; from thence to Grange,
and had a meeting with Friends, and another at Antrim.

Then we went to Richard Boys`'s house, where we stayed to the Province Meeting,
which held two days, and a great appearance of Friends there was,
and the mighty power of the Lord was with us.
When the service of that meeting was over, we rode to Lurgan, and had a meeting,
and another at Ballyhagan; then to Friends near Ballyhayes, thirty-two miles.
When we had gone through these meetings,
we rode to the county of Longford to get meetings, and spread truth in those places.
Had a good meeting at Granard, where none had been before, and many came to it,
who were reached with truth`'s testimony, and desirous to have more such meetings.

Thence we went to Ballinalee, and had a meeting about a mile from thence,
to which several professors came, and the mystery of faith was largely opened to them.
We had another meeting at a place called Tristiny,
where several Friends met us from the Moat and Mountmellick;
some noted persons and others also came to it,
and the everlasting Gospel was largely preached to them
in the demonstration of the spirit and power of the Lord.

After this meeting we rode to Lismoiney, to Isaac Fuller`'s,
and there parted in the sweet peace and unity of the Lord`'s blessed spirit,
which accompanied us in our travel and service,
and was mouth and wisdom to us in every place where we came,
so that gainsayers could not oppose,
and many confessed to the truth of the testimony we bore for God,
and his dear Son our Lord Jesus Christ; everlasting praise to his great name.
Amen.

George Rooke and Roger Roberts went home to Dublin, Thomas Winsloe to Birr,
and I to my own house, accompanied by Joshua Beale and Richard Guy,
the 18th day of the seventh month, 1700.

In a short time after our Provincial Quarterly Meeting was held at Catherlough,
and my mind was inclined to be there; so I went in faith of the Lord`'s power,
though in much pain, and the Lord helped me to perform the journey.
When the service of the meeting was over, I returned home;
and soon after George Rooke came from Dublin to our Monthly Meeting at Mountmellick;
after which we travelled together in the King`'s county and county of Tipperary,
visiting some meetings; and also went to Clonmel to the Province Meeting for Munster,
which held two days for the worship of God and church discipline.

When that meeting was over we rode towards Dublin, and in three days got there;
the next day the National Half-year`'s Meeting began,
and many Friends from several parts of the nation came to it.
It held four days in doctrine and church discipline, and I met with some exercise;
but the Lord`'s power carried me through it, as at other times,
and we had a good heavenly meeting, and when over,
parted in the love of God and comfort of his blessed spirit; and I returned home.

About eight or ten days after, I was drawn in spirit to go again to Dublin,
which accordingly I did, accompanied by my son Tryal, and my son-in-law, William Fayle,
where I found service for truth`'s testimony, that required my being there at that time;
and sensible honest-hearted Friends were glad of my coming.
I stayed four meetings in Dublin,
and the Lord`'s power in his testimony was over opposite spirits.
One John Beck, who had professed truth, and had gone from Friends for a wife,
together with his wife, both appearing in our public meeting for the worship of God,
in a bitter and envious spirit, with railing accusations against Friends,
were publicly detected and their folly manifested,
and Friends were refreshed and comforted.
So being clear, I returned homewards with my two sons, and some other Friends.

That day I came to my son-in-law, William Fayle`'s, and next day to Ballynolert,
where I stayed a meeting with Friends, and then came home.
In the twelfth month our Province Meeting falling in course to be at the Moat,
I rode thither--it held part of two days, and was an heavenly comfortable meeting;
Friends were sweetly refreshed,
and parted in the sense of God`'s love upon their spirits.

I kept to adjacent meetings as they came in course, not being well that winter.
I felt a concern upon my spirit to visit some places in the north of England,
and on the 6th day of the third month, in the year 1701, I went from my house,
though not in health, and in two days came to Dublin very weary.
Next day the service of our National Meeting began,
and a great appearance of elders and Friends was there from several parts of the nation,
and the Lord`'s mighty power was with us, to our great comfort and satisfaction,
which made me easy over my illness.
The service of this meeting lasted part of six days.
