== Chapter XXV

[.chapter-synopsis]
* In 1704, he visits Friends in their National and Provincial Meetings
* In his sickness is resigned to the will of God
* Gives a summary of his life, faith, and practice, etc.

In the third month, 1704, the National Meeting of Friends being held at Dublin, as usual,
I went thither in the company of some Friends, and attended the service of that meeting,
which held three days in the worship of Almighty God,
and for promoting truth and righteousness among us.
Comfortable accounts were given from other meetings of the godly care of Friends in
their several meetings and quarters, for the honour of the blessed truth,
as also the good and preservation one of another;
and though some occasional exercise happened, yet the Lord`'s power went over it,
and our concluding meeting was full,
wherein large and heavenly testimonies were borne in the demonstration of
the spirit and power of our Lord and Saviour Jesus Christ,
to the comfort and refreshment of Friends;
in a sense of which we returned to our several places of abode.

Some time after I went to Munster Province Meeting at Clonmel,
which held most of two days, and was a refreshing comfortable meeting,
in the heavenly openings of the testimony of Jesus;
and in our parting one from another in tenderness of heart and true love,
we sweetly enjoyed the Lord`'s goodness, to our great comfort and satisfaction.
I went home in company of some Friends,
and kept to adjacent meetings as they came in course, being unable to take long journies,
by reason of weakness and pain over my whole body.

Leinster Province Quarterly Meeting at Mountmellick being near, I got to it,
though under affliction of body,
and the Lord enabled me to answer what service he required of me.
It held part of three days in worship and discipline, in both which,
through the Lord`'s assistance by his divine Spirit and power,
I bore a faithful testimony for him and his blessed truth;
so that if it were the last time the Lord would give me to appear in public testimony,
I found myself clear.

After the meeting I returned home, but my illness increased,
so that my whole body was under great affliction and pain, even nigh unto death;
no place could give me ease, and many Friends and elders came daily to see me;
some from far.
In these visits I was comforted, and by their fervent prayers,
through the tender mercy of God, the violence of the raging distemper somewhat abated,
so that my weak abilities were able to bear it.
Thomas Pearce from Limerick,
carefully applied things for my ease in this time of extremity,
as heretofore he had done upon the like occasions,
having accompanied me several times in travel, in the Lord`'s service,
both in this nation and England.

In the eighth month, 1704, in the seventy-seventh year of my age,
being under much affliction and weakness of body,
I was resigned unto the blessed will of the Lord, and were it his time,
would gladly have been dissolved and at ease, "`where the weary are at rest,
and the wicked cease from troubling.`"
For I was not afraid of death or the grave, but could say,
through the tender mercy of God, "`Death, where is thy sting?
Grave, where is thy victory?`"
through steadfast faith and hope in my Lord and Saviour Jesus Christ,
who suffered for me, and whom death or the grave could not hold; but who rose again,
and appears before the Father for me, as advocate, mediator and interceder.
In my youthful days he was pleased to visit me with the appearance of his holy Spirit,
to turn me from the evil of my ways, making me sensible of his judgments and mercies,
calling me by his grace to a reformation,
and also put me into his service in the ministration of the Word of Life,
and doctrine of his kingdom,
endowing me with a talent of his holy Spirit of understanding in doctrine and discipline,
for the benefit of his church.
In which I have laboured for the space of above fifty years,
according to my strength and ability, through many troubles,
deep exercises and perils of divers kinds, by sea and land,
which fell to my lot in the Lord`'s service,
both in the wilderness by robbers and blood-thirsty murderers,
by open opposers and enemies to truth,
and worst of all by false brethren under the same profession.
These things, and many other great exercises and straits,
the Lord`'s arm and gracious providence have still preserved me through,
and supported me over in the faith that gives the victory,
having blessed his work and given the testimony of his truth,
dominion to this present time.

It pleased the Lord to give me ease from my violent pain,
after a considerable time of affliction,
and the National Half-year`'s Meeting of Friends being at hand at Dublin, as usual,
I found some drawings in spirit to go to it, though my body was weak,
and according to appearance unfit to take a journey.
But I went in faith,
knowing that the Lord`'s strength had carried me through great weaknesses, deep exercises,
and sore afflictions, in his service; and according to faith in him,
strength was given me to perform that service,
to the satisfaction and comfort of many Friends.
After the meeting was over, which held three days, I returned home,
in the company of several Friends.

Soon after I went to Leinster Quarterly Meeting at Catherlough,
and the Lord`'s power was with us in an eminent manner,
to Friends`' comfort and encouragement in the service of truth.
It held part of three days in the worship of God and church affairs, and I returned home,
and kept to meetings as they came in course, both weekly and monthly.

In the beginning of the first month following,
I had drawings in my spirit to go to Dublin, which I did,
and was with Friends about a week, and at three public meetings for the worship of God,
as also at their men`'s meeting for church affairs;
and the Lord was pleased to fill my heart with his word and testimony, as at other times,
and to open many divine mysteries,
which I published in the demonstration of the spirit and power of the Lord Jesus,
in the public meeting, as he was pleased to give me ability and utterance.
In the conclusion of the testimony, in the fresh opening of life, I told the auditory,
that in the last calamity over this nation, that city felt little of it,
but heard the report,
and had not prized the Lord`'s mercies so as to
walk worthy of them in that great preservation;
and now, I was to tell them,
the Lord had a rod in store for the inhabitants of that city,
and I desired in submission to the will of God,
that it might not be such as would break them to pieces; and bid them remember,
that I had told them of it.

Another day I was sitting in a Friend`'s house in that city,
with several elders and brethren, and it sprang afresh in my heart to say to them,
that the Lord would make this earnestness of getting the riches of this world,
to many with whom he hath long striven,
and often faithfully warned of the danger thereof,
that they might be weaned from the same,
even as the flesh that God gave to the Jews in the wilderness,
when they slighted the bread which he gave them from heaven,
and lusted after the flesh-pots, onions and garlic, in Egypt.
