== Section XXIX.

In 1708 and 1711, he visited Munster, and attended both Monthly,
Provincial and National Meetings, in his old age,
to the joy and refreshment of faithful Friends.
In 1712, at the National Meeting in Dublin, he solemnly took his last leave of Friends;
after which he fell sick, and in three months time died, aged near eighty-five.

Finding my ability renewing,
and drawings upon my spirit to visit some parts of the province of Munster,
our Quarterly Meeting being at hand, by appointment at Castledermot,
I took that in my way towards Munster.
Here I met George Rooke, who went with me that journey in the Lord`'s service.
After the meeting we went to Waterford, and had a meeting, and next day to Clonmel,
where we had a meeting with Friends on the day following.

From thence we went to Joshua Fennell`'s, and had a meeting; so to Tipperary,
and had a meeting in the market-house,
where a great concourse of Friends and others assembled.
Then to Limerick, and the day following had a meeting at Six-miles-bridge,
in the county of Clare, so came back to Limerick,
and stayed another meeting there with Friends.
On the day following we went to Silver Mines,
and that evening had a meeting at the inn where we lodged, to which many people came,
and were attentive to hear the doctrine of Christ`'s kingdom,
which was preached to them in the spirit and power of the Lord Jesus Christ.

We then went to Birr, and on the first-day of the week,
had two meetings there with Friends,
and afterwards had a meeting with Friends at Walter`'s-town; one at the Moat,
and the day following one at Lismoiney;
in all which the Lord`'s spirit and power were with us,
and his goodness upheld us in the testimony of his blessed truth,
the Gospel of his kingdom being rightly divided,
and Friends refreshed in the Lord Jesus Christ.
Here I and my companion parted, and each of us returned home.
This was in the sixth month, 1708.

I kept to meetings near home, until our Half-year`'s Meeting at Dublin,
which began the 8th day of the ninth month.
I went thither, where many Friends came from several parts of the nation,
and an account of the affairs of truth and welfare of the churches was given.
Here I met with some exercise, but the Lord`'s power went over it,
blessed be his great name, who stands by and owns his testimony.
When the meeting was over, I returned home, and my body was weary with riding;
so I tarried near home, and frequented both Weekly, Monthly and Six-weeks`' Meetings.

I also was enabled to go to the following Half-year`'s Meeting at Dublin,
which began the 8th day of the third month, 1709; and some time after,
having drawings upon my spirit to visit Friends about the Moat, I went thither,
accompanied by Joshua Strangman,
and was at Friends`' meeting at the Moat and Walter`'s-town,
where we were well refreshed in the Lord Jesus Christ.

The Quarterly Meeting being at Castledermot, I went to it,
and the Lord`'s mighty power was with us, in the service of that meeting,
both in the public worship of God, and in meetings of discipline,
for promoting Gospel order among us,
and many things relating thereto were closely discoursed,
in a weighty sense of God`'s goodness on the spirits of sensible elders and brethren,
to our great comfort in the Lord Jesus Christ.

Some weeks after the Province Meeting for Munster being appointed at Limerick,
and I having a concern upon my spirit to be there, took my journey,
accompanied by Ralph Stephenson and my son Tryal.
We went to Birr, and stayed a meeting with Friends;
and on the day following I went to Limerick, and attended the Province Meeting there,
which held part of two days.
The Lord strengthened me mightily in the performance of this journey and service;
everlasting praises to his great name.

I kept to meetings near home, until about the time of our National Half-year`'s Meeting,
which began at Dublin the 8th day of the ninth month;
when I went in company of Richard Eves, to our Province Meeting,
which was held at Athy at that time; after which we went to Dublin,
and on the day following our National Meeting began,
where a great many Friends from several places convened,
and accounts were brought of the affairs of truth in the particular meetings.

Soon after I went to our Provincial Quarterly Meeting at Castledermot,
which held part of three days in the worship of God and discipline of the church,
and the sweet and comfortable presence of the Lord Jesus Christ was with us,
to Friends`' great refreshment.

In the third month, 1710, I went to our National Meeting at Dublin,
and accounts were given of the affairs of truth,
and of Friends`' concern in each province for its prosperity.
Soon after, our Quarterly Province Meeting being again at Castledermot, I went thither,
and stayed the service thereof, which was weighty;
the Lord hitherto renewing my strength in his service,
both in the inward and outward man.

Our next Six-weeks`' Meeting for Leinster Province being appointed at Ballycane,
in the county of Wicklow, I found a concern upon my spirit to be there,
and accordingly went, though feeble in body; and after the meeting was ended,
through the Lord`'s mercy, I got well home.
The National Half-year`'s Meeting at Dublin approaching,
I found the Lord`'s drawings fresh upon my spirit to be there,
though I was very feeble and weak in body; for the Lord`'s gracious promise was to me,
that I should not want strength and ability.
I accordingly went and had good service for the
Lord and the testimony of his blessed truth,
in which he wonderfully strengthened me over old age and other infirmities,
so that the journey was made easy.

1711+++.+++ Our Quarterly Meeting for Leinster being appointed at Castledermot,
having some drawings upon my spirit, I went thither,
and afterwards to our National Half-year`'s Meeting at Dublin;
in both which the Lord strengthened me in the service of his blessed truth,
in doctrine and church discipline, and the power of the Lord, in his testimony,
was over all.
When the service of these large and heavenly meetings was over,
finding myself unable to endure long journeys, I was content to rest in the will of God,
who had lengthened my time to old age, and done great things for me;
to whose great and worthy name be praise, glory and honour, for ever and evermore.

Having rested some time, and kept to meetings near home,
finding my ability something strong again,
and my mind drawn forth to visit Friends`' meetings in the province of Munster,
I set forward in the seventh month following,
accompanied by Richard Guy and Joshua Strangman, and came to Bin-,
where we had a meeting, and next day to Limerick, and had a meeting there,
and on the day following, Joshua Strangman returned home;
but Richard Guy and I went to Charlevil, and had a meeting with Friends.
On the next day to Cork, and had two large meetings on the first-day of the week.
From thence we went to Bandon, and so returned to Cork; and then came to Youghal,
and had a meeting in each place.
Friends showed great gladness to see me once more among them,
and we were sweetly refreshed in the Lord Jesus Christ, and one in another;
for the Lord`'s refreshing goodness went along in that visit,
and I had many sweet comfortable opportunities with Friends who came to see me,
besides public meetings.

At Youghal we parted with Friends in the tendering power of the Lord Jesus Christ,
who filled our hearts with his goodness, and went to Kilcommonbeg,
and had a meeting at Joshua Fennell`'s house with Friends of that quarter:
then we went to James Russel`'s, about three miles from the town of Tipperary,
and had a meeting with Friends of that part; here George Rooke from Dublin met me,
and we rode to Clonmel, and had a meeting, to which several Friends came,
who were going to Munster Province Meeting at Waterford.

We went in company with them, and alighted at Carrick at an inn,
to refresh ourselves and horses: soon after which I was taken with violent pains,
excessive vomiting and shaking of my whole body, so that it shook the bed I lay upon,
and I was not fit to travel that day nor the next.
After two days`' rest I found myself much easier; and on considering the matter,
I found freedom in my spirit to return homeward.
This journey was above two hundred miles, and I was then about eighty-three years of age.

When I had rested some time, and kept to our meetings for the worship of God,
I found my body something better, and able to travel short journies in truth`'s service;
and Leinster Province Meeting being at Castledermot, I went thither.
I also went to our National Half-year`'s Meeting at Dublin, in the ninth month,
and was enabled to answer the service required of me,
the Lord`'s power being eminently manifested for carrying on his great
work of a complete reformation in the church of Christ,
and maintaining his testimony both in doctrine and discipline.
When that meeting`'s service was over I returned to my house, and kept to our meetings,
as usually I had done, but found my body grow weaker and weaker,
yet my understanding sound.

Our next National Half-year`'s Meeting beginning the 8th day of the third month, 1712,
I found some drawings upon my spirit to be there,
and in the faith of the Lord Jesus Christ I went,
and the service of truth was carried on in great peace and concord;
and the Lord`'s blessed power enabled me to perform the part committed to me,
both in doctrine and discipline, to his praise and my comfort.
Here I took my leave of Friends,
never expecting to see their faces any more in that place.
When the service of that great meeting was over, which held about three days,
in the worship of God and church discipline, I went to my own house,
in company of my son, Tryal Edmundson, and Richard Eves,
and found my body could not endure to travel, being now near eighty-five years old.
