== Chapter XXX. A Supplement

[.chapter-synopsis]
* Several weighty expressions of William Edmundson on his death bed
* A brief account of his death and burial

This worthy elder, after his return home, attended meetings thereaway,
whilst of ability of body; also read over his journal and other papers,
and on the day before he took his bed, was at a burial near his own dwelling,
where he bore a living testimony to Friends and neighbours present,
advising all to make ready for such a time as that, viz. death;
and exhorting the young people to beware of pride and height; which testimony,
though short, was very reaching, a good power attending,
and he concluded in sweet and fervent prayer to the Lord.

Next day, being the 2nd of the sixth month,
a few hours after he had finished the reading of his writings for truth`'s service,
he took his bed of the illness whereof he died, and said he was willing to die,
and well satisfied to go out of this troublesome world, for his day`'s work was finished.

On the 4th of the said month he said to Friends present, I find my legs fail me,
and it is tedious to die upward--desiring the Lord would make his passage easy.
He requested that his will might be performed,
and the substance of his journal no way altered.
And soon after said, "`Lord Jesus Christ, thou great Physician, who canst cure me,
look upon me: I had rather die than live.`"
That night being very ill and full of pain, he was desirous to go to bed,
and when helped towards it, he kneeled down at the bedside,
and was enabled in the midst of his extremity to call upon God,
to the comfort and satisfaction of Friends present,
beseeching the Lord to abate in some measure the bitterness of the pain that lay on him,
which in a great degree was answered.
He got little sleep that night, yet he lay for the most part pretty easy and quiet;
and towards morning, being in a very tender frame of spirit,
he was truly thankful to God for his mercy and goodness, and did bless,
praise and magnify his great name for the same,
desiring those present to praise the Lord also on his behalf.

On the 5th day of the month, some Friends being in the room, sitting quietly by him,
he desired their prayers for him, for he was weak and not able to undergo much.
Soon after he got a little sleep, and when he awoke, besought the Lord to this effect:
"`forget not thy wonted mercies, but mitigate these pains, if it be thy will,
and stand not at a distance in this time of need: I pray thee, O Lord!
Touch, one touch with thy finger, and cure all.`"
A little after he ordered where his grave should be made,
and gave some advice and charges to his children.

On the 6th, he expressed to some Friends his concern and trouble of mind,
because of the pride and height that young people were gone into,
far wide from the humility and plainness that truth led Friends into in the beginning;
and said, one examples another therein;
his spirit seeming burdened under a sense thereof.
On going to bed, he renewed his supplication to the Lord,
not to forget his wonted kindness towards him.

On the 7th he said to his wife, "`I am now clear of the world and the things of it.`"
To Friends who came to visit him that afternoon, he said, "`Friends,
you would do well to retire to the Lord.`"
After a time of silent waiting, he prayed fervently to God to their great comfort;
and though the extremity of his distemper was great, yet he bore it patiently.
Friends from several parts coming to see him,
he frequently declared his zealous concern for truth`'s prosperity,
and the promotion of its government in the churches of Christ,
that not only those who were peculiarly concerned as
elders in the discipline and oversight of the church,
should be rightly qualified and gifted for that service--men of truth,
fearing God and hating covetousness;
but also that all who were admitted into close communion,
as members of men`'s and women`'s meetings, should be subject to truth,
and walk agreeably thereto in the whole course of their conversation.
When such came to visit him, who had not been subject to those wholesome rules,
established in the church for good order and discipline,
he did not spare to admonish and reprove them in the authority of truth for their good.

On the evening of the 10th, being in a heavenly frame of mind,
discernible to those near him, he spoke thus: "`heaven and earth, sea and dry land,
and all things shall be shaken; nothing must stand,
but what is according to the will of God: so look to it Friends.`"
And some time after; "`I lie here under pain, and would fain be removed;
but I am like one that pursues death, and it flees from me,
although I see not wherefore my time should be prolonged, my natural parts being decayed;
neither do I see anything left undone, which the Lord required of me,
when I had strength and ability,
or that the Lord chargeth me with any neglect or transgression.`"

On the 18th, as he lay, he spoke thus to some present; "`I have something to say to you,
if you have ears to hear it; the spirit of vanity is let loose, the Lord suffers it,
and it is like to make a separation.`"
At another time he said to some intimate Friends present:
"`there are wonderful things to be done, the Lord hath a mighty work to do,
that must be gone through, and there be few that see through it.`"

Several other weighty expressions dropped from the mouth of our dear,
ancient Friend in the time of his sickness,
some of which are inserted in the testimonies given forth by Friends,
who visited him near his end, and were eye and ear witnesses thereof.

Though many of his last sayings were not committed to writing,
yet what is here collected may demonstrate his zeal for
the glory of God and welfare of Sion to his latter end.
After about one month`'s sickness and pain of body, which was sharp to bear at times,
having run the race with patience, and kept the faith,
he departed this life in sweet peace with the Lord, in unity with his brethren,
and good-will to all men, the 31st day of the sixth month, 1712,
being nearly eighty-five years old,
and was buried the 4th day of the seventh month following,
in Friends`' burying place at Tineel, near his late dwelling-place,
accompanied to the grave by many Friends and others from several parts,
where divers testimonies were borne, from a lively sense of his manifold services,
perils and labours of love, both in this nation and islands abroad;
after which his body was decently interred, but his memorial lives among the righteous.

[.asterism]
'''
